task 06 started
Friend-LGA/msu_course_cpp_323 pull request #107
Opened 2021-11-24 18:17 UTC by kapkappa

2021-11-25 15:32 UTC, Friend-LGA requested changes

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation.cpp
> +Graph generate(Params params) {
`const` ref

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/logger.cpp
> +  mtx_.lock();
```cpp
std::lock_guard lock(mutex_);
```

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +  int threads_count_;
Зачем?

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +  std::mutex mtx;
😡😡

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +  void new_generate(const GenStartedCallback& gen_started_callback,
`new`?

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +      uni_cpp_practice::graph_generation::Params graph_generator_params);
`const` ref

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +    workers_.emplace_back([&]() -> std::optional<JobCallback> {
Указывай конкретно что захватываешь в лямбду

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +GraphGenerationController::~GraphGenerationController() {
Добавиь деструктор для `Worker`

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +}
Добавить `while`, пока все работы не закончились, потом остановить воркеров

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +  finish_flag = true;
Не помешает ассерт

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +  thread_ = std::thread([=]() {
Нужно проеврить, что ещё не запущено, ассерт

2021-11-25 15:32 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +    bool finish_flag = false;
Удобней было бы использовать что-то вроде
```cpp
enum class State { Idle, Working, ShouldTerminate };
```

2021-11-26 14:59 UTC, Friend-LGA requested changes

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation.hpp
> +  //      : depth(_params.depth), new_vertices_num(_params.new_vertices_num){};
Что за комментарии в коде ненужные?

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +    const uni_cpp_practice::graph_generation::Params& graph_generator_params)
Зачем повсюду пишешь `uni_cpp_practice` - просто лишние буквы, чем код короче - там лучше

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
>        gen_finished_callback(std::move(graph), i);
Почему у тебя `mutex` только на `finish_callback`?

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +  while (!jobs_.empty()) {
Не верно. Когда `jobs_` опустеет - не значит, что они все будут выполнены. Они все будут только взяты в работу на этот момент.

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
>  GraphGenerationController::~GraphGenerationController() {
В этом деструкторе нет необходимости раз воркеры итак остановят себя при удалении, дублирование кода, усложнение

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +  if (thread_.joinable())
перед `join()` они должны остановить себя.

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +    State state_flag_ = State::Idle;
Будешь у каждой переменной добавлять суффикс `flag`?
```suggestion
    State state = State::Idle;
```

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
>  void GraphGenerationController::Worker::start() {
А если был вызван `stop()` но `thread_.join()` вызван не был, тогда нужно заджойнить его здесь, перед тем, как создавать новый `thread_`

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +            return;
`Idle` теперь?

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +  std::mutex mutex_;
У тебя один `mutex` на все операции? Как думаешь, это правильный подход?

2021-11-26 14:59 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +    jobs_.emplace_back([gen_started_callback, gen_finished_callback, i,
Доступ к `join_` вроде бы должен быть синхронизован

2021-11-26 15:07 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +    State state_flag_ = State::Idle;
`std::atomic`?

2021-11-26 19:18 UTC, kapkappa commented on roman_kuprii/graph_generation_controller.cpp
>        gen_finished_callback(std::move(graph), i);
Потому что start_callback синхронизируется в логгере, а в finish_callback синхронизировать надо ещё и заполнение ветокра graphs как я понял (иначе бы и тут не синхронизировал)
Но в целом, могу убрать синхронизацию из логгера и полностью сдесь её сделать (добавить для start_callback)

2021-11-26 19:50 UTC, kapkappa commented on roman_kuprii/graph_generation_controller.cpp
>  void GraphGenerationController::Worker::start() {
Думаю логичней будет обратно в stop вернуть join наверное

2021-11-26 20:14 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
>        gen_finished_callback(std::move(graph), i);
Ты опять базируешь свои решение на дополнительном знании, которое у тебя есть. Твоя задача
- Сделать логгер потокобезопасным
- Сделать вывод `started_callback` и `finished_callback` тоже потокобезопасными, ибо мы не знаем что там происходит дальше внутри них.

2021-11-26 20:15 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
>  void GraphGenerationController::Worker::start() {
Можно и так

2021-11-26 20:25 UTC, Friend-LGA requested changes

2021-11-26 20:25 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +  int completed_jobs = 0;
Доступ к переменной осуществляется только из 1ого потока?

2021-11-26 20:25 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +      completed_jobs++;
`completed_jobs` не связана с логикой, которую блокирует `finish_callback_mutex_`. То, что ты сделал - это костыль, который может прокатить. если требуется овероптимизация для быстродействия. Наша же задача другая, поэтому не стоит перемешивать различную логику - это потенциально ведет к проблемам.

2021-11-26 20:25 UTC, Friend-LGA commented on roman_kuprii/graph_generation.hpp
> +  }
Функция в публичном интерфейсе для отладки нам не нужна

2021-11-26 20:25 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.cpp
> +}
Ты воркеров запустил, почему остановить не хочешь? Вроде вся работа уже выполнена, им тоже пора на отдых

2021-11-26 20:25 UTC, Friend-LGA commented on roman_kuprii/graph_generation_controller.hpp
> +  std::mutex get_job_mutex_;
Нигде не забыл его использовать?

2021-11-26 20:44 UTC, Friend-LGA requested changes
Падает
```
➜  temp git:(pr/107) ./main 
libc++abi: terminating with uncaught exception of type std::runtime_error: Failed to create file stream
[1]    72803 abort      ./main
➜  temp git:(pr/107) 
```

2021-11-26 21:31 UTC, Friend-LGA requested changes

2021-11-26 21:31 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +  }
1) Думаю просто `std::filesystem::create_directory(DIRECTORY_NAME)` хватило бы
2) Слишком длинная функция main()

2021-11-26 22:09 UTC, Friend-LGA approved these changes

2021-11-26 22:10 UTC, merged