tevfik_aksoy/task_06
Friend-LGA/msu_course_cpp_323 pull request #108
Opened 2021-11-24 19:53 UTC by AxoyTO

### [TASK_06 — Concurrent Graphs Generation](https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_06)

- Add prototype:
    - Draft
    - Add GraphGenerationController
    - thread, functional, list, lambda

2021-11-26 15:41 UTC, Friend-LGA requested changes

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +          new_vertices_num(params.new_vertices_num) {}
Зачем тебе `copy` конструктор?

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +   */
Что за ненужные комментарии?

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +        graphs.push_back(graph);
Ещё `write_to_file`

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.hpp
> +    using GenerateFinishedCallback = std::function<void(int, Graph)>;
Зачем перенес их внутрь `Worker`, они принадлежат `GraphGenerationController`
Кроме `GetJobCallback`, его действительно, можешь оставить здесь

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +  terminate_flag = true;
1) `lock` должен распространяться только на ту логику, которую нужно синхронизировать, а не на всю функцию
2) Для синхронизация простого флага, можно использовать `std::atomic`

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +GraphGenerationController::~GraphGenerationController() {
В первую очередь, ты обязан написать деструктор того объекта, который владеет потоком, и который обязан его удалить при остановке. Соответственно `~Worker()`

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +void GraphGenerationController::Worker::start() {
Нужно проверить на то что воркер ещё не был запущен

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +void GraphGenerationController::Worker::stop() {
Не помешает проверить что воркер был запущен.
Тебе, наверное нужна переменная состояния, что-нибудь вроде
```cpp
enum class State { Idle, Working, ShouldTerminate };
State state_ = State::Idle;
```

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +      } else if (terminate_flag) {
Зачем поменял местами?
Ты в первую очередь должен проверить, требуется ли остановка, а уж потом проверять, есть ли работа для выполнения. А ты делаешь наоборот, даже если требуется остановка, ты выполняешь всю работу перед этим. Это ошибка.

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +        [&gen_started_callback, this, &i, &gen_finished_callback]() {
Не нужно захватывать `this`, перечисляй каждую переменную, которую захватываешь

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +  thread_ = std::thread([this]() {
Не нужно захватывать `this`, перечисляй каждую переменную, которую захватываешь

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.hpp
> +    bool terminate_flag = false;
Naming Convention !!!

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +          const std::lock_guard lock(mutex_);
Синхронизируешь `finished_callback`, а как же `started_callback`?

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +    jobs_.emplace_back(
Как думаешь, `jobs_` должны быть синхронизированы? Есть к ним доступ из разных потоков?

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +  }
Функция `generate` должна завершиться, когда выполнена вся работа и воркеры остановлены:
1) Запуск `Workers`
2) Заполнение `jobs`
3) Ожидание выполнения всех `jobs`
4) Остановка всех `Workers`

Это все должно быть реализовано внутри `generate()`

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +          auto graph = graph_generator_.generate();
А где инициализация `graph_generator_`?

2021-11-26 15:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +  params_ = graph_generator_params;
Нет смысла хранить `params_` достаточно сразу инициализировать `graph_generator_`, что ты вообще забыл сделать

2021-11-27 08:32 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +   */
С прошлой задачи, удалил

2021-11-27 08:33 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.hpp
> +    using GenerateFinishedCallback = std::function<void(int, Graph)>;
+

2021-11-27 08:37 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +          const std::lock_guard lock(mutex_);
Понял

2021-11-27 08:48 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +          const std::lock_guard lock(mutex_);
Добавил

2021-11-27 08:52 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +  params_ = graph_generator_params;
Точно... И из-за этого я добавил copy constructor😳😐

2021-11-27 11:33 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +          new_vertices_num(params.new_vertices_num) {}
Для того, чтобы можно было присвоить в конструкторе GraphGenContr но на самом деле не нужно

2021-11-27 11:34 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +        graphs.push_back(graph);
Сделал

2021-11-27 11:38 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +      } else if (terminate_flag) {
Просто дало SEGVFAULT, перемещение это решило но все равно ошибка было, исправил

2021-11-27 11:40 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +void GraphGenerationController::Worker::start() {
+

2021-11-27 11:42 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +        [&gen_started_callback, this, &i, &gen_finished_callback]() {
хорошо

2021-11-27 11:43 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +void GraphGenerationController::Worker::stop() {
Понял

2021-11-27 11:44 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +GraphGenerationController::~GraphGenerationController() {
Хорошо

2021-11-27 11:45 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.hpp
> +    bool terminate_flag = false;
😳😳😐😐 Исправил

2021-11-27 11:55 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +    jobs_.emplace_back(
+

2021-11-27 11:56 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +  }
Хорошо, понял

2021-11-29 18:07 UTC, Friend-LGA requested changes
Ну почти :)

2021-11-29 18:07 UTC, Friend-LGA commented on tevfik_aksoy/graph_generation_controller.cpp
> +  assert(state_ != State::Working && "Worker is already working!");
```cpp
state_ == State::Idle
```
Почему ты считаешь, что мы можем стартовать его, когда он `shouldTerminate`?

2021-11-30 11:39 UTC, AxoyTO commented on tevfik_aksoy/graph_generation_controller.cpp
> +  assert(state_ != State::Working && "Worker is already working!");
Аа, да, ошибся и не понял, потому что не влияло на выполнение, но теперь понял
Исправил

2021-11-30 20:43 UTC, Friend-LGA requested changes
Не работает
```
Enter threads_count: 8
Enter graphs_count: 64
Enter max_depth: 4
Enter new_vertices_num: 4
30/11/2021 23:41:56: Graph 13, Generation Started
30/11/2021 23:41:56: Graph 39, Generation Started
30/11/2021 23:41:56: Graph 52, Generation Started
Assertion failed: (!has_edge_id(id, edge_ids_) && "Edge already exists in vertex!"), function add_edge_id, file graph.cpp, line 20.
30/11/2021 23:41:56: Graph 32766, Generation Finished {  
  depth: 0,
  vertices: 1, [1],
  edges: 0, {30/11/2021 23:41:56: Graph 32766, Generation Started
30/11/2021 23:41:56: Graph 32766, Generation Started
30/11/2021 23:41:56: Graph 32766, Generation Started
30/11/2021 23:41:56: Graph 32766, Generation Started
Assertion failed: (!has_edge_id(id, edge_ids_) && "Edge already exists in vertex!"), function add_edge_id, file graph.cpp, line 20.
[1]    79994 abort      ./temp/main
➜  tevfik_aksoy git:(pr/108) 
```

2021-11-30 22:13 UTC, Friend-LGA approved these changes
Моя вина, не подтянул все изменения, все работает ок

2021-11-30 22:17 UTC, merged