Shamil_latypov/task_05
Friend-LGA/msu_course_cpp_323 pull request #112
Opened 2021-11-26 11:44 UTC by 2Lapsha1

2021-11-26 16:19 UTC, Friend-LGA requested changes

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.hpp
> +  std::ofstream file_out_;
У нас ведь нет конструктора где мы задаем значение стрима. Значит он у нас может быть, а может не быть. Следовательно это опциональное значение.
"file_out" - файл, извне. Это не файл - это стрим. Плохое название.
```suggestion
  std::optional<std::ofstream> output_stream_;
```

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.hpp
> +  void set_file_output_name(const std::string& file_path);
Так как стрим у нас - опциональное значение, в таком случае имеет смысл и указывать файл, как опциональное значение. Соответственно, если передаем `std::nullopt` - значит нужно удалить стрим.
"set_file_output_name" - указать внешнее имя файла. Корявое название. Более того, ты указываешь не имя файла, а путь к файлу.
```suggestion
  void set_output_file_path(const std::optional<std::string>& file_path);
```

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.cpp
> +  file_out_ << text << std::endl;
И куда-же он пишет по-дефолту?
Нужно проверить, что стрим существует.
```suggestion
  if (file_out_.has_value()) {
    file_out_.value() << text << std::endl;
  }
```

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +void write_to_file(std::string graph_output, std::string file_name) {
`const` ссылка

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.hpp
> +#include <optional>
Списывал у кого-то, да?)) Библиотеку добавил. которую нужно использовать, а использовать не стал. Внимательнее надо быть.

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.hpp
> +#include <iostream>
Зачем?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.cpp
> +  assert(file_out_.is_open() && "File didnt open. Maybe Temp dir soesnt exist");
Это не баг в коде - это уже потенциально взаимодействие с операционной системой. В таких ситуация нужно использовать `exception` а не `assert`.
```suggestion
  throw std::runtime_error("Failed to create file stream");
```

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.cpp
> +#include <iomanip>
Зачем?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.cpp
> +#include <chrono>
Зачем?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/logger.cpp
> +#include <cassert>
Смысл?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +std::string gen_started_string(int i) {
Что за `i`???

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +constexpr int COLORS_MAX_COUNT = 5;
Это тебе зачем?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +  for (int i = 1; i < COLORS_MAX_COUNT; i++) {
```suggestion
  const auto colors = std::array<EdgeColor, 5> { Edge::Color::Grey, ... };
  for (const auto& color : colors) {
```

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +                    << graph.get_color_edge_cnt(0);
Решил что `0` настолько крут, что циклы не для него?

2021-11-26 16:19 UTC, Friend-LGA commented on shamil_latypov/main.cpp
> +    const auto output_graph = uni_cource_cpp::GraphPrinter();
`output_graph`, серьезно? Подумай ещё раз.

2021-12-02 14:27 UTC, 2Lapsha1 commented on shamil_latypov/logger.hpp
> +#include <optional>
Всего лишь подглядел, как класс Логгер реализовать Синглтоном

2021-12-02 18:32 UTC, closed without merging