nikolai chernyshov/task 04
Friend-LGA/msu_course_cpp_323 pull request #113
Opened 2021-11-29 12:12 UTC by nickcherr

2021-11-29 17:47 UTC, Friend-LGA requested changes

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
>  constexpr int VERTICES_COUNT = 14;
Не используется

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  }
Если тебе нужны и сеттер и геттер без дополнительной логике, то лучше просто изменить видимость переменной `depth_` на `public`, и удалить эти функции

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +            for (const auto& edge_id : get_vertex(vertex1_id).get_edge_ids()) {
Это оверкил, ещё один вложенный цикл делать. Зачем он вообще тебе здесь нужен?

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    })();
```suggestion
    const auto color = calculate_edge_color(std::min(vertex1_id, vertex2_id), std::max(vertex1_id, vertex2_id));
```

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +        set_vertex_depth(vertex2_id, get_vertex(vertex1_id).get_depth() + 1);
Опять дублирование, писал выше

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
Если уж ты везде проверяешь, первая вершина, или вторая, то и тут стоит решить, какую из них проверять

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +      depth_difference *= -1;
`std::abs`

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    Vertex& vertex = vertices_[vertex_id];
`get_vertex`

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  void set_vertex_depth(const VertexId& vertex_id, const int& depth) {
фундаментальные типы передают по значению

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +      depth_map_.push_back({});
А если разница = 5?

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  void add_edge_to_required_graph(const VertexId& vertex1_id,
Это зачем?

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
>    Graph build_required_graph() const {
Не используется

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +           vertex_num++) {
Ну что ты творишь. Вместо реальных данных. притягиваешь за уши какие-то другие
```suggestion
      const auto vertex_ids= graph.get_vertex_ids_in_depth(depth);
      for (const auto& vertex : vertex_ids) {
```

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +            graph.add_edge(current_vertex_num, added_vertex_num);
Что это за рандомные цифры?...
```suggestion
            const auto new_vertex_id = graph.add_vertex();
            graph.add_edge(vertex.id, new_vertex_id);
```

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  const std::vector<VertexId>& get_vertices_in_depth(int depth) const {
`get_vertex_ids_in_depth`

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    for (auto depth = (graph.get_depth_map()).begin();
```cpp
vertex_ids_in_depth
```
или просто 
```cpp
vertex_ids
```
а то не понятно, что за `depth`

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    for (auto depth = (graph.get_depth_map()).begin();
Есть подозрение, что ты итерируешься здесь по коллекции, при этом меняя её... Я бы написал по-другому, но, если работает, можешь оставить

2021-11-29 17:47 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    if (graph.get_depth() < 2)
А если там 0 и 1 глубина, что мешает желтые грани между ними добавить?

2021-11-29 17:54 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    if (graph.get_depth() < 2)
Желтые грани нельзя добавлять своим же потомкам, а т.к. у нас по идее ровно 1 вершина на 0 глубине, то все вершины на 1 глубине = её потомки
Позже все равно они бы отсеялись по условию, но зачем выполнять лишнюю работу

2021-11-29 18:01 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
>  constexpr int VERTICES_COUNT = 14;
Не совсем понял, что конкретно не используется?
Если Вы про GREEN/RED_EDGE_PROBA, то они используются в add_green/red_edges при построении графа(298 и 331 строки)
а если про VERTICES_COUNT, то оно используется в build_required_graph для построения графа из таска 2, но в принципе эта функция больше не нужна в этом и последующих тасках, могу убрать, если намек на это

2021-11-29 18:05 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +  }
Я рассуждал так, что если depth сначала присваивается 0, а уже потом в графе высчитывается реальная глубина и присваивается, то константой depth быть не может
Тогда, вероятно, стоит сделать ее приватной, чтобы ее не изменил кто-то, кому это не положено делать?
Или можно оставить public?

2021-11-29 18:12 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +  void add_edge_to_required_graph(const VertexId& vertex1_id,
т.к. сначала вершине приписывается глубина 0, то я решил, что до того, пока не посчитается и не присвоится реальная глубина, стоит положить в карту глубины 0, а потом удалить и положить в карту реальной глубины
но вообще согласен, можно и без этого

2021-11-29 18:21 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +            for (const auto& edge_id : get_vertex(vertex1_id).get_edge_ids()) {
нужен, чтобы проверять в случае если vertex1_id == vertex2_id что вершина не соединена сама с собой
наверное, просто не лучшая реализация получилась, попробую сделать по-другому

2021-11-29 18:31 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
учел при объявлении vertex1, vertex2

2021-11-29 18:36 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
>    Graph build_required_graph() const {
подскажите, пожалуйста, что Вы имеете в виду? если бы этот отрезок кода не использовался, то у меня бы не генерировались красные грани, но они генерируются

2021-11-29 21:27 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    for (auto depth = (graph.get_depth_map()).begin();
вроде бы карта глубин не меняется во время выполнения этой функции, потому что мы здесь добавляем желтые грани, а глубины(и, соответственно, карта) меняются только при добавлении серых граней
ну и судя по тем графам, которые генерируются, все работает

2021-11-30 09:17 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
>    Graph build_required_graph() const {
Ты строчку видишь, к которой комментарий? `Graph build_required_graph() const {`
Красные грани тут ни при чем. Гитхаб просто тебе для контекста дополнитепльный код вокруг комментария покаызвает

2021-11-30 09:21 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
>    Graph build_required_graph() const {
понял, спасибо!

2021-11-30 11:19 UTC, Friend-LGA requested changes

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    if (graph.get_depth() < 1)
Твой довод насчет того что на 0ой глубине все равно все связаны и нет смысла проверять, если `< 2`, был довольно адекватным. Зачем изменилд в таком случае? А вот комментарий можно было бы добавить

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +        for (const auto& vertex_id_on_next_depth : *(vertex_ids_in_depth + 1)) {
Имена отличаются только `on` - `in`, это потенациально приведет к путанице и ошибке. Переименуй боллее наглядно. `unconnected_vertex_ids` например

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +                                        graph.get_depth_map().begin()))) {
`get_depth_map` вызывается несколько раз в функции, не помешает вынести в локальную переменную.

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  void add_edge_to_required_graph(const VertexId& vertex1_id,
Опять не ту строчку смотришь. И не исправил. Этот комментарий к `add_edge_to_required_graph`

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
А если у тебя `vertex2.get_edge_ids().size() == 0`? Тут же нет прямой связи с `id`

2021-11-30 11:19 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    for (int iter = 0; iter <= depth - depth_map_size; iter++) {
`iter` или `it` сокращения обычно используют, когда работают с реальным объектом итератора, например `vector.begin()`. В твоем случае это обычная итерация по числу, обычно используют `i, j, k`

Более того, тут логичней будет запись 
```cpp
while (depth_map_.size() <= depth)
```

2021-11-30 11:41 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    return vertices_.back().id;
0 - чтобы добавить глубину корневой вершины
но лучше, наверное, просто инициализировать карту глубин через {{0}}

2021-11-30 11:46 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> -    }
потому что перестал туда добавлять(кроме, очевидно, корневой вершины)
сделал так, что глубина вершины заносится в карту глубин только после того, как реальная глубина посчитана, а 0, которым мы инициализируем глубину при создании вершины, добавлять в карту глубин, чтобы потом почти сразу удалить его, большого смысла нет

2021-11-30 11:59 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    const int depth_map_size = depth_map_.size();
если в условие цикла поставить depth_map_.size(), то у нас будет бесконечно добавляться новый элемент, пока программа не крашнется(я проверял), т.к. после 
depth_map_.push_back({}); 
depth_map_.size() увеличивается на 1

2021-11-30 12:04 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    const int depth_map_size = depth_map_.size();
P.S. изменил цикл с for на while, теперь действительно отпала необходимость в этой переменной

2021-11-30 12:23 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
заменил на 
if (vertex2.depth == 0) {
смысл от этого не поменялся, т.к. если вершина не соединена ни с одной гранью, то ее глубина = 0,
но код получился понятнее

2021-11-30 12:27 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
если вопрос состоял в том, почему именно для vertex2 проверяем это условие, а не для vertex1, то я объявил их так, что vertex2_id >= vertex1_id, поэтому vertex2 была создана позже, для нее и проверяем

2021-11-30 12:36 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> -    }
кажется, удалить это было логично, т.к. граф у нас односвязный + на глубине 0 только одна вершина, корневая

2021-11-30 20:46 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    return vertices_.back().id;
Я же тебе написал как лучше

2021-11-30 20:52 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> -    }
Получается, если я добавлю 10 вершин, а потом вызову `get_vertices_in_depth(0)`, то вернется только одна вершина? Где же это логично, это сломанная структура. Логика такая, что сначала вершины добавляются на 0ую глубину, а потом их глубина меняется, после их связывания

2021-11-30 20:56 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
Да, перепутал в прошлом комментарии, хотел написать `vertex1`. Ещё раз говорю, у тебя нет прямой связи по `id` предположим такой сценарий
```cpp
graph.add_vertex();
graph.add_vertex();
graph.add_vertex();
graph.add_edge(1, 2);
graph.add_edge(0, 2);
```
Тут твой код ошибочно решит, что цвет должен быть желтый, хотя по факту, цвет должен быть серый.

2021-11-30 20:58 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    return vertices_.back().id;
это я по невнимательности, исправил

2021-11-30 21:08 UTC, Friend-LGA requested changes

2021-11-30 21:08 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +  std::vector<std::vector<VertexId>> depth_map_{{0}};
Это с какого перепугу у нас в пустом графе будет в карте глубин лежать значение, когда там даже вершин нет

2021-11-30 21:08 UTC, Friend-LGA commented on nikolai_chernyshov/main.cpp
> +      // т.к. при создании серых граней у новых вершин пересчитывается глубина
nit: обычно комментарии сверху пишут

2021-11-30 22:14 UTC, nickcherr commented on nikolai_chernyshov/main.cpp
> +    if (vertex2.get_edge_ids().size() == 0) {
ок, с примером стало понятнее, спасибо
тогда правильно ли, что можно проверить обе вершины на наличие граней, и если хотя бы у одной из них граней нет, то тогда новая грань - серая?

2021-11-30 23:35 UTC, Friend-LGA approved these changes
👍

2021-12-01 05:59 UTC, merged