novikov_dmitry/task_06
Friend-LGA/msu_course_cpp_323 pull request #115
Opened 2021-11-30 18:04 UTC by dimchanov

2021-11-30 23:29 UTC, Friend-LGA requested changes

2021-11-30 23:29 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +  if (current_depth < params.depth) {
Лучше делать ранний выход, чем увеличивать вложенность
```cpp
if () {
  return;
}
```
Вероятность имеет смысл рассчитывать уже после проверки

2021-11-30 23:29 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
>  Graph GraphGenerator::generate() const {
А если у нас `depth == 0 || new_vertice_num == 0` у тебя ничего не сломается?

2021-11-30 23:31 UTC, dimchanov commented on novikov_dmitry/graph_generator.cpp
>    generate_blue_edges(graph);
В условии про синие не было, или я проглядел(

2021-12-01 00:02 UTC, dimchanov commented on novikov_dmitry/graph_generator.cpp
>  Graph GraphGenerator::generate() const {
вроде все работает, только нулевая вершина будет

2021-12-01 11:57 UTC, Friend-LGA requested changes

2021-12-01 11:57 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
>              not_binded_vertices.push_back(next_vertex_id);
не должно быть в локе

2021-12-01 11:57 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +      [&graph, &mutex_add, &parent_vertex_id ]() -> const auto {
зачем `const auto`?

2021-12-01 11:57 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +  double probability = get_color_probability(Edge::Color::Gray);
меняется?
Зачем `double`?

2021-12-01 11:57 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +                       &parent_vertex_id = parent_vertex_id, current_depth]() {
```suggestion
    jobs.emplace_back([this, &graph, &mutex_add, &jobs_counter,
                       &parent_vertex_id, current_depth]()
```

2021-12-01 12:47 UTC, Friend-LGA requested changes

2021-12-01 12:47 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +            return is_binding;
```cpp
return graph.check_binding(current_vertex_id, next_vertex_id);
```

2021-12-01 12:47 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +  const double probability = get_color_probability(Edge::Color::Gray);
float

2021-12-01 12:47 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +  auto worker = [&should_terminate, &mutex_jobs, &jobs]() {
`const`?

2021-12-01 12:57 UTC, Friend-LGA requested changes
Падает
```
➜  novikov_dmitry git:(pr/115) ./temp/main 
Enter the Depth of the graphs
8
Enter the Number of new vertices from each vertex of the graphs
4
Enter the Count of new graphs
8
Enter the Count of threads for graphs generation
4
A directory wasn't created
2021.12.01 15:56:20: Graph 1, Generation Started
2021.12.01 15:56:20: Graph 2, Generation Started
2021.12.01 15:56:20: Graph 4, Generation Started
2021.12.01 15:56:20: Graph 3, Generation Started
Assertion failed: (has_edge(id) && "Edge doesn't exist"), function get_edge, file graph.cpp, line 174.
[1]    82439 abort      ./temp/main
➜  novikov_dmitry git:(pr/115) 
```

2021-12-01 13:32 UTC, Friend-LGA requested changes

2021-12-01 13:32 UTC, Friend-LGA commented on novikov_dmitry/graph_generator.cpp
> +#include <iostream>
Зачем?

2021-12-01 15:10 UTC, Friend-LGA approved these changes

2021-12-01 15:15 UTC, merged