Add task 4
Friend-LGA/msu_course_cpp_323 pull request #117
Opened 2021-12-01 11:37 UTC by theonlymusya

2021-12-01 12:33 UTC, Friend-LGA requested changes

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  Vertex(const VertexId& _id, const int _depth) : id(_id), depth(_depth) {}
Глубина не должна указываться при создании, так как изначально она находится на 0ой глубине

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  const int depth;
Не будет константой

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  VertexId add_vertex(const int depth);
копия не передается как `const`

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +                const Edge::Color& edge_color);
Нужно высчитывать цвет здесь

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  bool have_vertices_in_depth(const int depth) const;
1) конст копия
2) Не очень гибкий интерфейс, будет лучше возвращать все вершины на глубине, и кому надо - узнает, пустой ли вектор или нет

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +#include <iostream>
?

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +}
Проверяется другая логика. Но по факту тебе эта функция вообще не нужна

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  return new_vertex_id;
Все новые вершины, по умолчанию должны находиться на 0ой глубине в `vertices_in_depth`

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +           "Vertices are already connected");
эта проверка должна быть валидной для всех цветов

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +VertexId Graph::add_vertex(const int depth) {
глубина не должна передаваться извне

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +void Graph::fill_vertices_in_depth(const int depth, const VertexId id) {
В дополнительном интерфейсе нужды нет, достаточно `add_vertex` и `add_edge`

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +const std::vector<VertexId> exclude_connected_vertices(
`get_unconnected_vertices`

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +    for (const auto& vertex_id_in_current_depth :
nit: Для это функции нет необходимости в карте глубины

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  for (int depth = 0; depth < graph.get_depth() - 2; depth++) {
Почему у тебя логика для генерации желтых и красных различается?

2021-12-01 12:33 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +}
??????!!!

2021-12-04 20:57 UTC, Friend-LGA requested changes

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +void Graph::fill_vertices_ids_in_depth(int depth, VertexId id) {
Раз уж договорились `VertexId` и `EdgeId` считать кастомными типами и передавать по `const` ссылке, то и продолжай так делать

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +    vertices_ids_in_depth_.resize(depth + 1);
1. Не логично, что ты проверяешь просто больше ли, а добавляешь всего 1 элемент.
    1) Либо проверяй что они равны и нам нужна новая глубина
    2) Либо добавляй количество элементов, равное разнице
2. У тебя есть интерфейс для получения глубины, вот его и используй
3. `resize()` работает, но такая логика больше сишная. Ты что хочешь сделать тут? Добавить новый элемент в вектор, вот и добавь новый элемент
```suggestion
  assert(depth <= get_depth());
  if (depth == get_depth())
    vertices_ids_in_depth_.emplace_back();
```

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  if (id != 0) {
1) Почему ты проверяешь `id`? У нас нет гарантии, что вершина с `id == 0` будет корневой. Логика притянута за уши.
2) Зачем вообще это проверяешь. Это ответственность не данной функции. Каждая функция должна быть максимально простой и специализированной. Данная просто переставляет вершины с 0ой глубины на другую, и не задумывается ни о чем лишнем.

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +    for (auto vertex_id_ind = vertices_ids_in_depth_[0].begin();
3 раза обращаешься к `vertices_ids_in_depth_[0]` - вынеси в переменную

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  fill_vertices_ids_in_depth(0, new_vertex_id);
Неверно, функция `fill_vertices_ids_in_depth` переносит вершины с 0ой на другую. Тебе же просто нужно добавить вершину на 0ую глубину. Это другая логика, и тебе для этого функция особо не нужна. Просто положи её в карту глубин прямо здесь.

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +std::vector<EdgeId> Graph::get_edge_ids(const VertexId& id) {
`const` ссылка

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  auto edge_color = define_edge_color(from_vertex_id, to_vertex_id);
Будет меняться?

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
>  }
1) Глубины должны обновляться только для  серых граней, наверное ошиблась, потому что скобочки не ставишь у `if` условий
2) Скорее не "заполнить на глубине", а "обновить глубину вершины"
```suggestion
  if (edge_color == Edge::Color::Gray) {
    const int new_depth = from_vertex.depth + 1;
    update_vertex_depth(to_vertex.id, new_depth);
  }
```
Соответственно функция и обновляешь глубину у вершины, и обновляет карту глубин. Будет более связанная логика, чем у тебя сейчас.

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +    return false;
Не правда. `is_connected` должна возвращать `true` для зеленых граней

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
Нет смысла делать копию, лучше вернуть `const` ссылку

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +bool should_be_created_new_elem(float probability) {
:) `should_be_created` имело смысл, если это было все название, в такой форме данное выражение употреблять нельзя)) назови тогда `should_create_new_element`

2021-12-04 20:57 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
>          auto random_vertex_id_in_prev_depth =
const

2021-12-04 21:56 UTC, theonlymusya commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
get_vertices_ids_in_depth у тебя возвращает ссылку на карту глубины, потом ты в цикле обходишь этот же объект по ссылке и вызываешь add_edge, который изменяет карту глубин. Соотвественно получается так, что ты обходишь объект одновременно изменяя его, поэтому ссылка у тебя ломается
тебе нужно брать не ссылку, а копию от get_vertices_ids_in_depth

Мы же обсудили это и исправили...

2021-12-04 22:15 UTC, theonlymusya commented on tamara_gadieva/graph.cpp
> +  auto edge_color = define_edge_color(from_vertex_id, to_vertex_id);
Таки я возвращаю значение временного объекта

2021-12-04 23:37 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +  auto edge_color = define_edge_color(from_vertex_id, to_vertex_id);
`const`?

2021-12-04 23:38 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
Да, только копию ты должна делать на уровне выше, там где вызываешь `get_vertices_ids_in_depth()`
А сам интерфейс этой функции должен возвращать `const` ссылку, она не должна решать, нужно делать копию или нет. Это решение принимает пользователь графа.

2021-12-07 18:54 UTC, theonlymusya commented on tamara_gadieva/graph.cpp
> +    for (auto vertex_id_ind = vertices_ids_in_depth_[0].begin();
Возникали разные ошибки при попытке использовать переменную...

2021-12-08 13:09 UTC, Friend-LGA requested changes

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
1) ссылка на возвращаемый вектор
2) Тебе вообще не нужен этот метод, удали

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
>    auto new_vertex_id = get_new_vertex_id();
`const`

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +const std::vector<EdgeId>& Graph::get_edge_ids(const VertexId& id) {
метод тоже `const`

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +    return true;
Это что же, если `id` равны, то у нас всегда есть грань? Надо проверить что существует зеленая грань от вершины к ней самой, и в этом случае вернется `true`.

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  const std::vector<EdgeId>& get_edge_ids(const VertexId& id);
`const` метод

2021-12-08 13:09 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
>    std::vector<VertexId> get_vertices_ids_in_depth(int depth);
Тебе не нужна `non-const` версия этого метода

2021-12-09 14:56 UTC, Friend-LGA approved these changes
🎉

2021-12-09 15:07 UTC, merged