maxim_grabovskiy/task_04
Friend-LGA/msu_course_cpp_323 pull request #119
Opened 2021-12-01 23:40 UTC by maximgrab

2021-12-07 09:34 UTC, Friend-LGA requested changes

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    explicit Vertex(VertexId _id, int _depth) : id(_id), depth(_depth) {}
передавать в конструктор `depth` смысла нет, так как по логике, вершина всегда добавляется изначально на 0ую глубину, и потом глубина меняется во время создании грани к этой вершине. Так как глубина - это минимальное количество шагов от корня до этой вершины

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    vertexes_[newVertexId].depth = vertexes_[parentId].depth + 1;
Глубина должна обновляться внутри `add_edge`, так как она зависит именно от количества граней.

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    vertexIdByDepth_[0].emplace_back(0);
Нельзя брать данные с потолка
```suggestion
    const auto& new_vertex = vertexes_.emplace_back(newVertexId, 0);
    vertexIdByDepth_[0].emplace_back(new_vertex.id);
```

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  map<int, vector<VertexId>> vertexIdByDepth_;
Нет смысла использовать `map`, глубина начинается с 0 и увеличивается последовательно на 1. Обычный вектор подходит в самый раз

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  void generate_gray_edges(Graph& graph) const {
Только `Graph generate()` - публичный метод, все остальные нам не нужны как часть публичного интерфейса, верно?

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    std::bernoulli_distribution grayGenerationDistribution;
В каждой функции дублируешь эту логику, вынеси в отдельную функцию

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      }
А что если нам не повезло, и ни одной новой вершины не создалось, но мы ещё не дошли до запрашиваемой глубины? Надо бы проверить и прервать цикл в таком случае

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    std::bernoulli_distribution greenGenerationDistribution(0.1);
`0.1` и остальные аналогичные цифры - `magic numbers`, нужно вынести в глобальные константы

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        auto randomPreviousVertexId = graph.getVertexIdByDepth(
Почему `previous`, она же на последующей глубине через 2 находится. Скорее уж `next` тогда?

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +            2)[rand() % graph.getVertexIdByDepth(vertex.depth + 1).size()];
https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        auto const& connectionsVector = graph.getConnectionsVector(vertex.id);
Уже говорили про названия `...Vector, ...Graph, ...Int`, все типы будешь дублировать в названии? Название должно отражать суть.
```cpp
getConnectedEdges
```
Видимо в прошлом ревью проглядел

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +          vertex.depth < params_.depth - 2) {
Логично было бы сначала проверить на соответствие глубины, а потом генерировать вероятность

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        auto randomPreviousVertexId = graph.getVertexIdByDepth(
Тебе нужно получить не просто рандомную, а рандомную + `unconnected`
Вынеси эту логику в отдельную функцию, что-нибудь типа
```cpp
getUnconnectedVertexId(VertexId vertexId, const std::vector<VectorId>& vertexIds)
```
Передаешь туда список всех вершин с определенной глубины, и она тебе возвращает рандомную несоединенную вершину.

И, наверное, тебе ещё понадобится расширить интерфейс графа, чтобы проверять, соединены вершины или нет, например:
```cpp
bool isConnected(VertexId fromVertexId, VertexId toVertexId) const;
```

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +int const intInput() {
Возвращать конст копию данных нет смысла, так как это копия, нам не важно, что с ней будет происходить дальше

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    const int new_vertices_num = 0;
Ты вроде по-другому пишешь `const`

2021-12-07 09:34 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  const int depth = intInput();
1) А пользователь понимает, что он должен вводить? Не вижу, чтобы ты где-то сообщал пользователю, что от него ожидается.
2) Где информирование об ошибке? просто `error` недостаточно.

2021-12-08 10:37 UTC, Friend-LGA requested changes

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return 0;
```suggestion  
  assert(vertexIds.size() > 0 && "vertexIds can't be empty");
  const auto unconnected_vertex_ids = get_unconnected_vertex_ids(vertexId, vertexIds);
  if (unconnected_vertex_ids.size() == 1) {
   return unconnected_vertex_ids[0];
  }
  std::random_device seed;
  std::default_random_engine generator(seed());
  std::uniform_int_distribution<> idDistribution(0, vertexIds.size() - 1);
 return unconnected_vertex_ids[idDistribution(generator)];
```

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    auto const& connections = graph_.getconnections(vertex.id);
```cpp
edge_ids
```

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  bool probability(float p) const {
Однобуквенные названия - плохо
```cpp
check_probability
```

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +          if (!generated)
Не тот цикл

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    bool generated = 0;
Нет смысла объявлять вне цикла
```cpp
true || false
```

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    for (auto vertex : graph.getVertexes()) {
`const` reference

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      for (auto parrentId : graph.getVertexIdByDepth(currentDepth)) {
const

2021-12-08 10:37 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    std::cout << ((input < 0) ? "Error: <0" : "Error: !=int") << "\n";
На человеческом языке

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      for (int i = 0; i < (int)vertexIdByDepth_[0].size() - 1; i++) {
Проще сразу взять итератор, раз он тебе итак нужен
```cpp
auto& zero_depth = vertexIdByDepth_[0];
for (auto it = zero_depth.begin(); it != zero_depth.end(); it++) {
```

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
>      edgeConectionMap_[toVertexId].push_back(newEdgeId);
1) А если `color == green`? Ты 2 раза сделаешь одно и тоже
2) Логично это действие делать после того, как грань создана, а не до

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        vertexIdByDepth_.emplace_back();
Что-то сложно
```suggestion
      if (vertexes_[toVertexId].depth == vertexIdByDepth_.size()) {
        vertexIdByDepth_.emplace_back();
      }
```

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
>        vertexes_[toVertexId].depth = vertexes_[fromVertexId].depth + 1;
Ты много раз вызываешь одно и тоже
```cpp
vertexes_[fromVertexId];
vertexes_[toVertexId];
```
Чем 100 раз делать одно и тоже, лучше создай временные переменные
```cpp
const auto& fromVertex = vertexes_[fromVertexId];
const auto& toVertex = vertexes_[toVertexId];
```

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    int depth = 0;
Лучше не хранить глубину внутри вершины, это ответственность графа, 
```cpp
class Graph {
  std::unordered_map<VertexId, Depth> vertex_depths_;
}
```
И добавь тип для глубины `using Depth = int;`

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return true;
Это как так? Вершина связана сама с собой, только если есть грань, а не просто так.

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +          connected || (getEdge(connections[i]).fromVertexId == toVertexId);
Какая-то сомнительная запись. Зачем нам выполнять работу, если мы уже нашли результат?

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  VertexId getUnconnectedVertexId(VertexId vertexId,
Не исправлено

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return -1;
Насколько я помню, мы обсуждали, что так делать нельзя

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    return (notConnected[rand() % notConnected.size() - 1]);
`rand() % number` - это `C`
Используй `std::uniform_int_distribution`

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  string getEdgeColor(Graph::Edge const& edge) const {
1) Ты тут не цвет пытаешься получить, а `Edge::Color` перевести в строку. Название неверное. Назови по логике остальных методов `print_edge_color`
1) Передаваемый аргумент неверный, зачем ты передаешь `Edge`, ты должен передавать `Edge::Color`, все остальное этой функции не интересно

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        break;
`break` после `return` нет смысла писать

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        return "gray";
У нас нет `default`, все цвета имеют определенные значения.

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      for (auto parrentId : graph.getVertexIdByDepth(currentDepth)) {
Не исправлено

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      bool generated = 0;
Это не `int` а `bool`

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      float generationProb = ((100.0 - (step * (currentDepth))) / 100);
const

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    for (auto vertex : graph.getVertexes()) {
Не исправлено

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
>          auto randomNextVertexId = graph.getUnconnectedVertexId(
const

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
>        for (auto parrentId : graph.getVertexIdByDepth(currentDepth)) {
`parent` пишется с 1 `r`

2021-12-21 15:38 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    auto const& connections = graph_.getconnections(vertex.id);
Не исправлено

2021-12-21 15:41 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return 0;
Не исправлено

2021-12-21 15:42 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +                     (getEdges()[connections[i]].fromVertexId == toVertexId);
Не исправлено

2021-12-21 15:42 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +  bool isConnected(VertexId fromVertexId, VertexId toVertexId) const {
Не исправлено

2021-12-21 15:46 UTC, Friend-LGA requested changes
Гитхаб заглючил, меняю статус вручную

2021-12-22 00:31 UTC, maximgrab commented on maxim_grabovskiy/main.cpp
> +        vertexIdByDepth_.emplace_back();
Не эквивалентная замена

2021-12-22 16:01 UTC, Friend-LGA requested changes

2021-12-22 16:01 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        auto randomNextVertexId = getUnconnectedVertexId(
const

2021-12-23 11:14 UTC, Friend-LGA requested changes

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      if ((int)vertexIdByDepth_.size() - 1 < (newDepth))
Зачем миллион скобочек

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    return Edge::Color::Gray;
```cpp
throw std::runtime_error("Failed to calculate the color");
```

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return false;
!?!?!?!

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    return "";
`throw`

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      return vertexId;
```cpp
std::optional<VertexId> getUnconnectedVertexId();
const auto vetex_id = getUnconnectedVertexId();
if (vertex_id.has_value()) {
  vertex_id.value()..
}
```

2021-12-23 11:14 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
>    std::cout << graph_json << std::endl;
В одном стиле

2021-12-24 13:06 UTC, Friend-LGA requested changes

2021-12-24 13:06 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    return false;
```cpp
if () {
  return true;
}
else {
  return true;
}
return false;
```

2021-12-24 13:06 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +      const std::vector<VertexId>& vertexIds,
Продолжаешь писать в разных стилях

2021-12-24 13:06 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +        auto const NextVertexesIds = getUnconnectedVertexIds(
Названия с большой буквы?!?

2021-12-24 13:06 UTC, Friend-LGA commented on maxim_grabovskiy/main.cpp
> +    throw("line 102 wrong vertex ids");
1) без дебаг
2) эксепшены должны выкидывать эксепшены
```cpp
throw std::runtime_error("message");
```

2021-12-24 13:22 UTC, Friend-LGA approved these changes
🎉

2021-12-24 16:28 UTC, merged