anton_potapov/task_05
Friend-LGA/msu_course_cpp_323 pull request #120
Opened 2021-12-02 06:27 UTC by Flagro

Anton Potapov task_05

2021-12-08 10:35 UTC, Flagro commented
В общем с ленивыми вычислениями какая-то сложная логика получается, если пользователь адекватный и использует везде константные ссылки и прочее. В общем, проблема такая: появляется ошибка как только мы начинаем использовать константную ссылку на неконстантный объект (например создали в `main` граф, передали его в принтер, вывели, добавили ребер, и опять вывели). В принтере лежит константная ссылка, а при добавлении ребер мы вообще не думаем об обновлении глубин, поэтому вывести корректный граф у нас не получится никак. Долго думал как это фиксить, в итоге понял, что вся проблема в константных интерфейсах - они возвращают ссылку на внутреннюю структуру, которую не обновляют и не могут обновить. В итоге единственный вариант - это возвращать в таких методах обновленную копию структуры, не меняя объекта. В целом, не считая возвращения копии, с точки зрения пользователя получилось достаточно приятно, но внутри класса еще придется поработать. Коммит, где я все это переделал: ac1925744e3fac2ac42d49d44c7aeadcd2bc22f2.

Сейчас почти уверен, что генератор графа у меня интерфейс использует не совсем оптимально, но потенциал для превосходства ленивых вычислений есть)

2021-12-13 13:21 UTC, Friend-LGA requested changes
Будем смотреть, когда статус изменится с черновика

2021-12-13 13:29 UTC, Flagro commented
Если в ленивых вычислениях написать правильные интерфейсы (до этого у нас интерфейсы могли выдавать невалидные вещи), то с конструкторами по идее даже возиться не надо. Убрал их cf673641d154b01b885f51e1713d23ca69b7e35a, осталось допилить нормальные интерфейсы (уже почти готово)

2021-12-13 13:37 UTC, Flagro commented
И константный и обычный интерфейс будут работать на ленивых вычислениях, при чем быстро. Единственное отличие: при работе с константным интерфейсом не будет запоминаться новое место, с которого надо начинать bfs (но это и нормально, если у нас сам объект константный, то он меняться не будет и значение, которое было возвращено этим интерфейсом можно сохранить и использовать, а если у нас константная ссылка на неконстантный объект, то эти флаги оптимизации будут обновляться в этом неконстантном объекте и будут использованы через константный объект при вычислении интерфейс, то есть банить константные интерфейсы наверное все таки не придется)

2021-12-13 13:56 UTC, Flagro commented
Еще добавлю оптимизации bfs под разные интерфейсы (например, нам не надо пересчитывать все глубины, чтобы узнать глубину одной вершины)

2021-12-15 15:28 UTC, Friend-LGA requested changes

2021-12-15 15:28 UTC, Friend-LGA commented on anton_potapov/main.cpp
> +    auto graph_printer = GraphPrinter(graph);
const?

2021-12-15 15:28 UTC, Friend-LGA commented on anton_potapov/main.cpp
> +std::string print_graph_description(const Graph& graph) {
Перенеси в `GraphPrinter`

2021-12-15 15:28 UTC, Friend-LGA commented on anton_potapov/main.cpp
> +      !std::filesystem::exists(temp_directory_path)) {
Необязательно

2021-12-16 11:07 UTC, Flagro commented on anton_potapov/main.cpp
> +      !std::filesystem::exists(temp_directory_path)) {
готово 08be08d5e3a89c42444ea01313e7467ff6db0ec8

2021-12-16 11:10 UTC, Flagro commented on anton_potapov/config.cpp
> +namespace config {
08d545c8c2e7518154fe927751612d74779c9ec3

2021-12-16 11:12 UTC, Flagro commented on anton_potapov/main.cpp
> +std::string print_graph_description(const Graph& graph) {
смешалось вместе с большим коммитом fdc491c89552a55a2ddde39deb1235e15279eca7

2021-12-16 13:28 UTC, Flagro commented on anton_potapov/graph_printer.hpp
> +  const Graph& graph;
f2e2ac431630423d70071ec34b82513b99662e96

2021-12-16 13:30 UTC, Flagro commented on anton_potapov/graph_printer.hpp
> +  std::string print_edge(const Edge& Edge) const;
de139083da668600c086a0c0a2a7f4db2fdf398d

2021-12-16 13:35 UTC, Flagro commented on anton_potapov/logger.cpp
> +  return *logger;
b31e1bdc8dd602c548d03eab356e006679b8a9a7

2021-12-16 13:51 UTC, Flagro commented on anton_potapov/main.cpp
> +      << graph.edge_with_color_cnt(uni_cource_cpp::EdgeColor::Green)
3a8f5afe9fbbc2f075cfa0af90bb4a9dcfe99185

2021-12-16 13:52 UTC, Flagro commented on anton_potapov/main.cpp
> +    auto graph_printer = GraphPrinter(graph);
9aacc737e368b61f0cfcb46fce35b5e85f3bd82d

2021-12-16 13:54 UTC, Flagro commented on anton_potapov/graph_printer.cpp
> +  const auto vertices = graph.vertices();
7ff2670500b57f85edd3a5b33c92edaa2ff28fd1

2021-12-16 14:13 UTC, Flagro commented on anton_potapov/main.cpp
> +      << "gray: " << graph.edge_with_color_cnt(uni_cource_cpp::EdgeColor::Gray)
a7a6446895c7a2d0ca5a5193f0947d71a9ef9b80

2021-12-16 14:13 UTC, Flagro commented on anton_potapov/graph.cpp
> +std::string get_edge_color_string(const EdgeColor& color) {
a7a6446895c7a2d0ca5a5193f0947d71a9ef9b80

2021-12-16 14:21 UTC, Flagro commented on anton_potapov/logger.hpp
> +  Logger() = default;
9d1a014d1c993333d3d8825b017ce58c106d57da

2021-12-16 14:45 UTC, Friend-LGA requested changes

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph_traverser.cpp
> +      const auto vertices_at_depth_before_max_correct =
Почему копия?

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph_traverser.cpp
> +        known_depths.at(max_correct_depth);
Уверен насчет копии?

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph_printer.cpp
> +  const std::vector<EdgeColor> edge_colors = {
`std::array`

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph.cpp
> +std::set<EdgeId> Graph::edge_ids_with_color(const EdgeColor& edge_color) const {
```cpp
unordered_map<Color, std::set<EdgeId>>
```
+ возвращай ссылку

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph.cpp
> +const std::set<EdgeId> Graph::connected_edges(const VertexId& vertex_id) const {
почему копия?

2021-12-16 14:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  int max_depth();
`depth()`

2021-12-16 14:45 UTC, Flagro commented on anton_potapov/graph_traverser.cpp
> +      const auto vertices_at_depth_before_max_correct =
a9e447a6c753f41af414cf5516c4c41c5d3a5a70

2021-12-16 14:46 UTC, Flagro commented on anton_potapov/graph_traverser.cpp
> +        known_depths.at(max_correct_depth);
a9e447a6c753f41af414cf5516c4c41c5d3a5a70

2021-12-16 14:48 UTC, Flagro commented on anton_potapov/graph_traverser.cpp
> +      const auto vertices_at_depth_before_max_correct =
то есть 42bd0b18e2f0a431bb5e94580d3cfd7d482452ff

2021-12-16 14:53 UTC, Flagro commented on anton_potapov/graph_printer.cpp
> +  const std::vector<EdgeColor> edge_colors = {
3824a5dba5c5f8b03edb21ca391ff53bda03ca15

2021-12-16 15:21 UTC, Flagro commented on anton_potapov/graph.cpp
> +std::set<EdgeId> Graph::edge_ids_with_color(const EdgeColor& edge_color) const {
5bece0e1bba9746ade8dd7a24baf87dcaf6032df

2021-12-16 15:22 UTC, Flagro commented on anton_potapov/graph.cpp
> +const std::set<EdgeId> Graph::connected_edges(const VertexId& vertex_id) const {
76f74aaf355fb1158dffc53022911722012f7a2e

2021-12-16 15:36 UTC, Friend-LGA requested changes

2021-12-16 15:36 UTC, Friend-LGA commented on anton_potapov/graph.cpp
> +  static std::set<EdgeId> ans;
`result`

2021-12-16 15:37 UTC, Friend-LGA approved these changes
🎉

2021-12-16 15:37 UTC, Flagro commented on anton_potapov/graph.cpp
> +  static std::set<EdgeId> ans;
longer variable names are better variable names

2021-12-16 15:40 UTC, merged