tevfik_aksoy/task_06
Friend-LGA/msu_course_cpp_323 pull request #123
Opened 2021-12-02 13:29 UTC by AxoyTO

[**TASK_06 - Реализовать многопоточную генерацию графа**](https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_06)

2021-12-04 22:54 UTC, Friend-LGA requested changes

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +      [&logger, &graphs](int index, const Graph& graph) {
Почему изменил? Это `callback`, который должен возвращать объект графа, и передавать его владение нам. А ты передаешь ссылку, подразумевая, что кто-то другой им владеет, и нам в таком случае придется делать копию всего графа.

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
>    }
Избавься от лишних выводов в консоль. У нас уже вся необходимая информация логируется с помощью логгера.

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
>        const auto destination = vertices_in_depth[j + 1];
Иммеет смысл делать эти копии после проверки на вероятность

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
>              filter_connected_vertices(vertex_id, vertices_next, graph);
А сюда передать `mutex` не следовало бы?

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  enum class State { Idle, Working, ShouldTerminate };
это лишнее

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  std::atomic<State> state = State::Idle;
достаточно boolean флага, `should_terminate`

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  std::mutex job_mutex;
`graph_mutex`?
Лучше называть мютекс по именно той логике, которую он блокирует

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  std::mutex worker_mutex;
`jobs_mutex`

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  std::array<std::thread, MAX_THREADS_COUNT> threads;
А если  `new_vertices_num <  MAX_THREADS_COUNT`, есть ли смысл плодить лишние потоки?

2021-12-04 22:54 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +                                          const VertexDepth depth) const {
const только для ссылок

2021-12-05 08:00 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
>              filter_connected_vertices(vertex_id, vertices_next, graph);
Не очень понял куда именно, в функцию или после? Если после, так падает программа, но добавил в функцию

2021-12-05 08:01 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
>              filter_connected_vertices(vertex_id, vertices_next, graph);
После или в функции не очень понял

2021-12-05 08:03 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
>        const auto destination = vertices_in_depth[j + 1];
Да, так лучше, исправил, спасибо

2021-12-05 08:04 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
>    }
Избавился

2021-12-05 08:05 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +      [&logger, &graphs](int index, const Graph& graph) {
Изменил по предложению IDE, не заметил о последствиях. Исправил

2021-12-07 08:55 UTC, Friend-LGA requested changes

2021-12-07 08:55 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
>        result.push_back(vertex_id);
Что ты здесь синхронизируешь, локальную переменную `result`?

2021-12-07 08:55 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +  VertexDepth depth = 0;
В этой переменной нет смысла, просто передай `1`, конечно, это не очень наглядно, но контекст можно понять из аргументов функции, хотя бы

2021-12-07 09:22 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
> +  VertexDepth depth = 0;
+

2021-12-07 12:02 UTC, Friend-LGA requested changes

2021-12-07 12:02 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
>        result.push_back(vertex_id);
Нам нет нужды синхронизировать и `result.push_back();`
Нужно синхронизировать только граф - `graph.are_vertices_connected();`

2021-12-08 11:34 UTC, Friend-LGA requested changes

2021-12-08 11:34 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> -std::vector<VertexId> filter_connected_vertices(
верни

2021-12-08 11:34 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +/*
Комментарии не оставляй

2021-12-08 12:20 UTC, Friend-LGA approved these changes

2021-12-08 12:21 UTC, merged