roman_kuprii/task 06
Friend-LGA/msu_course_cpp_323 pull request #124
Opened 2021-12-02 16:08 UTC by kapkappa

2021-12-04 22:39 UTC, Friend-LGA requested changes

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.hpp
> +  Graph generate();
`const` метод

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +  int new_vertices_num = params.new_vertices_num;
1) const
2) так ли тут нужна эта переменная

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +  std::mutex modify_mutex;
`modify` что, можно конкретней? например `graph_mutex`

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +                          int current_depth) {
Много аргументов. Нужно стараться держаться в пределах 4ёх, лучше меньше.
`params` - это приватное поле, просто сделай функцию тоже приватным методом генератора, тогда можно будет брать `params_`

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
>    int new_vertices_num = params.new_vertices_num;
1) const
2) используются 1 раз, нет нужды в переменных

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +  }
1) лучше сразу инициализировать в константу
2) что за жесть `new_vertex_id = work_graph.get_vertices().back().get_id();`
```suggestion
  const VertexId new_vertex_id = []() {
    const std::lock_guard lock(modify_mutex);
    const auto new_vertex_id = work_graph.add_vertex();
    work_graph.connect_vertices(parent_vertex_id, new_vertex_id, true);
    return new_vertex_id;
  }()
```

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +  } else {
`else` можно не писать, чтобы вложенность не увеличивать.

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +    for (int iter = 0; iter < new_vertices_num; iter++) {
`iter` обычно используется, когда ты оперируешь итератором, например `vector.begin()`
Для обычных циклов с перечислением, обычно используют `i`, `j`, `k`

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +  for (int i = 0; i < MAX_THREADS_COUNT; ++i) {
А если `new_vertices_num < MAX_THREADS_COUNT` есть ли смысл создавать лишние потоки?

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
>          if (!work_graph.is_connected(adjacent_vertices[0],
А это не надо синхронизировать?

2021-12-04 22:39 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
>      if (!work_graph.is_connected(start_vertex.get_id(), start_vertex.get_id()))
Зачем проверяешь, у нас вроде никто больше зеленые грани не создает

2021-12-05 18:37 UTC, kapkappa commented on roman_kuprii/graph_generator.cpp
>          if (!work_graph.is_connected(adjacent_vertices[0],
Ну, я проверяю есть ли ребро между вершинами на определённых глубинах, и кроме этой функции создать ребро между ними никто не может. Но эту проверку добавил во все функции в начале, когда ещё эта функция вызывалась из мэйна, чтобы если функцию вызвать дважды - не было двойных рёбер. Но теперь когда это часть генератора - можно оставить её только для жёлтых рёбер (ну тк как раз серые и соединяют вершины на соседних уровнях) и там синхронизировать

2021-12-07 08:24 UTC, Friend-LGA requested changes

2021-12-07 08:24 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +      generate_gray_branch(graph, graph_mutex, 0, 1);
вот этот вот `0`, притянутый за уши, мне не нравится. Возьми это значение `id` из реальной вершины.

2021-12-07 08:24 UTC, Friend-LGA commented on roman_kuprii/graph_generator.cpp
> +    threads.emplace_back(std::thread(worker));
nit: `emplace` принимает аналогичный конструктору список аргументов, нет нужды вручную создавать `std::thread`

2021-12-07 12:01 UTC, Friend-LGA approved these changes

2021-12-07 12:03 UTC, merged