Add tevfik_aksoy/task_02
Friend-LGA/msu_course_cpp_323 pull request #13
Opened 2021-09-13 16:21 UTC by TevfikOguzhanAksoy

- Init commit, add tevfik_aksoy/task_01
- Init commit, add main.cpp, graph.json
- add README.md

2021-09-22 16:21 UTC, Friend-LGA requested changes
Убери из PR изменения в файлах, не относящихся к данной задаче.

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +		for (int i = 0; i < edges.size(); i++)
В данном случае лучше использовать запись цикла:
```suggestion
              for (const auto& edge : edges) {
```

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +			int edge_val = edges[i].edge_val;
Если не планируешь изменять переменные, всегда лучше писать `const int`

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +			graphVec[src_id].push_back(std::make_tuple(dest_id, edge_val));
А что если `src_id > node_amount`? Ожидаемо, что здесь может произойти ошибка... Я не буду на этом настаивать, но я бы на твоем месте подумал, как можно улучшить данную логику.

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +void writeJson(const Graph &graph, int node_c, const vector<Edge> &edges)
Разве `Graph` уже не знает про `node_c` и `edges`? Они же являются частью графа, это не должно быть внешней информацией. Граф должен знать информацию о себе и уметь себя распечатывать в `json` без дополнительной информации.

Еще, я бы реализовал это как функцию класса `Graph`, что-нибудь типа `std::string to_jsong() const;`

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +#line __LINE__ "graph.json"
Зачем это?

2021-09-22 16:21 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +		ofile << "}" << endl;
Довольно сложная логика... Подумай, не проще было бы, объявить у структур `Node` и `Edge` функции, например `to_json()`, чтобы они сами знали как себя распечатывать. `JSON` это простая структура, вложенная сама в себя.

Тогда вся логика, приблизительно, будет выглядеть как-то так:
```
Node {
    std::string to_json() const {
        // ...
    }
}
Edge {
    std::string to_json() const {
        // ...
    }
}
Graph {
    std::string to_json() const {
        // ...
        for every node {
            node.to_json();
        }
        for every edge {
            edge.to_json();
        }
        // ...
    }
}
```

2021-09-23 10:56 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	int node_id = 0;
Поправка:
Передавать извне можно. Но не из корня программы вручную. Должна быть какая-то инкапсулированная логика по генерации следующего уникального значения для `id`.

2021-09-23 11:05 UTC, TevfikOguzhanAksoy commented on task_02/tevfik_aksoy/main.cpp
> +	int node_id = 0;
Хорошо, я понял, я на 3 задаче так сделал, думал на этой задаче вручно передаем параметры, исправлю.

2021-09-23 17:39 UTC, Friend-LGA requested changes
Убери из PR изменения в файлах, не относящихся к данной задаче.
- Ты файлы удалил, а тебе наоборот, не нужно их изменять, тогда они и из PR исчезнут. В PR показываются только измененные файлы.

Зачем добавил пустой README.md?

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +typedef std::tuple<int, int> DestID_EdgeID;
`typedef` is a `C` style
`using` is a `C++` style
Давай придерживаться `C++` стиля

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +private:
ПОследовательность определения секций видимости такая:
`public -> protected -> private`

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	}
Нет смысла добавлять простой геттер и сеттер для приватного поля. Достаточно просто сделать поле публичным.

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	explicit Node() : id(0) {}
Вместо нескольких конструкторов достаточно сделать один с аргументом с дефолтным значением
```suggestion
      explicit Node(int id = 0) : id(id) {}
```

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	explicit Node() : id(0) {}
`explicit` нужно указывать только для конструкторов с одним аргументом.

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	int id = 0;
`int` было бы хорошо заменить на что-нибудь более выразительное, например:
```cpp
using NodeId = int;
```
В таком случае и читаемость кода будет лучше, и если мы захотим сделать `id` например строкой, достаточно будет изменить только в одном месте. 
```suggestion
      NodeId id = 0;
```

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	std::string to_json(vector<int> edge_ids, bool end_flag) const
Если передаешь большие структуры данных в функцию, то лучше передавать их не по значению, а по `const` ссылке
```suggestion
      std::string to_json(const vector<int>& edge_ids, bool end_flag) const
```

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	const int GetID() const
Что за непостоянство в наименовании функций и переменных. Определись и выбери какой-нибудь один стиль.

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +	void to_json() const
Работа с файлами не входит в зону отвественности графа.
Эта функция скорее должна возвращать строку, которая извне уже может быть записана в файл.
```suggestion
      std::string to_json() const {
```

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +typedef std::tuple<int, int> DestID_EdgeID;
Не стоит комбинировать `snake_case` и `CamelCase` вместе, выбери что-то одно

2021-09-23 17:39 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +		this->id = id;
Чем обращаться к `this` лучше просто переименуй локальную. переменную, например в `_id`
```suggestion
              id = _id;
```

2021-10-05 14:48 UTC, Friend-LGA requested changes
Репозиторий изменил структуру, и теперь код должен находиться не в папке `task_02`, а в папке `02_knight_and_princess`

2021-10-05 14:48 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +  void generateVertices() {
Генерация вершин и граней не входит в зону ответственности графа. Он является самой структурой, а не генератором данной структуры. Логика добавления вершин и граней в граф должна находиться вне графа.

2021-10-05 14:48 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +        continue;
nit: Конкретно в данном случае это не принципиально, но в целом, архитектурно не очень хорошее решение, так как `id` поле может измениться и стать, например, строкой. Поэтому не стоит полагаться на внутреннюю структуру объекта при выполнении внешнего алгоритма.

2021-10-05 14:48 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +    total_nodes_ = nodes_set.size();
Нет смысла в переменной, ты итак всегда можешь взять это значение из `graph_vec_.size()`

2021-10-05 16:04 UTC, TevfikOguzhanAksoy commented on task_02/tevfik_aksoy/main.cpp
> +#include <iostream>
Да

2021-10-06 09:06 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> +using std::cout;
Почему помечено как `Resolved` без изменений и комментария? Замечание все еще актуально.

2021-10-06 09:12 UTC, TevfikOguzhanAksoy commented on task_02/tevfik_aksoy/main.cpp
> +using std::cout;
tuple и vector использую, std::cout удалил

2021-10-06 09:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    Edge e(0, 0, 0);
Уже обсуждали, язык должен быть выразительным, а не криптографическим. Не нужно пытаться излишне сокращать названия. особенно до 1ой буквы.

2021-10-06 09:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +using dest_edge_id = std::tuple<int, int>;
Наверное, это должны быть не `int`, a `NodeId`?
```suggestion
using dest_edge_id = std::tuple<NodeId, NodeId>;
```
Все еще из названия не понимаю, что означает этот тип. "Destination Edge Id"? Зачем он тогда хранит 2 значения, если `id` должен быть одним значением?

Можешь объяснить свою логику?

2021-10-06 09:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                      vector<std::pair<int, int>>& edges_src_dest);
Неиспользуемый метод без тела.

2021-10-06 09:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      edges_src_dest_;  // vector of pairs to keep data of source and
Тоже самое, наверное ты хотел использовать `NodeId` здесь?
```suggestion
  vector<std::pair<NodeId, NodeId>>
      edges_src_dest_;  // vector of pairs to keep data of source and
```

2021-10-06 09:33 UTC, Friend-LGA commented on task_02/tevfik_aksoy/main.cpp
> + private:
Не исправлено, почему помечено `Resolved` без исправления и без комментария?

2021-10-06 09:43 UTC, TevfikOguzhanAksoy commented on task_02/tevfik_aksoy/main.cpp
> + private:
Ааа, здесь проблема, что private в начале перед public? Его перемещу на конец

2021-10-06 10:00 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      edges_src_dest_;  // vector of pairs to keep data of source and
Исправил

2021-10-06 10:46 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Edge edges[] = {{0, 1, 0},    {0, 2, 1},   {0, 3, 2},   {1, 4, 3},
Понял, исправил

2021-10-06 10:47 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  for (auto edge : edges) {
Исправил

2021-10-06 12:35 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +using dest_edge_id = std::tuple<int, int>;
То есть этот тип хранит DestinationID, EdgeID

2021-10-06 13:04 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                      vector<std::pair<int, int>>& edges_src_dest);
Исправил(надеюсь)

2021-10-06 19:25 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    Edge e(0, 0, 0);
Исправил

2021-10-06 19:27 UTC, TevfikOguzhanAksoy commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    for (int i = 0; i < graph_vec_.size(); i++) {
Я знаю, что не resolved, но для запросить ревью кажется нужно отметить resolved

2021-10-07 20:30 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +using dest_id_edge_id = std::tuple<int, int>;
`VertexId`, `EdgeId`?

2021-10-07 20:31 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  explicit Vertex(VertexId _id = 0) : id(_id) {}
Есть ли смысл создавать `Vertex` с `id = 0` по-умолчанию? А если мы создадим 10 таких вершин, получится что в графе есть 10 вершин с одинаковым id? Наверное, лучше будет не указывать дефолтное значение?
```suggestion
  explicit Vertex(VertexId _id) : id(_id) {}
```

2021-10-07 20:32 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  explicit Vertex(VertexId _id = 0) : id(_id) {}
По значению мы должны передавать только фундаментальные типа, но так как в данном случае конкретный тип скрыт от нас за `VertexId`, мы не знаем, фундаментальный это тип или нет, в таком случае лучше пользоваться стандартной практикой передачи по `const` ссылке

2021-10-07 20:34 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  VertexId id = 0;
`0` - это валидный id, а так как у нас id должен создаваться и назначаться в конструкторе, было бы лучше указывать стандартным какое-то невалидное значение, которое лучше вынести в константу:
```cpp
constexpr int INVALID_ID = -1;
```
```suggestion
  VertexId id = INVALID_ID;
```

2021-10-07 20:35 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Edge(int src_id, int dest_id, int _id)
`VertexId`, `EdgeId`?

2021-10-07 20:37 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  array<Vertex, 13> vertex;
Почему граф решил, что он может хранить только 13 граней? Это же абстрактная сущность. Граф может хранить любое количество граней.

2021-10-07 20:38 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Graph() {}
Не нужно указывать пустой конструктор, он итак существует по-умолчанию

2021-10-07 20:40 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  array<Vertex, 13> vertex;
`vertex` - единственное число
`vertices` - множественное число

2021-10-07 20:41 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      json_string += vertex[i].to_JSON(edge_ids);
`i` берется из размера другого вектора, и так же используется для доступа к элементу другого вектора - это потенциальная ошибка. Подумай как можно улучшить эту логику.

2021-10-07 20:43 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string to_JSON(const vector<int>& edge_ids) const {
Нарушение логики, такая распечатка имела бы смысл, если `Vector` сам хранил в себе `edge_ids`, но если нам нужно передавать их снаружи, тогда и весь метод лучше реализовать снаружи структуры `Vertex`

2021-10-07 20:44 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string to_JSON() const {
Вот видишь, тут с логикой все в порядке. `Edge` имеет все данные чтобы распечатать самого себя и данная функция имеет смысл, в отличие от аналогичной в `Vertex`

2021-10-07 20:45 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  const array<Edge, 18> edges = {{{0, 1, 0},
Если ты в `Graph` указал `array` вместо `vector`, чтобы у тебя была возможность использовать `array` здесь, то можешь вернуть как было `vector` и здесь и там.

2021-10-07 20:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    graph.vertex[i].id = i;
Откуда ты знаешь что в `vertex` совпадает количество элементов. Подозрительная логика.

2021-10-07 20:47 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  for (int i = 0; i < nodes_set.size() + 1; i++)
Почему здесь вот эта `+ 1`, классический пример `magic number`, я не могу понять для чего это нужно из простого прочтения кода.

2021-10-08 07:05 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +using dest_id_edge_id = std::tuple<int, int>;
Точно, исправил

2021-10-08 07:08 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  VertexId id = 0;
Понял, так даже красивее. И вопрос, так понимаю что конст значение лучше глобальным объявлять, да? Исправляю

2021-10-08 07:21 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  explicit Vertex(VertexId _id = 0) : id(_id) {}
Здравствуйте, 
![image](https://user-images.githubusercontent.com/24300906/136514520-80560b26-a7f7-485f-8ec5-93d704f28de9.png)
получаю такую ошибку если не создаю с значением по умолчанию, этот конструктор работал еще как дефольтный. Тут мне кажется либо надо создать дефольтный конструктор что и сделает то же самое с этим, либо вернуть array на vector, да?

2021-10-08 08:01 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  for (int i = 0; i < nodes_set.size() + 1; i++)
Да, вы правы, но у нас только` 13 source вершины(0-12)`. Надо включить последний `13` тоже, который не `source`, потому что не рождается новая вершина от неё. Ну в принципе я могу сначала пройтись и читать все `source` вершины, потом все `destination` вершины, и убрать дубликаты. Не сложно, но это же для конкретного графа я понял. Поэтому так сделал, извините

2021-10-08 08:13 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    graph.vertex[i].id = i;
Исправил

2021-10-08 10:31 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string to_JSON(const vector<int>& edge_ids) const {
Логику исправлю легко если создам вектор нитей в структуре Vertex, сделаю

2021-10-08 13:46 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string to_JSON(const vector<int>& edge_ids) const {
Исправил

2021-10-08 13:48 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      json_string += vertex[i].to_JSON(edge_ids);
Думаю, исправил

2021-10-09 15:11 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
1. Ты не можешь позволить себе делать "ничего" в случае непредвиденного поведения. Если уж ты решил обрабатывать ошибку, то нужно делать это до конца, и выводить результат из функции, например:
    ```suggestion
      enum class InsertEdgeStatus { 
          Ok,
          EdgeAlreadyExists, 
          InvalidSourceVertexId, 
          InvalidDestinationVertexId 
      };
    
      InsertEdgeStatus insert_edge(VertexId source, VertexId destination, EdgeId id) {
        if (edge_already_exists(id)) {
          return InsertEdgeStatus::EdgeAlreadyExists;
        }
        if (is_vertex_valid(source)) {
          return InsertEdgeStatus::InvalidSourceVertexId;
        }
        if (is_vertex_valid(destination)) {
          return InsertEdgeStatus::InvalidDestinationVertexId;
        }
        edges.push_back(Edge(source, destination, id));
        vertices[source].edge_ids.push_back(id);
        vertices[destination].edge_ids.push_back(id);
        return InsertEdgeStatus::Ok;
      }
    ```
2. Когда у тебя есть входные проверки, вместо того, чтобы вкладывать их друг в друга:
    ```cpp
    Error function() {
      if (success) {
        if (success) {
          if (success) {
            // ну ты меня понял
          }
        }
      }
    }
    ```
    Лучше делать ранний выход из функции:
    ```cpp
    Error function() {
      if (error) {
        return Error();
      }
      if (error) {
        return Error();
      }
      if (error) {
        return Error();
      }
      // так намного лучше
    }
    ```
3. Конкретно в данном случае, у нас нету передачи данных извне, то бишь от юзера или из интернета. Есть только вероятность локальной ошибки. А раз так, то нам и не нужно обрабатывать эти ошибки, достаточно проверить что их нет, поэтому лучше просто добавить `assert`
    ```suggestion
      void insert_edge(VertexId source, VertexId destination, EdgeId id) {
        assert(edge_already_exists(id), "Edge already exists");
        assert(is_vertex_valid(source), "Source vertex id doesn't exist");
        assert(is_vertex_valid(destination), "Destination vertex id doesn't exist");

        edges.push_back(Edge(source, destination, id));
        vertices[source].edge_ids.push_back(id);
        vertices[destination].edge_ids.push_back(id);
      }
    ```

2021-10-09 15:12 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  vector<Edge> edges;
`Naming Convention`?

2021-10-09 15:13 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  graph.insert_edge(13, 14, 18);
Здорово, что ты это показал, но код не должен содержать в себе лишней `Debug` логики.

2021-10-09 15:26 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  void insert_node(VertexId source) { vertices.push_back(Vertex(source)); }
Хорошо

2021-10-10 07:33 UTC, AxoyTO commented
![image](https://user-images.githubusercontent.com/24300906/136686762-78d2cba2-dcec-4ea2-8650-483c98ae6a50.png)
**Может возникать вопрос, почему оставить std::cerr сообщение в фунцкиях, у меня тоже возникает. Но это хорошо, что благодаря тому сообщению можно видеть где в какой vertex или edge ломается программа.**

2021-10-12 12:06 UTC, Friend-LGA requested changes
Almost there
![](https://media.giphy.com/media/dEPGknRiEniec/giphy.gif)

2021-10-12 12:06 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  vector<EdgeId> edge_ids;
Было бы хорошо спрятать `edge_ids` от чужих глаз в приватную область, и реализовать интерфейс по взаимодействию, например:
```cpp
add_edge_id(const EdgeId& id);
```
И добавить туда валидацию на то, что мы не добавляем одинаковые `id`

2021-10-12 15:23 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  void insert_node(VertexId source) { vertices_.emplace_back(Vertex(source)); }
Понял, вспомнил, исправил 😃

2021-10-12 19:10 UTC, AxoyTO commented
> Almost there ![]

Are we there yet? 😄 
![](https://media0.giphy.com/media/zOvBKUUEERdNm/giphy.gif)

2021-10-13 14:01 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                           const vector<EdgeId>& edges_of_vertex);
nit: Ну это же просто `edge_ids` зачем усложнять название

2021-10-13 14:03 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +           "Destination vertex id doesn't exist");
Еще бы проверить, что вершины не связаны.

2021-10-13 14:06 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +bool edge_exists_in_vertex(const EdgeId& id,
nit: Edge cannot exists in Vertex, грань не может существовать в вершине, грань связывает вершины, наверное ты имел ввиду `edge_id`?) Можешь оставить такое название, это не особо принципиально, но довольно забавно, мне пришлось поломать голову пару секунд, чтобы понять, что эта функция делает))
На будущее - старайся называть функции и переменные более понятно.

2021-10-13 14:08 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +bool is_vertex_valid(const VertexId& id, const vector<Vertex>& vertices) {
nit: Ты не валидность проверяешь, а его вхождение в вектор, было бы лучше `is_vertex_exists`, или что-нибудь наподобие, например сверху ты нормально назвал аналогичную функцию для граней, почему просто не последовал своему же примеру: `vertex_exists_in_graph` - звучит намного ближе к реальности.

2021-10-13 15:13 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +bool edge_exists_in_vertex(const EdgeId& id,
Понял, исправил, спасибо!)

2021-10-13 18:16 UTC, Friend-LGA requested changes

2021-10-13 18:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +using std::get;
Не используется

2021-10-13 18:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Edge(VertexId src_id, VertexId dest_id, EdgeId _id)
`const` ссылка

2021-10-13 18:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  void insert_node(const VertexId& source) { vertices_.emplace_back(source); }
Валидация на то, что такой вершины не существует

2021-10-13 18:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +}
Не эффективный код. А если у тебя 10000 граней? Достаточно взять список граней из первой вершины, и проверить, если они присоединены ко второй. Ну или другими словами, проверить, если ли пересечение в их `edge_id` списках

2021-10-13 19:22 UTC, merged