anton_gadzikovskiy/task_04
Friend-LGA/msu_course_cpp_323 pull request #136
Opened 2021-12-10 16:25 UTC by AGadzuk

2021-12-13 12:43 UTC, Friend-LGA requested changes

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +const double kRedEdgesProbability = 33.0;
Почему `const`, а не `constexpr`?

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  std::unordered_map<Depth, vector<VertexId>> vertices_on_depth_;
Нет смысла использовать `unordered_map`, так как глубина увеличивается с 0 и каждый раз на 1, то можно использовать просто вектор.

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +        vertices_on_depth_.emplace(new_vertex_depth, vector<VertexId>());
А сам `id` на новую глубину положить?
```suggestion
        vertices_on_depth_.emplace(new_vertex_depth, vector<VertexId>({to_vertex_id}));
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +    for (const auto& edge : edges_) {
А если у тебя 100500 граней? Очень неэффективная логика, обходить их все. Возьми грани от первой и от второй вершины, и проверь их

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  return (rand() % 100) <= prob;
Это `C` логика. Используй `std::bernoulli_distribution`
- https://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  srand(time(0));
https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  graph.add_vertex();
Добавление корневой вершины - это внешнаяя логика, относительной этой функции, будет лучше вынести

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +            new_child_vertex_id++;
Воу воу воу, это что вообще такое???))) Добавляешь грань, к какой-то рандомной вершине.
```suggestion
            const auto new_vertex_id = graph.add_vertex();
            graph.add_edge(from_vertex_id, new_vertex_id);
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  for (int i = 0; i < depth; i++) {
Названия не достаточно очевидные:
```suggestion
  for (int current_depth = 0; depth < depth; current_depth++) {
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +    if (i < graph.get_vertices_on_depth().size()) {
Лучше для этого добавить удобный интерфейс
```suggestion
    if (current_depth < graph.depth()) {
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +          graph.get_vertices_on_depth().at(i);
1) Лучше для этого добавить удобный интерфейс
1) Зачем тебе `temp` префикс?
1) Это не `vertices`, а `vertex_ids`
1) Почему не `const`
1) Почему делаешь копию? Добавь комментарий, если это оправдано
```suggestion
      const auto vertex_ids_on_depth = graph.get_vertex_ids_on_depth(current_depth);
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +bool is_generated(double prob) {
Что за `prob`? Пиши полностью

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +    if (depth < graph.get_vertices_on_depth().size() - 2) {
Лучше всегда делать ранний выход:
```suggestion
  for (const auto& [depth, vertices] : graph.get_vertices_on_depth()) {
    if (depth >= graph.get_vertices_on_depth().size() - 2) {
      break;
    }
```

2021-12-13 12:43 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +  cout << depth << std::endl;
Зачем?

2021-12-13 13:22 UTC, AGadzuk commented on anton_gadzikovskiy/graph_generator.cpp
> +          graph.get_vertices_on_depth().at(i);
Исправил название, а копию делал потому что, у меня возникла ошибка, в которой почему-то id новой вершины менялся на какое-то большое число, и создание копии исправило ее.

2021-12-13 16:50 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +          graph.get_vertices_on_depth().at(i);
Это потому, что ты изменял объект, по которому итерировался. Нельзя одновременно итерироваться по коллекции и менять её, тогда обращения к памяти указывают на неверные адреса.
Добавь комментарий прямо в коде

2021-12-13 16:59 UTC, AGadzuk commented on anton_gadzikovskiy/graph_generator.cpp
> +          graph.get_vertices_on_depth().at(i);
Добавил

2021-12-13 18:47 UTC, Friend-LGA requested changes

2021-12-13 18:47 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
>      vertices_on_depth_.at(0).push_back(new_vertex_id);
Для вектора `.at()` использовать особого смысла нет, лучше `[]`

2021-12-13 19:33 UTC, AGadzuk commented on anton_gadzikovskiy/graph_generator.cpp
> +        if (edge_id_1 == edge_id_2) {
Добавил реализацию этого условия через обход граней. Можно допустить такое? У нас же зеленые грани будут редко встречаться.

2021-12-13 19:40 UTC, Friend-LGA requested changes

2021-12-13 19:40 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +      for (const auto& edge : edges_) {
Зеленые грани так же принадлежат вершине, нет смысла обходить их все. Просто условие для их проверки отличается.

2021-12-13 20:01 UTC, AGadzuk commented on anton_gadzikovskiy/graph_generator.cpp
> +      for (const auto& edge : edges_) {
Нужно обойти все грани на глубине данной вершины? Просто у вершины мне доступны только id граней, а ним я не могу получить грань без обхода по граням

2021-12-15 05:11 UTC, Friend-LGA requested changes
Я бы принял, если программа правильно работала. Что-то у тебя за проблема с вероятностями. А раз уж исправляешь вероятности, то оставил ещё пару комментариев по коду.
![Screenshot 2021-12-15 at 08 05 48](https://user-images.githubusercontent.com/5897136/146127074-2f55161e-0ccd-4fd0-8681-9b7da55d8c5d.png)

Такое чувство, что у тебя у всех граней вероятность 100%

2021-12-15 05:11 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +           vertices_.at(from_vertex_id).get_edge_ids()) {
Что мы про `at` говорили?

2021-12-15 05:11 UTC, Friend-LGA commented on anton_gadzikovskiy/graph_generator.cpp
> +        if (edges_[edge_id].from_vertex_id == edges_[edge_id].to_vertex_id) {
Нет прямой связи между `edge_id` и индексом данной грани в массиве. То же самое относится и к вершинам.
Добавь интерфейс для поиска вершины и грани по её `id`, и используй везде его
```cpp
Vertex& get_vertex(const VertexId& id);
Edge& get_edge(const EdgeId& id);
```

2021-12-15 08:35 UTC, AGadzuk commented on anton_gadzikovskiy/graph_generator.cpp
> +           vertices_.at(from_vertex_id).get_edge_ids()) {
а vertices_ это unordered_map, я когда с нему через [] обращаюсь, мне ошибку кидает

2021-12-15 11:37 UTC, Friend-LGA approved these changes
🎉

2021-12-15 11:38 UTC, merged