kirill_tolstobrov/task_06
Friend-LGA/msu_course_cpp_323 pull request #137
Opened 2021-12-10 16:30 UTC by lanzy4

2021-12-13 13:18 UTC, Friend-LGA requested changes

2021-12-13 13:18 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +  const VertexId first_vertex_id = 0;
Не надо гадать, либо получи `id` первого объекта из графа, либо передавай аргументом в функцию

2021-12-13 13:18 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +  auto worker = [&jobs, &jobs_mutex, &should_terminate]() {
`const`

2021-12-13 13:18 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +                                          const int cur_depth,
`cur`?
Зачем передаешь константное значение?

2021-12-13 13:18 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +      lock.~lock_guard();
lock_guard будет автоматически удален, когда закончится скоп, в котором он был объявлен. В этом его преимущество, что не нужно вручную управлять его памятью
```suggestion
      {
        const std::lock_guard lock(mutex);
        const auto new_vertex_id = graph.add_new_vertex();
        graph.bind_vertices(cur_vertex_id, new_vertex_id);
      }
```

2021-12-13 13:18 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +  }
Не очень красиво и надежно, писать специальный кейс, всего для одной уникальной ситуации при рекурсивном выполнении. Тем более что сравниваешь с каким-то магическим числом `0`

Попробуй этого избежать и написать более универсальную логику, которая будет выполняться одинаково, независимо от вершины.

В целом, тут потребуются минимальные изменения. Подумай о такой логике, каждый бранч создает по 1 вершине и порождает `new_vertices_num` новых `generate_gray_branch`

2021-12-13 15:14 UTC, lanzy4 commented on kirill_tolstobrov/graph_generator.cpp
> +      lock.~lock_guard();
Там ведь потом вызов рекурсивный этой же функции с этим же мьютексом. Он ведь тогда, по идее, не разблокируется, и программа зависнет. У меня так и происходит: с этой строчкой работает, без нее прога виснет.

2021-12-13 15:16 UTC, lanzy4 commented on kirill_tolstobrov/graph_generator.cpp
> +      lock.~lock_guard();
Аа, все, понял

2021-12-13 18:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +  // generate_blue_edges(graph);
Тогда полностью удаляй все, связанное с ними

2021-12-13 18:58 UTC, Friend-LGA requested changes

2021-12-13 18:58 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +  if (random_bool(new_vertex_prob)) {
Всегда лучше использовать ранний выход, чем увеличивать вложенность
```suggestion
  if (!random_bool(new_vertex_prob)) {
    return;
  }
```

2021-12-13 18:58 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +    }
Всегда лучше инициализировать переменную в значение + `const`
```suggestion
    const VertexId new_vertex_id = [&mutex, &graph, &vertex_id]() {
      const std::lock_guard lock(mutex);
      const auto new_vertex_id = graph.add_new_vertex();
      graph.bind_vertices(vertex_id, new_vertex_id);
      return new_vertex_id;
      }();
```

2021-12-13 18:58 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.cpp
> +    int new_vertices_num = params_.new_vertices_num;
1) `const`?
1) В переменной нет нужды, испольузется 1 раз

2021-12-13 19:38 UTC, Friend-LGA requested changes

2021-12-13 19:38 UTC, Friend-LGA commented on kirill_tolstobrov/graph_generator.hpp
> +  // void generate_blue_edges(Graph& graph) const;
?
Невнимательность отнимает кучу времени

2021-12-15 05:00 UTC, Friend-LGA approved these changes

2021-12-15 09:45 UTC, merged