task started
Friend-LGA/msu_course_cpp_323 pull request #138
Opened 2021-12-10 21:12 UTC by kapkappa

2021-12-13 16:24 UTC, Friend-LGA requested changes

2021-12-13 16:24 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +      GraphTraversalController(threads_count, graphs_count);
не `graphs_count` а непосредственно список графов, которые нужно обойти - `graphs`

2021-12-13 16:24 UTC, Friend-LGA commented on roman_kuprii/main.cpp
>    return 0;
Разбей `main` на меньшие функции

2021-12-13 16:24 UTC, Friend-LGA commented on roman_kuprii/graph_traversal_controller.hpp
> +  void traverse_graphs(const std::vector<Graph>& graphs,
`graphs` передавай в конструктор

2021-12-13 16:24 UTC, Friend-LGA commented on roman_kuprii/graph_traversal_controller.hpp
> +  int graphs_count_;
`graphs_count_` не нужен

2021-12-13 16:24 UTC, Friend-LGA commented on roman_kuprii/graph_traversal_controller.cpp
> +        auto pathes = graph_traverser.traverse_graph(graphs[i]);
Множественное число от `path` -> `paths`

2021-12-14 13:53 UTC, kapkappa commented on roman_kuprii/main.cpp
>    return 0;
немного не понимаю, какие логические блоки можно выделить в мэйне, чтобы это не было убиранием одной фукнци в другую просто чтобы меньше строчек в мэйне было

2021-12-15 12:57 UTC, Friend-LGA requested changes

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +  generate_graphs(graphs, logger, threads_count, graphs_count, params);
```cpp
graph = generate...
```

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/logging_helping.hpp
> +  for (const auto& vertex_pair : work_graph.get_vertices_map()) {
```suggestion
  for (const auto& [vertex, vertex_id] : work_graph.get_vertices_map()) {
```

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph_printing.cpp
> +std::string vertex_to_json(const std::pair<VertexId, Vertex>& vertex) {
`const Vertex& vertex`

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.hpp
> +  std::vector<std::vector<VertexId>> depth_map_ = {{0}};
Что за дефолтные данные в объекте? Причем рандомные совершенно.
Добавишь их когда появится необходимость

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.hpp
> +  int get_edges_num() const { return edges_map_.size(); }
Не очень гибко, просто возвращай вершины и грани

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.hpp
> +  std::unordered_map<EdgeId, Edge> edges_map_;
просто вершины и грани

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.hpp
>    int depth_ = 0;
Он тебе больше не нужен

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +  for (const auto& vertex_pair : vertices_map_) {
Подумай

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
>      }();
Глубина меняется только серыми гранями, упрости

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +  auto new_edge_id = get_next_edge_id();
const

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph_traversal_controller.cpp
>    for (int iter = 0; iter < threads_count; iter++) {
`min()`

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph_traversal_controller.cpp
> +        auto paths = graph_traverser.traverse_graph();
const

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph_traverser.cpp
>      std::lock_guard lock(graph_mutex);
Зачем?

2021-12-15 12:57 UTC, Friend-LGA commented on roman_kuprii/graph_traverser.cpp
> +  auto vertex_ids = graph_.get_vertex_ids_at_depth(graph_.get_depth());
1) const?
2) Зачем копия?

2021-12-15 16:34 UTC, Friend-LGA requested changes

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +  vertices_.emplace(new_vertex_id, new_vertex_id);
Положи на 0ую глубину

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +      vertices_.find(from_vertex_id)->second.get_edges_ids();
find -> at

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +    int new_depth = vertices_.find(from_vertex_id)->second.depth + 1;
const

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +      depth_map_.push_back(std::vector<VertexId>({0}));
Откуда `0` взял, придумал? Бери реальные данные

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
>        new_edge_id, Edge(from_vertex_id, to_vertex_id, new_edge_id, color)));
```cpp
edges_[key] = value;
```

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph_traverser.cpp
> +         graph.is_vertex_exist(destination_vertex_id));
Нельзя комбинировать несколько ассертов

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/graph_traverser.cpp
> +  const auto vertex_ids = graph_.get_vertex_ids_at_depth(graph_.get_depth());
Зачем копия?

2021-12-15 16:34 UTC, Friend-LGA commented on roman_kuprii/logging_helping.hpp
>    std::vector<int> depth_count;
Зачем оно тебе?

2021-12-16 06:39 UTC, Friend-LGA requested changes

2021-12-16 06:39 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +  if (!depth_map_.size())
nit:
```cpp
depth_map_.empty();
depth_map.size() == 0;
```

2021-12-16 06:39 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +    depth_map_.push_back(std::vector<VertexId>({new_vertex_id}));
nit:
```cpp
depth_map_.push_back({new_vertex_id});
```

2021-12-16 06:39 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
>    if (initialization) {
```cpp
initialization
```

2021-12-16 06:39 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +    depth_map_[0].pop_back();
Почему?

2021-12-16 06:39 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
>    const Edge::Color color = [&initialization, &diff, &from_vertex_id,
вынеси в отдельную функцию
```cpp
calculate_edge_color()
```

2021-12-16 07:16 UTC, Friend-LGA requested changes

2021-12-16 07:16 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +    const int from_vertex_depth,
`const` значение нет необходимости

2021-12-16 07:16 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +  if (to_vertex_depth == 0)
А если зеленая

2021-12-16 07:22 UTC, Friend-LGA approved these changes
🎉

2021-12-16 07:22 UTC, merged