tevfik_aksoy/task_08
Friend-LGA/msu_course_cpp_323 pull request #139
Opened 2021-12-11 12:26 UTC by AxoyTO

[**Задача 8 —Реализовать поиск кратчайшего пути**](https://github.com/AxoyTO/uni_course_cpp/tree/master/practice/task_08)

2021-12-13 16:45 UTC, Friend-LGA requested changes

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.hpp
> +  std::vector<GraphTraversal::Path> get_shortest_paths() const;
```suggestion
  std::vector<Path> get_shortest_paths() const;
```

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.hpp
> +                                         VertexId destination_vertex_id);
Зачем спрятал в приватной области? Вполне валидная публичная функция. Это же и есть публичная ответственность этого класса - искать пути.

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.hpp
> +      const VertexId& vertex_id);
Никаких лишних данных быть не должно

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal_controller.cpp
> +const int MAX_WORKERS_COUNT = std::thread::hardware_concurrency();
Лучше поместить в приватный неймспейс

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +  }
Не нужно ничего искать при создании

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +  save_shortest_paths(distances, destination_vertex_id, dummy_path_vertices);
Не нужно ничего сохранять

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +}
Зачем?

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +  return shortest_paths_;
Тут ты должен создать воркеров, и многопоточно обойти граф.
```cpp
// ...

const auto root_vertex_id = graph_.get_vertex_ids_at(0).front();
const auto& last_vertex_ids = graph_.get_vertex_ids_at(graph_.depth());

for (const auto last_vertex_id : last_vertex_ids) {
  jobs.push_back([]() { /* ... */ });
}

// ...
```

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.hpp
> +  std::vector<Path> shortest_paths_;
Зачем тебе все эти переменные? Эти данные ты можешь брать напрямую из графа, тебе не нужны приватные переменные.

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal_controller.hpp
> +      std::function<void(int, std::vector<GraphTraversal::Path>)>;
Кроме индекса будет не лишним возвращать `const` ссылку на граф

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +               "},\n");
Перенеси к остальной логике по печати 
```cpp
GraphPrinter::print_path(path);
```

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +  prepare_log_file(logger);
Нет смысла разделять логику
```suggestion
  prepare_temp_directory();
  auto& logger = prepare_logger();
```

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +        // log_traversal_end(logger, traversal, index);
Да, здесь обхода быть не должно

2021-12-13 16:45 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +      [&logger, &graphs](int index, std::vector<GraphTraversal::Path> path) {
Будет логичным возвращать и сам граф тоже
```suggestion
      [&logger](int index, const Graph& graph) { log_traversal_start(logger, index); },
      [&logger, &graphs](int index, const Graph& graph, std::vector<GraphTraversal::Path> path) {
```

2021-12-13 20:33 UTC, AxoyTO commented on tevfik_aksoy/graph_traversal.hpp
> +                                         VertexId destination_vertex_id);
Просто использовал её не публично поскольку сразу в консрукторе вызывал но ошибка было конечно, исправляю

2021-12-14 17:49 UTC, AxoyTO commented on tevfik_aksoy/graph_traversal.cpp
> +}
Удалил, поменял логику

2021-12-14 17:50 UTC, AxoyTO commented on tevfik_aksoy/graph_traversal.cpp
> +}
Поменял логику этой функции, теперь более разумно и читаемо

2021-12-14 18:07 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +               "},\n");
Я не понял почему, GraphPrinter же для печати на .json файл

2021-12-14 18:13 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +               "},\n");
А тут логирование

2021-12-15 13:41 UTC, Friend-LGA requested changes

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
>      logger.log("{vertices: [");
В `GraphPrinter` - `print_path`

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
>      return std::nullopt;
`assert()`

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +    if (graph_.get_edges()[edge_id].color == Edge::Color::Green)
Добавь интерфейс для получения граней и вершин из графа
```cpp
graph.get_vertex();
graph.get_edge();
```

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +  auto vertex_edges = vertex.get_edge_ids();
const

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +      }
Дублируешь код
```cpp
const auto connected_vertex_id = ? source : destination;
adjacent_vertices.push_back(connected_vertex_id);
```

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +    const Vertex& vertex) {
Логика графа
```cpp
class Graph {
  std::vector<VertexId>get_adjacent_vertex_ids(const VertexId& vertex_id) const;
};
```

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal_controller.cpp
> +            auto path = graph_traversal.traverse_graph();
const

2021-12-15 13:41 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal_controller.cpp
> +              traversalStartedCallback(i, graphs[i]);
Захвати в лямбду только 1 граф

2021-12-15 14:39 UTC, Friend-LGA requested changes

2021-12-15 14:39 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +    const Vertex& vertex) const {
```cpp
const VertexId& vertex_id
```

2021-12-15 14:39 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +      continue;
Она будет связана сама с собой через зеленую грань, надо тоже вернуть

2021-12-15 14:39 UTC, Friend-LGA commented on tevfik_aksoy/graph_printer.cpp
> +  ss << "], distance: " + std::to_string(path.distance) + "},\n";
Что здесь делает `,\n`?

2021-12-15 14:39 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
> +  assert(graph_.get_vertices().size() > 1 &&
```cpp
assert(graph.has_vertex(source_vertex_id));
assert(graph.has_vertex(destination_vertex_id));
```

2021-12-15 14:39 UTC, Friend-LGA commented on tevfik_aksoy/graph_traversal.cpp
>  std::optional<GraphTraverser::Path> GraphTraverser::find_shortest_path(
Убери `optional`

2021-12-15 15:51 UTC, Friend-LGA requested changes

2021-12-15 15:51 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +  const auto vertex = get_vertex(vertex_id);
Зачем копия?

2021-12-15 15:58 UTC, Friend-LGA approved these changes

2021-12-15 16:13 UTC, merged

2021-12-15 16:15 UTC, AxoyTO commented
<img src="https://media3.giphy.com/media/j0vs5H7Kcz3Pm9LRDa/giphy.gif"/>