tamara_gadieva/task_05
Friend-LGA/msu_course_cpp_323 pull request #142
Opened 2021-12-13 17:32 UTC by theonlymusya

2021-12-13 19:35 UTC, Friend-LGA requested changes

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/config.cpp
> +}  // namespace uni_cource_cpp
no newline
😠

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/main.cpp
> +namespace graph_printing {
`namespace graph_printing`
Должен быть в отдельных файлах
- `graph_printing.hpp`
- `graph_printing.cpp`

И включать в себя он должен следующее:
```cpp
namespace graph_printing {

std::string print_graph(const Graph& graph);
std::string print_vertex(const Graph::Vertex& vertex, const Graph& graph);
std::string print_edge(const Graph::Edge& edge, const Graph& graph);
std::string print_edge_color(const Graph::Edge::Color& color);
std::string print_graph_description(const Graph& graph);

};  // namespace graph_printing
```

`print_graph_description` - соответственно возвращает то, в каком виде граф выводится логгером

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/main.cpp
> +std::string get_current_date_time();
Зачем тебе объявление функций отдельно от их реализации? Все находится в одном файле, пиши сразу их логику.

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/main.cpp
> +    const std::string file_name = "./temp/graph_" + std::to_string(i) + ".json";
про `config::TEMP_FOLDER_PATH` забыла?

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  const int get_edges_number() const { return edges_.size(); }
`const int` - константную копию нет смысла возвращать. Нам не важно что происходит дальше с копией данных

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  }
Обсуждали. что гибким интерфейсом будет - возвращать список граней
```suggestion
  const std::vector<EdgeId>& get_vertex_ids_in_depth(int depth) const {
    return vertices_ids_in_depth_[depth];
  }
```

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +
Опять же, гибким интерфейсом будет вернуть `vertices` и `edges`, а кому нужно - возьмет их размер

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +  std::vector<VertexId> get_vertices_ids_in_depth(int depth);
Почему возвращает не `const` ссылку?

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.hpp
> +std::string color_to_string(const Edge::Color& color);
Должно быть внутри `graph_printing`

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
Зачем тебе `non-const` версия? Она вообще используется где-нибудь?

2021-12-13 19:35 UTC, Friend-LGA commented on tamara_gadieva/graph_generator.cpp
> +const VertexId& get_random_vertex_id(
Тоже в приватный `namespace`, оно же нигде вне данного файла не используется?
Остальные подобные функции тоже в приватный неймспейс

2021-12-13 19:42 UTC, theonlymusya commented on tamara_gadieva/main.cpp
> +std::string get_current_date_time();
Чтобы функцию main можно было написать первой. Так разве не удобнее?

2021-12-13 19:51 UTC, theonlymusya commented on tamara_gadieva/graph.cpp
> +std::vector<VertexId> Graph::get_vertices_ids_in_depth(int depth) {
Это я очень случайно забыла сохранить предыдущие изменения

2021-12-15 06:44 UTC, Friend-LGA approved these changes
![](https://media.giphy.com/media/xNBcChLQt7s9a/giphy.gif)

2021-12-15 08:34 UTC, merged