robert_gaisin/task 06
Friend-LGA/msu_course_cpp_323 pull request #150
Opened 2021-12-16 17:56 UTC by geleg-rigzin

2021-12-20 14:52 UTC, Friend-LGA requested changes

2021-12-20 14:52 UTC, Friend-LGA commented on robert_gaisin/graph_generator.hpp
> -class Graph;
Зря изменил, так было лучше.
Практика такая: в `hpp` файлах используешь `forward declaration`, то бишь как у тебя было `class Graph;`, а в `cpp` файле уже делаешь настоящий `#include`. Таким образом ускоряется компиляция проекта.

2021-12-20 14:52 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
>          std::vector<VertexId> vertices_to_connect = get_unconnected_vertex_ids(
А `get_unconnected_vertex_ids` не нужно синхронизировать?

2021-12-20 14:52 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> +  ;
?)

2021-12-20 14:52 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> +                          const Params& params,
Много аргументов, лучше бы уменьшить. `params_` ты можешь забрать напрямую из объекта, если сделаешь функцию приватной

2021-12-20 21:17 UTC, geleg-rigzin commented on robert_gaisin/graph_generator.cpp
>          std::vector<VertexId> vertices_to_connect = get_unconnected_vertex_ids(
Нет, здесь не нужно, серые ветви уже сгенерированы, а красные соединяют вершины на большей глубине.

2021-12-21 14:41 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
>          std::vector<VertexId> vertices_to_connect = get_unconnected_vertex_ids(
У тебя внутри этой функции вызывается `graph.is_connected`, который проверят вектор `vertex.edge_ids_`. Параллельно у тебя выполняются ещё несколько потоков, которые связывают вершины синими, желтыми и зелеными гранями, соответственно изменяя `vertex.edge_ids_`. А если вектор изменяется, то он может быть переаллоцирован в памяти для расширения, тогда, внутри `get_unconnected_vertex_ids`, когда ты вызовешь `graph.is_connected`, ты можешь обратиться к несуществующей памяти. Согласен?

2021-12-21 14:45 UTC, Friend-LGA requested changes
Продолжаем обсуждение необходимости синхронизации

2021-12-21 16:31 UTC, geleg-rigzin commented on robert_gaisin/graph_generator.cpp
>          std::vector<VertexId> vertices_to_connect = get_unconnected_vertex_ids(
Ок

2021-12-22 13:33 UTC, Friend-LGA requested changes

2021-12-22 13:33 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> -          const std::lock_guard lock(mutex);
Зря убрал

2021-12-22 13:33 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> +        const std::lock_guard lock(mutex);
Слишком много лочишь, `graph.is_connected` должно быть достаточно

2021-12-22 16:15 UTC, Friend-LGA requested changes

2021-12-22 16:15 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> +          mutex.lock();
```suggestion
          const std::lock_guard lock(mutex);
```

2021-12-22 16:15 UTC, Friend-LGA commented on robert_gaisin/graph_generator.cpp
> +        mutex.unlock();
Здесь лок не нужен, а внутри `get_unconnected_vertex_ids` должно быть нечто похожее на
```cpp
const bool is_connected = []() {
  const std::lock_guard lock(mutex);
  return graph.is_connected();
}();
```

2021-12-23 07:43 UTC, Friend-LGA approved these changes

2021-12-23 07:44 UTC, merged