kirill_tolstobrov/task_08
Friend-LGA/msu_course_cpp_323 pull request #152
Opened 2021-12-17 20:51 UTC by lanzy4

2021-12-20 13:49 UTC, Friend-LGA requested changes

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  for (const auto& vertex_id : vertices) {
```suggestion
  for (const auto& vertex_id : graph_.get_vertices()) {
```

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +    current_vertex_id = vertices_info[current_vertex_id].nearest_neighbour;
Это точно `nearest`? У нас дистанция одинаковая между ними всеми? Может это `parent_vertex`, например?

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  return result;
```suggestion
  return GraphPath(path);
```

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  VertexId root_vertex = graph_.depths_map_[0][0];
`root_vertex_id`
`const`?

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  std::mutex mutex;
Назови понятнее, для чего этот мютекс? `paths_mutex`

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.hpp
> +  const int graphs_count_;
Зачем, ты можешь из вектора взять количество

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.cpp
> +  int threads_count = std::min(MAX_WORKERS_COUNT, graphs_count_);
`const`?

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.cpp
> +    const TraversalFinishedCallback& trav_finished_callback) {
Вот эти `trav` только путают, назови уж тогда просто `started_callback` и `finished_callback`

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.cpp
> +        trav_started_callback(i);
Не лишним будет передавать в коллбэк и ссылку на граф, над которым происходит работа в данный момент.

2021-12-20 13:49 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.cpp
> +        trav_finished_callback(i, std::move(paths));
Тут тоже ссылка на граф не помешает

2021-12-20 16:18 UTC, lanzy4 commented on kirill_tolstobrov/graph_printer.hpp
> +  static std::string print_paths(const std::vector<GraphPath>& paths);
То есть вынести из класса и сделать отдельными функциями?

2021-12-21 14:03 UTC, Friend-LGA commented on kirill_tolstobrov/graph_printer.hpp
> +  static std::string print_paths(const std::vector<GraphPath>& paths);
`print_path` - это правильный интерфейс, он тебе нужен, распечатка данной сущности. А вот `print_paths` - очень специфичная функция, ты можешь её использовать, но как вспомогательную функцию в приватном неймспейсе, а не часть интерфейса

2021-12-21 14:32 UTC, Friend-LGA requested changes

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph.cpp
> +    VertexId new_neighbour_id =
Я же тебе в примере написал `const`, ты настолько их недолюбливаешь, что даже копировать не стал?))

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.hpp
> +      std::function<void(int, std::vector<GraphPath>, Graph)>;
Хочешь копию графа делать?

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.hpp
>    const std::vector<Graph> graphs_;
Делать копию графов - неэффективно, траверсер не владеет графами, у него есть просто ссылка на них. Вот и хранить лучше ссылку.

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  std::reverse(path.begin(), path.end());
Данный кусок - просто генерацию пути, можно либо вынести в отдельную функцию, или хотя бы объединить под лямбду, например
```cpp
  const auto path = []() {
    std::vector<VertexId> result;
    current_vertex_id = destination_vertex_id;
    while (current_vertex_id != source_verex_id) {
      result.push_back(current_vertex_id);
      current_vertex_id =
          vertices_info[current_vertex_id].previous_vertex_in_path;
    }
    result.push_back(source_verex_id);
    std::reverse(result.begin(), result.end());
    return result;
  }
```

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.hpp
>  };
На часть приватного интерфейса это тоже не очень похоже. Можешь в приватный неймспейс спрятать?

2021-12-21 14:32 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traversal_controller.cpp
> +        started_callback(i, std::move(graphs_[i]));
Почему решил `std::move` делать? Это ломает структуру твоего класса, вообще-то.
И не понятно, как у тебя дальнейший код работает. должен был сломаться, по-идее.

2021-12-21 18:24 UTC, lanzy4 commented on kirill_tolstobrov/graph_traverser.hpp
>  };
Почему не похоже? Мне тогда придется VertexInfo делать public

2021-12-22 09:05 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.hpp
>  };
`VertexInfo` тоже туда же, в приватный неймспейс

2021-12-22 11:12 UTC, Friend-LGA requested changes

2021-12-22 11:12 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +    std::map<uni_cpp_practice::VertexId, VertexInfo>& vertices_info,
const

2021-12-22 11:12 UTC, Friend-LGA commented on kirill_tolstobrov/graph_traverser.cpp
> +  };
```suggestion
  }();
```

2021-12-22 11:20 UTC, Friend-LGA requested changes

2021-12-22 11:20 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +      [](int index, uni_cpp_practice::Graph graph) {
ссылка

2021-12-22 11:45 UTC, Friend-LGA approved these changes

2021-12-22 11:45 UTC, merged