xieyu_wang/task_05
Friend-LGA/msu_course_cpp_323 pull request #154
Opened 2021-12-19 19:19 UTC by AncientEncoder

2021-12-20 14:11 UTC, Friend-LGA requested changes
Please, put the label

2021-12-20 15:10 UTC, Friend-LGA requested changes

2021-12-20 15:10 UTC, Friend-LGA commented on xieyu_wang/Logger.hpp
> +  Logger() = default;
Again, did you read the task?
You need to add `config.hpp`, and take path to log file from there.
```suggestion
  Logger() : file_(config::LOGGER_FILE_PATH) {
    if (!file_.is_open()) {
      throw std::runtime_error("Failed to open log file");
    }
  }
```
If you do like this, you don't need any `optional` and you don't need `setFile`

2021-12-20 15:10 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +int getMaxDepth(Logger& logger, Graph graph) {
Why logger is here?

2021-12-20 15:10 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  logger.log("}\n}\n");
All this into `graph_printing.hpp/cpp`
```cpp
namespace graph_printing {
std::string print_graph_description(const Graph& graph);
}
```

2021-12-20 15:10 UTC, Friend-LGA commented on xieyu_wang/Edge.hpp
>    std::string toString() const;
Everything related to printing should be moved to `graph_printing.hpp/cpp`
```cpp
namespace graph_printing {
std::string print_graph(const Graph& graph);
std::string print_vertex(const Vertex& vertex);
std::string print_edge(const Edge& edge);
std::string print_edge_color(const Edge::Color& color);
}
```

2021-12-20 15:10 UTC, Friend-LGA commented on xieyu_wang/main.cpp
>  int main() {
function is too long. Split it into smaller functions.
Task description has an [example](https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_05#%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F-main-%D0%B2%D0%B0%D1%88%D0%B5%D0%B9-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B). Did you even read it?

2021-12-20 18:05 UTC, AncientEncoder commented on .gitignore
> +/xieyu_wang/temp/
sry shouldn’t I change here ?

2021-12-23 11:00 UTC, Friend-LGA requested changes

2021-12-24 10:54 UTC, Friend-LGA requested changes

2021-12-24 10:54 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +std::vector<Edge> Graph::getNumEdgeByColor(const Edge::Color& color) {
```cpp
getEdgesByColor
```
return by reference

2021-12-24 10:54 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +  return colorEdges;
add to graph some map of colored edges like
```cpp
std::unordered_map<Color, std::vector<EdgeId>> colored_edges_;
```
```cpp
if (colored_edges_.find(color) == colored_edges_.end()) {
  static std::vector<EdgeId> empty_result = {};
  return empty_result;
}
return colored_edges_.at(color);
```

2021-12-24 10:54 UTC, Friend-LGA commented on xieyu_wang/Graph.hpp
>    bool isConnected(int fromVertexId, int toVertexId);
const method

2021-12-24 10:54 UTC, Friend-LGA commented on xieyu_wang/Graph.hpp
>    bool hasVertex(int idFind);
const method

2021-12-24 10:54 UTC, Friend-LGA commented on xieyu_wang/GraphPrinter.hpp
> +using Vertex = uni_course_cpp::Vertex;
We want to avoid using of `using` inside `hpp` file

2021-12-24 11:44 UTC, Friend-LGA requested changes

2021-12-24 11:44 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +std::vector<Edge>& Graph::getEdgeByColor(const Edge::Color& color) {
```suggestion
const std::vector<int>& Graph::getEdgesByColor(const Edge::Color& color) const {
```

2021-12-24 11:44 UTC, Friend-LGA commented on xieyu_wang/Graph.hpp
> +  std::unordered_map<Edge::Color, std::vector<int>> coloredEdges_;
`EdgeId`

2021-12-24 11:44 UTC, Friend-LGA commented on xieyu_wang/Graph.hpp
> +  const bool isConnected(int fromVertexId, int toVertexId);
don't return const copy. Make the method const

2021-12-24 11:44 UTC, Friend-LGA commented on xieyu_wang/LoggingHelper.cpp
>    for (int i = 0; i < colors.size(); i++) {
```cpp
for (const auto& color : colors) {
```

2021-12-24 12:14 UTC, Friend-LGA requested changes

2021-12-24 12:14 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +      return (Vertex&)vertex;
This type casting should not be here

2021-12-24 12:14 UTC, Friend-LGA commented on xieyu_wang/Graph.hpp
> +  Vertex& getVertex(int id) const;
If you need non-const then don't make it const

2021-12-24 12:25 UTC, Friend-LGA requested changes
Mak

2021-12-24 12:25 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +bool Graph::hasVertex(int idFind) {
const method

2021-12-24 12:25 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +bool Graph::isConnected(int fromVertexId, int toVertexId) {
const method

2021-12-24 12:25 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +Vertex& Graph::getVertex(int id) {
const version of this method if you need so

2021-12-24 12:38 UTC, Friend-LGA approved these changes
🎉

2021-12-24 12:38 UTC, merged