task 4
Friend-LGA/msu_course_cpp_323 pull request #155
Opened 2021-12-20 16:14 UTC by Alexsetyaev

2021-12-21 13:50 UTC, Friend-LGA requested changes
Назови ПР по аналогии с остальными

2021-12-23 11:52 UTC, Friend-LGA requested changes

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/main.cpp
> +const int handle_depth_input() {
нет смысла возвращать константное значение

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
> +  std::vector<EdgeId> connected_edge_ids_;
Вынеси внутрь графа
```cpp
class Graph {
  std::unordered_map<VertexId, std:vector<EdgeId>> adjacency_list_;
  std::unordered_map<VertexId, Depth> vertices_depth_;
};
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
> +  explicit Vertex(VertexId id, int vertex_depth)
Нет смысла передавать глубину при создании

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
> +#include <sstream>
не используются

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/edge.hpp
> +  enum class Color { Red = 0, Gray = 1, Green = 2, Yellow = 4 };
Можешь оставить дефолтные значения

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/edge.hpp
> +       Edge::Color color)
`const` reference

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/edge.cpp
> +  }
```cpp
std::string color_to_string(const Edge::Color& color);
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  explicit Graph(Depth depth) : depth_(depth) {}
Глубина вычисляется из самого графа, нет смысла передавать её в конструктор

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  void add_vertex(int vertex_depth);
Глубина вычисляется динамически внутри графа

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +                Edge::Color color);
Как сказано в задании нужно вычислять цвет динамически

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  VertexId get_last_added_vertex_id() const;
Зачем это в публичном интерфейсе?

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  Depth depth_ = 0;
Лучше хранить карту глубины
```cpp
std::vector<std::vector<VertexId>> depth_map_;
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +                       graph.get_last_added_vertex_id(), Edge::Color::Gray);
```suggestion
        const auto& new_vertex = graph.add_vertex(parent_vertices[i].get_vertex_depth() + 1);
        graph.add_edge(parent_vertices[i].get_id(),
                       new_vertex.id(), Edge::Color::Gray);
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    for (int i = 0; i < parent_vertices.size(); ++i) {
```cpp
for (const auto& vertex : parent_vertices) {
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  std::mt19937 gen(rd());
Код рандомизации дублируется во всех методах, вынеси в одельный метод
```cpp
bool check_probability(Probability probability)
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  for (int i = 0; i < params_.depth(); ++i) {
`i` -> `depth`

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    std::vector<Vertex> parent_vertices;
```cpp
// берем копию чтобы избежать проблем с памятью, так как итерируемя и изменяем один объект
const std::vector<VertexId> vertices = graph.get_vertex_ids_at_depth(depth);
for (const auto& vertex_id : vertex_ids) {
  if (check_probability( ... )) {
      graph.add_vertex();
      graph.add_edge();
  }
}
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    if (first_vertex.get_vertex_depth() < graph.get_depth() && d(gen)) {
Лучше сделать ранний выход
```cpp
if (first_vertex.depth == graph.depth) {
continue;
}
...
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +      std::vector<VertexId> second_vertices_ids;
```cpp
std::vector<VertexId> second_vertiex_ids = graph.get_vertex_ids_at_depth(depth. +1);
const auto unconnected_vertex_ids = get_unconected_vertex_ids(second_vertiex_ids);
```

2021-12-23 11:52 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +            second_vertices_ids[rand() % second_vertices_ids.size()];
`rand()` - это `C`
`std::uniform_int_distribution`
```cpp
const auto vertex_id = get_random_vertex_id(second_vertices_ids);
```

2021-12-26 15:50 UTC, Friend-LGA requested changes

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/edge.cpp
> +  if (color == Edge::Color::Grey) {
Используй `switch - case`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/edge.hpp
>  #pragma once
`#pragma once` должна быть первая в файле

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/edge.hpp
> +std::string color_to_string(const Edge::Color& color);
Не должно быть в публичном интерфейсе, то есть в `hpp` файле

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +bool check_probability(double param) {
`param` -> `probability`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    const std::vector<VertexId> vertices = graph.get_vertex_ids_at_depth(depth);
Добавь комментарий в код, зачем мы берем копию

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +          auto new_vertex = graph.add_vertex();
1) Зачем копию
2) Почему не `const`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    if (check_probability(0.1)) {
`0.1` - `magic number`
Вынеси в глобальную константу
```cpp
constexpr int kGreenProbability = 0.1;
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +const std::vector<VertexId> Graph::get_unconected_vertex_ids(
Нет смысла возвращать `const` копию данных

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +    bool flag = true;
`flag` - плохое название
`is_unconnected`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
>        }
```cpp
is_connected(from_vertex_id, to_vertex_id) const;
```
```cpp
if (!is_connected()) {
  vertices_ids.push_back(another_vertex);
}
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
>    std::vector<EdgeId> connected_edge_ids_;
Вынеси внутрь графа
```cpp
class Graph {
  std::unordered_map<VertexId, std:vector<EdgeId>> adjacency_list_;
  std::unordered_map<VertexId, Depth> vertices_depth_;
};
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
>    std::string to_string() const;
Перенеси в `graph_json_printing.hpp`
```cpp
namespace printing {
namespace json {
std::string print_vertex();
}
}
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
> +using VertexId = int;
using после `include`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +      std::vector<VertexId> second_vertices_ids = graph.get_vertex_ids_at_depth(
1) Зачем копия? Можно ли просто взять ссылку?
2) Почему не `const`?

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +      const std::vector<VertexId>& vertices_at_depth);
Не должно быть частью интерфейса графа, а обычной вспомогательной функцией

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
>              second_vertices_ids[rand() % second_vertices_ids.size()];
`uniform_int_distribution`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +        VertexId second_vertex_id = unconnected_vertex_ids[distrib(gen)];
```cpp
const VertexId second_vertex_id = get_random_vertex_id(unconnected_vertex_ids);
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  }
А как же все остальные вершины?

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  return 0;
```cpp
return vertex_depths_.at(vertex_id);
```

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +        get_edge(connected_edge).get_second_vertex_id() == to_vertex_id) {
А если `from_vertex_id == to_vertex_id`
Проверить зеленые грани

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  std::vector<EdgeId> get_edges(VertexId vertex_id) {
1) Зачем копия? Достаточно будет вернуть конст ссылку
2) Почему метод не константный?

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  bool is_connected(VertexId from_vertex_id, VertexId to_vertex_id);
Почему метод не константный?

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
>      return graph;
Перенеси в `cpp`

2021-12-26 15:50 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +bool check_probability(double param);
Не нужно делать частью интерфейса

2021-12-26 16:37 UTC, Alexsetyaev commented on setyaev_alexander/graph.cpp
> +      std::vector<VertexId> second_vertices_ids = graph.get_vertex_ids_at_depth(
можно

2021-12-26 16:40 UTC, Alexsetyaev commented on setyaev_alexander/graph.hpp
> +      const std::vector<VertexId>& vertices_at_depth);
Но ведь она обращается к приватным данным
Лучше добавлю в прайват

2021-12-26 16:41 UTC, Alexsetyaev commented on setyaev_alexander/graph.hpp
> +      const std::vector<VertexId>& vertices_at_depth);
всмысле, да, анконнектед я перенесу в функцию. имелл ввиду вершины на глубине

2021-12-26 17:54 UTC, Friend-LGA requested changes

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/edge.cpp
> +      break;
Нет смысла в `break` после `return`

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +          const auto new_vertex = graph.add_vertex();
Зачем копия?

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +          // copy for a temporary object
Что за лишние комментарии в коде?

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +constexpr double RedProbability = 0.33;
Naming Convention

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
>    Vertex vertex = vertices_.emplace_back(get_new_vertex_id());
1) Зачем копия
2) Почему не `const`

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  ;
?))

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +      depth_map_[0].pop_back();
Просто удали, зачем ты свапаешь их
`erase` или `remove`, не помню

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  for (const auto& connected_edge : adjacency_list_.at(from_vertex_id)) {
А если `from_vertex_id != to_vertex_id`

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +#include <random>
Используется в этом файле?

2021-12-26 17:54 UTC, Friend-LGA commented on setyaev_alexander/edge.cpp
> +std::string color_to_string(const Edge::Color& color) {
Перенеси в `graph_json_printing`

2021-12-26 18:18 UTC, Friend-LGA requested changes

2021-12-26 18:18 UTC, Friend-LGA commented on setyaev_alexander/graph.hpp
> +  const std::vector<EdgeId>& get_edges(VertexId vertex_id) const {
`get_connected_edge_ids`

2021-12-26 18:18 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  adjacency_list_[vertex.get_id()];
`adjacency_list_[vertex.get_id()] = {};`

2021-12-26 18:18 UTC, Friend-LGA commented on setyaev_alexander/vertex.hpp
> +#include <vector>
Не используются

2021-12-26 18:43 UTC, Friend-LGA approved these changes
🎉

2021-12-26 19:02 UTC, merged