anton_potapov/task_07
Friend-LGA/msu_course_cpp_323 pull request #172
Opened 2021-12-23 10:08 UTC by Flagro

Антон Потапов [Задача 7](https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_07)

2021-12-23 14:05 UTC, Friend-LGA requested changes

2021-12-23 14:05 UTC, Friend-LGA commented on anton_potapov/graph_generation_controller.cpp
> +      gen_finished_callback(i, graph);
Как насчет синхронизации?

2021-12-23 14:05 UTC, Friend-LGA commented on anton_potapov/graph_generation_controller.cpp
> +      gen_finished_callback(i, graph);
move?

2021-12-23 14:14 UTC, Flagro commented on anton_potapov/graph_generation_controller.cpp
> +      gen_finished_callback(i, graph);
e9d026b7b302d049610a3a2d2e05184fd21d0475

2021-12-23 14:14 UTC, Flagro commented on anton_potapov/graph_generation_controller.cpp
> +      gen_finished_callback(i, graph);
e9d026b7b302d049610a3a2d2e05184fd21d0475

2021-12-23 14:14 UTC, Flagro commented on anton_potapov/main.cpp
> +      [&logger, &graphs, &params](int index, Graph& graph) {
e9d026b7b302d049610a3a2d2e05184fd21d0475

2021-12-23 14:16 UTC, Flagro commented on anton_potapov/logger.cpp
> +  std::lock_guard logger_usage_lock(logger_use_mutex_);
d004833f2d3f80767dfb01750b1509efa0c986b9

2021-12-24 11:57 UTC, Friend-LGA requested changes

2021-12-24 11:57 UTC, Friend-LGA commented on anton_potapov/main.cpp
> +        graphs.emplace(index, graph);
Так что, почему бы `std::move` тоже здесь не использовать? Зачем копировать граф?

2021-12-24 12:31 UTC, Flagro commented on anton_potapov/main.cpp
> +        graphs.emplace(index, graph);
5978d1b43b0dde9f72554e20a67b58e0410e184c

2021-12-24 12:51 UTC, Friend-LGA requested changes

2021-12-24 12:51 UTC, Friend-LGA commented on anton_potapov/main.cpp
> +        graphs.emplace(index, std::move(graph));
Все ли тут ок?

2021-12-24 12:52 UTC, Friend-LGA approved these changes

2021-12-24 12:52 UTC, Flagro commented on anton_potapov/main.cpp
> +        graphs.emplace(index, std::move(graph));
теперь да

2021-12-24 12:54 UTC, merged