xieyu_wang/task_06
Friend-LGA/msu_course_cpp_323 pull request #182
Opened 2021-12-24 19:48 UTC by AncientEncoder

task-06

2021-12-25 13:24 UTC, Friend-LGA requested changes

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
Explain why do you use atomic here?

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
Why do we need this here, explain

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
Read about lambda function

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +void generateGreen(Graph& graph, std::mutex& mutex) {
Why do you have argument and don't use it?

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +void generateGreen(Graph& graph, std::mutex& mutex) {
All these functions are working concurrently. Do you think we need any kind of synchronisation here?

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
Why do we need `join()` here?

2021-12-25 13:24 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +void GraphGenerator::generateVertices(Graph& graph,
Explain all the steps in this function

2021-12-25 15:58 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +void generateGreen(Graph& graph, std::mutex& mutex) {
here I forgot to lock it on  `const std::lock_guard lock(mutex);`

2021-12-25 15:58 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
to unlock funcation

2021-12-25 15:59 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
prevent unsynchronized read and write on jobs_count by threads

2021-12-25 17:12 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
jobs is an array of callbacks, emplace_back is basically adding callbacks to it

2021-12-25 17:30 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
and here is we capthre the value  generateGrey in lambda

2021-12-26 14:02 UTC, Friend-LGA requested changes

2021-12-26 14:02 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
1) What values do we capture here?
2) Why do we need to capture `this`?

2021-12-26 14:02 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
And why do we want this? Give example from this code below, and explain.

2021-12-26 14:02 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +      const std::lock_guard lock(mutex);
Why exactly do you synchronise it here?

2021-12-26 14:02 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
>              getUnconnectedVertexIds(fromVertexId, destinationLevel, graph);
Do we need to synchronise this function as well?

2021-12-26 14:02 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  int maxDepth = graph.getDepth();
const

2021-12-26 14:15 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
because if this value was non-atomic then it will be thread-unsafe we are using parralin to change the value
if one is changing and anothe are changing it will be unsafe

2021-12-26 14:18 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
We used mutex to lock them in code

2021-12-26 14:20 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
without this the function can't be captured,only as a callback,this is just easier
value cap=>&graph, &firstVertexId, &lockGraph, &jobsDone

2021-12-26 14:23 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +const int MAX_THREADS_COUNT = std::thread::hardware_concurrency();
because it's not a runtime constant and if it gives constexpr it will be error=>must be initialized by a constant expression

2021-12-26 14:25 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +        return std::nullopt;
here workers are just picking jobs one by one until there is none left

2021-12-26 14:30 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +        const std::lock_guard lock(jobsLock);
to safely check if there are jobs left,and safely giive new round jobs

2021-12-26 14:33 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +      }
It means if there is a job then do it

2021-12-26 14:44 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +    const std::lock_guard lock(lockGraph);
Vertex Addition becouse whenever u add something u need to synchronize it

2021-12-26 14:52 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
>              getUnconnectedVertexIds(fromVertexId, destinationLevel, graph);
no we didnt change the graph don new vertex and edges are write into it we just get

2021-12-26 14:53 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +      const std::lock_guard lock(mutex);
wait till gray is done

2021-12-26 15:09 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
till gray is finished to gen

2021-12-26 15:09 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
' jobsDone++;'

2021-12-26 16:38 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +        const std::lock_guard lock(jobsLock);
Again, explain exactly why do we need to synchronise this part of code. How error can occur if we don't have this lock here? What exactly will go wrong. What threads will access what data, and why is it not safe?

2021-12-26 16:39 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    const std::lock_guard lock(lockGraph);
This is not an answer

2021-12-26 16:40 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
It is not related to mutex.
Again, what `join()` is doing?

2021-12-26 16:47 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    jobs.emplace_back([this, &graph, firstVertexId, &lockGraph, &jobsDone]() {
`generateGrey(graph, firstVertexId, 0, lockGraph);`
`this->generateGrey(graph, firstVertexId, 0, lockGraph);`

2021-12-26 16:51 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
- https://en.cppreference.com/w/cpp/atomic/atomic

2021-12-26 16:52 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +      const std::lock_guard lock(mutex);
This is not an answer, what data exactly need to be synchronised?

2021-12-26 17:14 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
>              getUnconnectedVertexIds(fromVertexId, destinationLevel, graph);
Ok, after discussion we decided to move the mutex before this line

2021-12-26 17:36 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  greenThread.join();
it means it will waiting the thread fhinished it task and then return

2021-12-26 17:39 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
it will sync threads and order them to access

2021-12-26 17:41 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +  std::atomic<int> jobsDone = 0;
this is whatr i undersatand

2021-12-26 18:09 UTC, Friend-LGA requested changes
```cpp
Enter Max Depth:16
Enter new vertices num:16
Enter new Graph num:1
26/12/2021 21:08:54: Graph 0, Generation Started
26/12/2021 21:08:54: Graph 0, Generation Finished {  
  depth: 2,
  vertices: 273, [1, 16, 256],
  edges: 313, {gray: 272, green: 19, blue: 5, yellow: 16, red: 1}
}
```

2021-12-26 18:26 UTC, Friend-LGA requested changes

2021-12-26 18:26 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +        (double)parentDepth * percent) {
```cpp
isLucky(getProbabilityGray(parentDepth, maxDepth_))
```

2021-12-26 18:26 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  const double percent = 100.0 / (double)maxDepth_;
You don't need this one

2021-12-26 18:26 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    auto new_vertex_id = graph.addVertex();
const

2021-12-26 18:31 UTC, Friend-LGA approved these changes
🎉

2021-12-26 18:31 UTC, merged