Kirill tolstobrov/task 02
Friend-LGA/msu_course_cpp_323 pull request #29
Opened 2021-09-17 11:21 UTC by lanzy4

2021-09-22 18:35 UTC, Friend-LGA requested changes
Слушай, в целом-то вроде и неплохо выглядит и должно работать... Но, ты нарушаешь принцип [single-responcibility](https://en.wikipedia.org/wiki/Single-responsibility_principle).

Смотри:
У тебя есть:
- `Vertex`
- `Edge`
- `Graph`

Давай подумаем, что они собой представляют:

`Vertex`: это структура, которая хранит в себе значение, в нашем случае `id` и может иметь несколько присоединенных граней.
`Edge`: это структура, которая так же хранит в себе `id` и соединяет 2 вершины.
`Graph`: это структура, которая хранит в себе вершины и грани, знает их количество и связи, и может ими манипулировать.

Так вот, `Vertex` вообще не должен знать о существовании такой структуры как `Edge`, и наоборот, `Edge` не должна знать о существовании такой структуры как `Vertex`. Все что они знают - это простые данные. А вот `Graph` уже может эти данные осознать и получить из них целостную картинку.

Подумай о том, как упростить твою логику. В первую очередь как упростить `Vertex` и `Edge` структуры, особенно, как избежать `raw pointers`.

---

И еще, убери из PR изменения в файлах, не относящихся к данной задаче.

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +    Graph(std::string mode = "empty", int max_vertices = 10, int max_edges = 15) {
Во-первых, зачем тебе вообще `mode` для этой задачи? Выглядит как что-то не относящееся к данному пулл реквесту.

Во-вторых, никогда не используй голые `std::string` как аргументы для последующего выбора чего-то. Такое поведение невозможно будет валидировать компилятором, только `runtime error`.
Именно для таких ситуаций придумали `enum class`
```
enum class Mode { Empty, Random };
```

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +        };
Это ты так константу пытался объявить?

Константы объявляются обычно в приватном `namespace` и давай договоримся называть их как обычные переменные, но с префиксом `k`, например 
```cpp
namespace {
  consexpr int kProbabilityCoef = 100;
} // namespace
``` 

Конкретно для данной задачи тебе вообще не нужны вероятности. Тебе нужно построить конкретный граф.

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +    void AddNewVertex(){
Давай называть функции с маленькой буквы, что за непостоянство?)

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +    Graph(int vert_number, std::vector<std::pair<int, int>> connections) {
2 совершенно разных конструктора меня пугают...

Мне кажется, ты переборщил с зоной ответственности конструктора.
Попробуй упростить, и вынести не необходимую логику во внешний `API`. К примеру, почему бы просто не конструировать просто пустой граф изначально? Он будет вполне валидным графом.
А дальнейшие манипуляции уже можно производить с помощью его интерфейса, к примеру
```
void add_vertex();
void add_edge(from, to);
```
Тогда, вместо того, чтобы писать 100500 конструкторов на все случаи жизни, у тебя будет гибкий интерфейс, для того чтобы создавать графы любой сложности.

А вся вот эта вот логика, тебе не кажется, что относится к какой-то другой сущности? Например к генератору графа. Если тебе нужно иметь фабрику, которая будет создавать множество типизированных графов, тогда проще написать генератор, который будет использовать интерфейс графа, чтобы создавать готовые графы с заданными параметрами.

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +    int get_vertices_amount() { return vertices_amount; }
Функции, которые не мутируют объект, должны помечаться как `const`
```suggestion
    int get_vertices_amount() const { return vertices_amount; }
```

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +        for(int i = 0; i < connections.size(); i++) {
В таких случаях используют следующий синтаксис:
```suggestion
        for (const auto& connection : connections) {
```

2021-09-22 18:35 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +            double new_vertex_prob = PROBABILITY_COEF - (double)PROBABILITY_COEF * vertices_amount / max_vertices;
Во-первых, куда тебе `double`, почему не `float`?

Во-вторых, если не планируешь изменять переменную, объявляй её как `const`

2021-09-23 10:55 UTC, Friend-LGA commented on task_02/kirill_tolstobrov/main.cpp
> +    Vertex(int x = 0): id(x) {}
Поправка:
Передавать извне можно. Но не из корня программы вручную. Должна быть какая-то инкапсулированная логика по генерации следующего уникального значения для `id`.

2021-10-05 15:26 UTC, Friend-LGA commented on .clang-format
> +BasedOnStyle: Chromium
nit: По-хорошему не относится к задаче, и должно бы быть в отдельном ПР. Можешь оставить.

2021-10-05 15:30 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  int id;
Я смотрю, что поле `id` не изменяется, в таком случае, вместо того, чтобы прятать его в `private` и добавлять геттер, проще указать его как `const`
```suggestion
  const int id;
```

2021-10-05 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  int get_edges_amount() const { return edges_amount; }
Зачем для этого отдельные переменные, у тебя же уже есть:
```suggestion
  int get_vertices_amount() const { return vertices.size(); }
  int get_edges_amount() const { return edges.size(); }
```

2021-10-05 15:36 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    connections_map[id2][edges_amount - 1] = id1;
Много цифр написано вручную, высока вероятность ошибиться
```suggestion
    const auto& edge = edges.emplace_back(edges_amount, id1, id2);
    edges_amount++;
    connections_map[id1][edge.id] = id2;
    connections_map[id2][edge.id] = id1;
```

2021-10-05 15:43 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  }
Эту логику можно упростить. Подумай о том, зачем графу знать, как превращать в строку `Vertex` или `Edge`, почему бы эту логику не вынести внутрь сами  структур `Vertex` и `Edge`?

Идея такая:
```
Vertex {
 to_string() {
    return "{ id: 0 }";
  }
}
```

Тогда вся логика значительно упростится для понимания.

2021-10-05 15:44 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  enum { PROBABILITY_COEF = 100 };
Уже писал ранее

2021-10-05 15:45 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  Graph g;
Никогда без нужды не стоит оставлять неинициализированные переменные
```suggestion
auto g = Graph();
```

2021-10-05 15:47 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  std::vector<std::pair<int, int>> g_connections{
Если знаешь размер вектора, тогда лучше использовать `array`

2021-10-05 15:51 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +}
Метод не используется

2021-10-05 15:51 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +#include <iostream>
Используется в программе?

2021-10-07 20:44 UTC, lanzy4 commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  const VertexId id;
Разве не удобнее хранить все данные класса в одном месте, чтобы сразу видеть всю суть сущности?

2021-10-07 20:47 UTC, lanzy4 commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  void add_edge(int edge_id) { connected_edges.push_back(edge_id); }
Вершине же все равно, какие к ней присоединять грани (по принципу single-responcibility.). Отсутствие одинаковых граней гарантирует генератор графа.

2021-10-07 20:52 UTC, lanzy4 commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +      std::string vertex_string = (std::string)vertices[i];
Ну она же работает в плюсах, есть какие-то недостатки?

2021-10-09 16:45 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +      std::string vertex_string = (std::string)vertices[i];
Ну, если действительно интересно, можешь почитать, [например тут](https://stackoverflow.com/questions/1609163/what-is-the-difference-between-static-cast-and-c-style-casting).

`std::string(some_var)` на самом деле не конвертация, а конструктор из `int`, который по идее должен работать. А использовать `static_cast` вообще лучше как можно реже. Если начинать все конвертировать друг в друга, то можно добиться совершенно нечитаемого и сложно поддерживаемого кода.

2021-10-09 16:48 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    auto& edge = edges.emplace_back(edges.size(), id1, id2);
Задание конечно, гарантирует это, а вот написанный код - нет, пока нет проверки)
Ты же пишешь интерфейс взаимодействия с графом, это абстрактная сущность. `bind_vertices ` - это публичная функция, которая может принимать в себя любые значения, а раз они любые, значит есть вероятность что они могут быть ошибочными, и чтобы отловить это - нужно добавить валидацию. Иначе зачем вообще писать интерфейс? Достаточно будет написать задачу в императивном стиле, с набором инструкций.

2021-10-09 16:55 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  const VertexId id;
Одно не исключает другое.
Конкретно здесь проблема в логике. Еслиты хочешь, чтобы немутабельная перменная была приватной, тогда у неё не должно быть геттера. Если же ты хочешь добавить геттер, тогда вместо того, чтобы писать больше кода и реализоваывать логику по вовразу значения приватной переменной, проще просто изменить её зону видимости. что позволит избежать лишнего кода и потенциальных ошибок.

2021-10-09 17:01 UTC, Friend-LGA requested changes
Нажимай на `Resolve Conversation` тех комментариев, которые исправил.

2021-10-11 13:00 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    result += "\n    }";
nit: Вместо `\n` лучше использовать кроссплатформенный символ новой строки - `std::endl;`

2021-10-11 13:04 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  void add_new_vertex() { vertices_.push_back(Vertex(vertices_.size())); }
nit: Для конструировании нового объекта в коллекцию, есть специальный метод - `emplace`. Поэтому вместо создании объекта и его копирования, достаточно было бы написать так:
```suggestion
  void add_new_vertex() { vertices_.emplace_back(vertices_.size()); }
```

2021-10-11 13:06 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    for (const auto& connection : vertex1_connections) {
Нет смысла создавать отдельбную переменную для единственного использования, лучше уменьбшить зону её видимости:
```suggestion
    for (const auto& connection : connections_map_[id1]) {
```

2021-10-11 13:10 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    }
Так как у нас нет входных данных от юзера, или же из сети, то единственная причина писать валидацию - проверить что в коде нету багов, а не обработать ожидаемую ошибку. В таких случаях нужно использовать `assert()`, так как они удаляются из `production` кода и не несут в себе последующего оверхеда для конечного юзера.
```suggestion
    assert(!is_vertices_connected(id1, id2) && "Attempting to connect already connected vertices: Error.");
```

2021-10-11 13:16 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    connections_map_[id2][edge.id] = id1;
А если `connections_map_[id1]` или `connections_map_[id2]` не существуют? Выше не помешала бы ещё валидация на то, что мы пытаемя связать существующие вершины

2021-10-11 13:17 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  std::map<VertexId, std::map<EdgeId, VertexId>> connections_map_;
Зачем `map` для хранения 2ух значений? Достаточно будет `pair`
```suggestion
  std::map<VertexId, std::pair<EdgeId, VertexId>> connections_map_;
```
Вообще, достаточно было бы отношения вершин к граням, зачем тебе хранить ещё одну вершину, когда её можно быстро достать из `Edge`
```suggestion
  std::map<VertexId, EdgeId> connections_map_;
```

2021-10-11 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  Graph graph = generateCustomGraph(14, g_connections);
`const`?

2021-10-13 16:00 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +           "Attemptig to connect nonexistent vertex: Error.");
Порядок валидации неверный. Сначала нужно проверить, что они существуют, а потом, что они не связаны.

Второе, почему у тебя проверка на существование проводится сравнением с размером коллекции? `id` и рарзмер коллекции вещи не связанные. То что ты генерируешь новые `id` таким образом, я уж не стал придироваться, но логика так себе... Например, если в будущем ты решишь удалять объекты из коллекций, тогда твои  нагенерированные `id` начнут ломаться. Ну да ладно, мы не планируем ничего удалять. Но не нужно писать валидацию, основываясь на каких-то предположениях, нужно произвести конкретный поиск в коллекции, есть ли там элемент с данным `id` или нет, иначе твою валидацию тоже нужно валидировать.

2021-10-13 16:01 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +           "Attemptig to connect nonexistent vertex: Error.");
И не стоит объединять 2 валидации в одну. Как ты поймешь из ассерта, где у тебя ошибка, если у тебя проверяется сразу несколько условий?

2021-10-13 16:13 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  std::map<VertexId, std::map<EdgeId, VertexId>> connections_map_;
Да, вот так, кстати норм:
```cpp
std::map<VertexId, std::vector<Edge *>> connections_map_
```
Сложно в том плане, что тебе придется один раз написать функцию, которая будет возвращать соединенную вершину. Один раз сделал и забыл, не беда. А вот дублирование данных выглядит не так безобидно, тебе придется постоянно помнить об этом и вероятность ошибки повысится. Одно дело, когда с помощью использования  большей памяти ты пытаешься улучшить эффективность программы, но конкретно в этом случае это вряд ли улучшает производительность...
Ну да ладно, не принципиальный момент, можешь оставить как есть.

2021-10-18 13:27 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +        return 1;
`bool` принимает значения `true` или `false`, зачем нужна эта конвертация?

2021-10-18 13:31 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  void add_new_vertex() { vertices_.emplace_back(vertices_.size()); }
Использовать размер массива для определения нового `id` не безопасно, в будущем может появиться логика по удалению вершин, в таком случае появятся новые вершины с одинаковыми `id`
Лучше использовать переменную, специально созданную для генерации новых `id`, например `VertexId vertex_id_counter` и логику по возврату нового `id` вынести в отдельную функцию типа `get_new_vertex_id()`

2021-10-19 22:33 UTC, Friend-LGA requested changes

2021-10-19 22:33 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  Graph() : vertex_id_counter(0), edge_id_counter(0) {}
Лучше просто укажи им дефолтные значения, при объявлении, тогда конструктор можно вообще убрать.
```cpp
VertexId vertex_id_counter_ = 0;
EdgeId edge_id_counter_ = 0;
```

2021-10-19 22:33 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +    connections_map_[id2].push_back(&edge);
Воу воу воу, договаривались не использовать сырые `С` поинтеры без крайней нужды.

2021-10-19 22:33 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  std::map<VertexId, std::vector<const Edge*>> connections_map_;
Договаривались не использовать сырые `С` поинтеры без крайней нужды.
```suggestion
  std::map<VertexId, std::vector<EdgeId>> connections_map_;
```

2021-10-19 22:33 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  VertexId vertex_id_counter;
Читай `Naming Convention`

2021-11-03 07:58 UTC, Friend-LGA requested changes

2021-11-03 07:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  bool are_vertices_connected(const VertexId& id1, const VertexId& id2) {
Ну так а документация для чего существует? Учись искать причину проблемы самостоятельно:
- https://en.cppreference.com/w/cpp/container/map/operator_at
- https://en.cppreference.com/w/cpp/container/map/at

2021-11-03 09:58 UTC, Friend-LGA requested changes
Финишная прямая

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  int get_edges_amount() const { return edges_.size(); }
Не используются

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  const std::vector<std::pair<VertexId, VertexId>> g_connections{
Если ты знаешь размер вектора, то лучше использовать `std::array`

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  const Graph graph = generateCustomGraph(14, g_connections);
`14` - `magic number`, вынеси в глобальную константу

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  void add_edge(const EdgeId& edge_id) {
Предупреждал, что теперь буду ругать за неподходящие названия:
```cpp
add_edge_id
```

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +  std::vector<EdgeId> connected_edges_;
```cpp
edge_ids_
```

2021-11-03 09:58 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +Graph generateCustomGraph(
Непостоянство наименования функций, определись `snake_case` или `CamelCase`

2021-11-03 13:26 UTC, Friend-LGA requested changes
Где бинарник?
Содержание ПР читал?
https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_03

Добавь бинарный скомпилированный файл и принимаю.

2021-11-03 14:41 UTC, Friend-LGA requested changes

2021-11-03 14:41 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +#include <vector>
У меня локально не компилируется. Пишет что у тебя используется `array`, но нет `#include`, видимо у тебя `clang` версия старая, раз скомпилировалось без ошибки. Добавь инклуд.

2021-11-03 15:49 UTC, Friend-LGA commented on 02_knight_and_princess/kirill_tolstobrov/main.cpp
> +#include <vector>
Хм, проверил через WSL, на линуксе реально не ругается, хотя кланг одинаковых версий. Это странно... Инклуд здесь должен быть.

2021-11-06 12:51 UTC, Friend-LGA approved these changes
![](https://media.giphy.com/media/lMameLIF8voLu8HxWV/giphy.gif)

2021-11-17 17:19 UTC, merged