copy task01
Friend-LGA/msu_course_cpp_323 pull request #4
Opened 2021-09-09 06:48 UTC by 2Lapsha1

2021-09-15 08:02 UTC, 2Lapsha1 commented
Здравствуйте. Вроде исправил

> 14 сент. 2021 г., в 23:11, Grigorii Lutkov ***@***.***> написал(а):
> 
> 
> @Friend-LGA requested changes on this pull request.
> 
> Не нужно удалять корневой README.md
> Добавь скриншот
> In task_01/shamil_latypov/README.md <https://github.com/Friend-LGA/msu_course_cpp_323/pull/4#discussion_r708596122>:
> 
> > @@ -0,0 +1 @@
> +Шамиль Латыпов
> Где скриншот?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Friend-LGA/msu_course_cpp_323/pull/4#pullrequestreview-754378754>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVOLZTGK7VTXYM333HNJBHDUB6T6TANCNFSM5DWM6CWQ>.
>

2021-09-15 12:43 UTC, Friend-LGA commented
Если исправил - нажми запросить ревью

2021-09-15 20:50 UTC, 2Lapsha1 commented
Не могу найти, что именно мне надо тыкнуть

> 15 сент. 2021 г., в 15:43, Grigorii Lutkov ***@***.***> написал(а):
> 
> 
> Если исправил - нажми запросить ревью
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/Friend-LGA/msu_course_cpp_323/pull/4#issuecomment-919984854>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVOLZTAHE6JLD2VKWIDNW5TUCCIHZANCNFSM5DWM6CWQ>.
>

2021-09-15 22:06 UTC, Friend-LGA commented
[Docs: Requesting a Pull Request Review](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)

2021-09-17 22:29 UTC, Friend-LGA requested changes

2021-09-17 22:29 UTC, Friend-LGA commented on task_01/shamil_latypov/README.md
> +Шамиль Латыпов
Все еще нет скриншота. Возможно у тебя не подтягиваются новые коммиты в пул реквест... Если это так, то, наверное, нужно пересоздать форк.

2021-09-19 16:34 UTC, closed without merging