xieyu_wang/task_02
Friend-LGA/msu_course_cpp_323 pull request #47
Opened 2021-09-23 15:04 UTC by AncientEncoder

Предыдущий Pull Request - #25

2021-09-23 17:06 UTC, Friend-LGA commented
Просил же добавить ссылку на прошлый `Pull Request`.
Добавил.

2021-09-23 17:08 UTC, Friend-LGA requested changes
Ничего из замечаний к прошлому PR не исправлено

2021-09-25 19:48 UTC, jqp4 commented
попробуй это

clang-format -i -style='{BasedOnStyle: Chromium, IndentWidth: 4}' *.cpp

2021-10-05 16:28 UTC, Friend-LGA requested changes
Почти ничего из замечаний к прошлому PR не исправлено

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +// constexpr will be generator a error so cant use maybe completer's problem
`constexpr` должно работать, проверь свой компилятор
```suggestion
constexpr int maxDots = 14;
constexpr int maxVecPerDot = 4;
constexpr int maxEdges = 18;
```

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +// constexpr will be generator a error so cant use maybe completer's problem
Читай [Naming Convention](https://github.com/Friend-LGA/uni_course_cpp/tree/master/tasks#naming-convention)

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +} liner;
[Правила](https://github.com/Friend-LGA/uni_course_cpp/tree/master/tasks#%D0%BE%D0%B1%D1%89%D0%B0%D1%8F-%D0%B8%D0%B4%D0%B5%D1%8F)
Запрещено использовать голый `C style`, нужно переписать на `C++`

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/Graphic.json
> +}
Отсутствует пустая строка, видишь Git ругается

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +}
Отсутствует пустая строка, видишь Git ругается

2021-10-05 16:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  }
Очень сложная императивная логика. Перепиши на `C++` вместо `C` и постарайся упростить.

2021-10-06 09:02 UTC, Friend-LGA requested changes
Вы читали все комментарии к этому и предыдущему пулл реквесту? Почему вы продолжаете запрашивать ревью почти ничего не исправляя? 90% моих замечаний к первому пулл реквесту так и висят без изменений. Если есть вопросы - спрашивайте, я готов помогать, только нет смысла запрашивать ревью ничего не исправляя.

2021-10-07 21:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +constexpr int pInt[18][3] = {
Опять, `C-style` array. Такие использовать запрещено. Нужно использовать `std::array` и `std::vector`

2021-10-07 21:15 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +constexpr int pInt[18][3] = {
Если уж ты называешь константы  большими буквами, то придерживайся этого

2021-10-07 21:16 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +class vectors {
Читай `Naming Convention`

2021-10-07 21:17 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  int vector;
Что ты называешь `vector`? Ты подразумеваешь `edge_id`? Лучше не использовать названия как типы данных, это может сильно запутывать

2021-10-07 21:18 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +struct MapOfVector {
Может просто `Edge`?

2021-10-07 21:19 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::array<MapOfVector, MAX_VEC> netWork;
Читай `Naming Convention`

2021-10-07 21:20 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  bool SetUp() {
Зачем ты возвращаешь `bool`, который может принимать только значение `true`, в этом нету смысла

2021-10-07 21:22 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    }
Нет необходимости генерировать его из уже известных данные. Ты с тем же успехом можешь вручную заполнить и этот вектор.

2021-10-07 21:22 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +class vectors {
Почему сущность называется в множественном числе? Это сбивает с толку.

2021-10-07 21:24 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    graph.open("Graphic.json", std::ios::out);
Взаимодействие с файлами не должно входить в зону отвественности класса `vectors`, эта логика должна быть реализована вне данного класса. Сам же класс может возвращать готовую строку. Например:
```cpp
std::string to_string() const;
```

2021-10-07 21:28 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  }
Сложная императивная логика. Подумай, как можно сделать её проще для понимания. Как насчет такой структуры?
```cpp
struct Vertex {
  std::string to_string() const;
};
struct Edge {
  std::string to_string() const;
};
struct Graph {
  std::vector<Vertex> vertices;
  std::vector<Edge> edges;
  std::string to_string() const {
    for (vertex : vertices) {
      vertex.to_string();
    }
    for (edge : edges) {
      edge.to_string();
    }
  }
};
```

2021-10-09 15:29 UTC, Friend-LGA requested changes

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +static constexpr std::array<Edge, MAX_VEC> netWork = {{{0, 0, 1},
It doesn't make sense to write `static`, global constant will be static anyway

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +static constexpr std::array<Edge, MAX_VEC> netWork = {{{0, 0, 1},
All constants is better to keep together at the top of the file, for organisation and readability purpose.

I mean, move `struct Edge` below all constants.

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +bool WriteToFile() {
Read `Naming Convention`, it is written there how to name classes, structures, variables and functions

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +bool WriteToFile() {
Separate the logic of preparing `std::string` and working with file into different functions. It is always better to keep function as small as possible, and to encapsulate as little logic as possible into them.

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +bool WriteToFile() {
`bool` is not a good way of handling errors. You need to try to be more expressive with your language. Just simple `bool` doesn't give us much information. You can do it in different ways, for example you use `Enum Class`
```suggestion
enum class WriteToFileStatus { Ok, FileIsNotOpened };

WriteToFileStatus writeToFile() {
```

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    for (auto it : netWork) {
As you are not modifying `it` object, then it make sense to mark it as `const`

2021-10-09 15:29 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +#include <cstdlib>
What do you use this library for?

2021-10-12 12:37 UTC, Friend-LGA requested changes
Repository's folder hierarchy changed long time ago, you need to move your files into different folder. Read `Workflow` section.

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +#include <cstdlib>
I repeat my question

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +};
Why are you combining everything into one struct? You shouldn't try to generalise. Here, it is actually opposite, it makes sense to define different structures for different entities, as they are not similar, they are different.
You should have both. If you have been writing JAVA, it is actually how you will do it there:
```suggestion
class Vertex {
 public:
  const int id = 0;
  
  Vertex(int _id) : id(_id) {}
  
  void add_edge_id(int id) {
    // validation that id has not been added already
    edge_ids_.push_back(id);
  }
  
 private:
  std::vector<int> edge_ids_;
};

class Edge {
 public:
  const int id = 0;
  const int from_vertex_id = 0;
  const int from_edge_id = 0;
  
  Edge(int _id, int _from_vertex_id, int _to_vertex_id) : id(_id), from_vertex_id(_from_vertex_id), to_vertex_id(_to_vertex_id) {}
};
```

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +class VecToString {
Class is entity, entity should not be named as an action. It should be named like any other entity, for example: tree, sun, sky, car, etc...
And functions should be named as actions like: go, run, jump.

So you are breaking naming logic here.

It is actually should be `Graph` itself.

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::string getVectors() { return vectors; }
Probably, you meant `vertices`, not `vectors`, right?

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::string vectors;
Read `Naming Convention`

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +class WriteTOFile {
Again, name like action is wrong for class, it should be something like `FileWriter`

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::ofstream graph;
It looks like you just randomly named everything. Stream is not a Graph, and Graph is not a Stream, it is completely different things. Why did you name your variable like that?

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    } catch (std::string e) {
If you want to catch exception, you need to enable them for stream. But on the other hand, don't complicate, just get rid of this exception handling here.

In general it is a good practice to handle exceptions and it is good that you did it here. But we have many other issues to deal with first. And if they are disabled by default, let's just keep it disabled.

2021-10-12 12:37 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  constexpr std::array<Data, MAX_ELEMENT> netWork = {{{0, 0, 1},
The difference between `constexp` and `const` is what 
- `constexpr` let's compiler to precalculate the value and replace variable with this value. 
- `const` tells compiler that this variable should not be changed while runtime

So in most cases it makes sense to use `const` in local scope and use `constexpr` to define global variables.
In your case just `const` will be enough
```suggestion
  const std::array<Data, MAX_ELEMENT> netWork = {{{0, 0, 1},
```

2021-10-15 18:13 UTC, Friend-LGA requested changes
Ok, it looks much much better now. Just a few more improvements.

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  void add_edge_id(int eId) { edge_ids.push_back(eId); }
You are using 2 different variable naming styles here: `snake_case` and `camelCase`, choose one and stick to it

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    std::string strVec = "";
It is not a `vector`, it is a `string`, why are you naming it like a `vector`?

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::vector<int> edge_ids;
Read `Naming Convention`

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  Edge(const int _id, const int _fromVertexId, const int _to_vertex_id)
Maaan! How can you be so careless, don't you see that everything is written in different style? Read your code before submitting it for review, please. We are waisting too much time on just code style.

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  void addVertx(int from, int edge, int to) {
Vertex is just a vertex, it doesn't need to have any `from` and `to` arguments, you are complicating the logic. Just add a vertex to graph, and that's it. Make it as simple as possible.

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  std::vector<Edge> edge;
These are collections, so the names should be `plural`

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +    for (auto vertexId : vertex) {
`const`

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +  bool idIsInVertex(int _id) {
When you ask question, `to be` verb should be the first word like `isIdInVertex`, when you are saying `idIsInVertex` it is the statement. So, logically wrong naming here.

2021-10-15 18:13 UTC, Friend-LGA commented on task_02/xieyu_wang/graphic.cpp
> +                                                         {12, 17, 13}}};
Doesn't really have to be global constant as you are using it only inside one function once. Better to just make it const variable inside that function.

2021-10-18 19:02 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  }
This function is only needed for validation logic, here are 2 ways it can be done:
1. As some outside function, as validation is not really a part of `Graph` class.
2. Or as public interface, if it makes sense to have such interface. In this case it is actually can make sense to have such public method, if someone will want to check if graph has vertex with specific id.

So as I suggested above, you can move it into public interface. I will also rename it to `has_vertex` as it is a little bit clearer.

2021-10-18 19:04 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  std::vector<Vertex> vertexs;
Singular is `vertex`
Plural is `vertices`

Man, I can't teach you English here as well. Just please, use google and translator, and check yourself. I believe you can do this on your own.

2021-10-18 19:05 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +}
Again "No new line at end of file"
I believe we fixed it already multiple times.
VSCode should have setting to add newline by default if you didn't disable this behaviour.

2021-10-20 14:32 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    for (const auto eId : edgeIds) {
It is better to use reference instead of making a copy
```suggestion
    for (const auto& eId : edgeIds) {
```

2021-10-20 21:08 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    for (const auto eId : edges) {
1. This is not `id`
2. `const` reference
3. What if you will have like 1000000 edges? It will be very inefficient logic. Just compare each vertex' `edge_ids`, if they have any intersection.

2021-10-20 21:12 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  void addVertx() { vertices.emplace_back(getNextVertexId()); }
`Vertex` is misspelled

2021-10-20 21:12 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    int vec = getVertex();
I asked for you to explain. I want to understand your naming logic here.

2021-10-20 21:13 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  }
I asked for you to explain. I want to understand your naming logic here.

2021-10-20 21:16 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  bool isConnected(int fromVertexId, int toVertexId) {
You need to validate if these vertices exists. Otherwise it doesn't make sense to check if inexistent vertices connected or not.

2021-10-20 21:16 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  std::vector<Edge> edges;
?

2021-10-20 21:20 UTC, Friend-LGA requested changes
1. A few more fixes
2. When I asked question, I expect to get an answer. If you see questions in my comments, please, be kind to answer.
3. If you fixed code, which I commented - press `Resolve Conversation`, which means, that this comment is addressed and fixed. Otherwise put comment to describe, why you didn't change the code, which may be valid case some times.

2021-10-21 05:51 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  // toSting
Its just forgot to deleted

2021-10-21 05:54 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    int vec = getVertex();
yes its should be vertex I just mistake here ver is what i wanted

2021-10-21 05:56 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  }
hummmm ,its that I just thought get getNextEdgeId so long to write so I choose getEdge

2021-10-21 06:15 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  bool isConnected(int fromVertexId, int toVertexId) {
It checked by:
 assert(hasVertex(fromVertexId) && "Vertex doesn't exist");
    assert(hasVertex(toVertexId) && "Vertex doesn't exist");

2021-10-21 06:23 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    for (const auto eId : edges) {
ok done as 
 bool isConnected(int fromVertexId, int toVertexId) {
    for (const auto edge : edges) {
      if (edge.fromVertexId == fromVertexId && edge.toVertexId == toVertexId) {
        return true;
      }
    }
    return false;
  }

2021-11-03 08:56 UTC, Friend-LGA requested changes

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    Vertex* vertexFind = NULL;
`Raw Pointer` - `C-Style`, you don't need it here. Don't use pointers unless it is necessary. And here it is not necessary.

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  const Vertex& getVertex(const int id) {
1. `const int` - don't pass fundamental types as `const` values.
2. `const` function

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
>    std::string toString() {
`const` function

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  const int verticesCount = 14;
nit: You can leave it like this. But it is usually better to use global constants for magic numbers.

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    }
It looks like you have a function for this

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  const Vertex& getVertex(const int id) {
Also it looks like you need private non const version of this function.
```cpp
 const Vertex& getVertex(int id) const {
   return getVertex(id);
 }

private:

 Vertex& getVertex(int id) const {
   // logic
 }
```

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    std::vector<int> intersections;
unused

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    }
Why do you need these variable for only one-line use?
```suggestion
    for (const auto& fromVertexEdgeId : getVertex(fromVertexId).getEdgeIds()) {
      for (const auto& toVertexEdgeId : getVertex(toVertexId).getEdgeIds()) {
        if (fromVertexEdgeId == toVertexEdgeId) {
          return true;
        }
      }
    }
```

2021-11-03 08:56 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    return vertexIdCounter_ - 1;
This logic is weird, probably, you can just write:
```suggestion
    return vertexIdCounter_++;
```
Which suppose to first return the value, and then increase the counter. Validate this code if it works.

2021-11-03 11:26 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +  const int verticesCount = 14;
ok, for now I`ll keep it in func main

2021-11-06 12:45 UTC, Friend-LGA requested changes

2021-11-06 12:45 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +      }
Why do you need to use cast here?
```suggestion
    for (auto& vertex : vertices_) {
      if (vertex.id == id) {
        return vertex;
      }
```

2021-11-06 12:45 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    return const_cast<Vertex&>(vertices_.at(-1));
Uuuuuu, this is really bad thing you are trying to do here... You are trying to get element from vector with index of `-1` and then cast it to `Vertex`. It looks like you are looking for some troubles later with this code.

1. Try not to use cast in general
2. Don't take elements with out of bounds index
3. If function should return a value, then it is should return a value or should fail
4. If return is optional, then use `std::optional`

Here, you can just fail the function.
Use `assert` to validate input argument, then you will be sure to always find the value.

2021-11-07 04:28 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +      }
![Screenshot 2021-11-07 122617](https://user-images.githubusercontent.com/30003216/140632291-5a6ce8f2-6b21-4631-a425-395300065275.png)
There will be a error if i dont use (Vertex&) even if i removed const

2021-11-07 04:31 UTC, AncientEncoder commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    return const_cast<Vertex&>(vertices_.at(-1));
Ok I think here the return is not optional I deleted it and use a exit to kill the program will it didnt found , and  as for
return const_cast<Vertex&>(vertices_.at(-1)); its becouse github will report a error while it check my code

2021-11-08 15:19 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +    exit(-1);
It is better to throw exceptions with description, something like this:
```suggestion
  throw std::runtime_error("Unreachable code");
```

This is actually a good showcase why `std::vector` is not the best structure to use here. `std::unordered_map` will be a much better to avoid search for an element.

2021-11-08 15:19 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +      }
And what the error?

2021-11-08 15:20 UTC, Friend-LGA commented on 02_knight_and_princess/xieyu_wang/main.cpp
> +      }
And don't press `Resolved` if it is not reloved

2021-11-10 22:59 UTC, Friend-LGA requested changes
Also, as you can see in the [task description](https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_03#%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%B8%D0%B5-pull-request), you have to include binary file as well. Please, be more careful while reading task description.

2021-11-15 11:52 UTC, Friend-LGA approved these changes

2021-11-15 13:11 UTC, merged