anton_potapov/task_02
Friend-LGA/msu_course_cpp_323 pull request #49
Opened 2021-09-23 22:39 UTC by Flagro

Изначально неправильно понял задачу и реализовал генерацию случайного связного графа с заданным количеством вершин. Функцию случайной генерации оставил в коде на всякий случай

2021-09-24 16:13 UTC, Friend-LGA requested changes

2021-09-24 16:13 UTC, Friend-LGA commented on task_02/anton_potapov/graph_create.cpp
> +                    std::vector<int> &color, int cur_color, int cur_v) {
Если ты передаешь объект в функцию по ссылке, то это `in out` аргумент, который ожидается быть измененным. Если же ты просто передаешь данные, то их нужно всегда передавать по `const` ссылке
```suggestion
void dfs_get_colors(const std::vector<std::vector<int>> &adjacency_list,
                    std::vector<int> &color, int cur_color, int cur_v) {
```

2021-09-24 16:13 UTC, Friend-LGA commented on task_02/anton_potapov/graph_create.cpp
> +    if (s == "task_02") {
Никогда не передавай список опций через простую строку. Для этого существует `enum class`.
При написании строки очень легко опечататься, и компилятор не сможет найти ошибку.

2021-09-24 16:13 UTC, Friend-LGA commented on task_02/anton_potapov/graph_create.cpp
> +  Graph(const std::string &s) {
Конструкторы твои меня беспокоят, почитай [common mistakes](https://github.com/Friend-LGA/uni_course_cpp/tree/master/tasks#15-%D0%BD%D0%B0%D1%80%D1%83%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%BE%D0%BD%D1%8B-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8-single-responcibility)

2021-09-24 16:13 UTC, Friend-LGA commented on task_02/anton_potapov/graph_create.cpp
> +    std::fstream json_file;
Работа с файлами не входит в зону отвественности графа.
Эта функция, скорее, должна возвращать строку, которая извне уже может быть записана в файл.
```suggestion
    std::string to_json() const {
```

2021-10-06 18:58 UTC, Flagro commented on task_02/anton_potapov/README.md
> +Получаемый json файл: <br />
убрал граф из README и json файл из .gitignore

2021-10-06 19:05 UTC, Flagro commented on task_02/anton_potapov/graph_create.cpp
> +  int id;
добавил alias'ы VertexId и EdgeId

2021-10-06 19:06 UTC, Flagro commented on task_02/anton_potapov/graph_create.cpp
> +  int v1_id, v2_id;
сделал названия полей структур более понятными

2021-10-06 19:07 UTC, Flagro commented on task_02/anton_potapov/graph_create.cpp
> +  for (auto el : adjacency_list[cur_v]) {
поправил

2021-10-06 20:03 UTC, Flagro commented on task_02/anton_potapov/graph_create.cpp
> +    if (s == "task_02") {
сделал для данной задачи специальную функцию task_02_get_graph()

2021-10-06 20:03 UTC, Flagro commented on task_02/anton_potapov/graph_create.cpp
> +  Graph(const std::string &s) {
сделал осмысленный конструктор

2021-10-07 17:05 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/properties.hpp
> +struct Boss {
Здорово, что ты уже начал делать дальнейшие задачи, но мы пока еще не дошли до этого этапа, и в. данном пулл реквесте, должны быть изменения, только реализующий задачу `task_02`

2021-10-07 17:26 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Vertex(int vertex_id, Camp c_info = Camp())
`int` -> `VertexId`

2021-10-07 17:29 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Edge(EdgeId e_id, VertexId ver1, VertexId ver2, Boss b_info = Boss())
Я говорил фундаментальные типы, как `int`, `float`, и т.д. нужно передавать в функции по значению. Но так как мы объявили свой тип, который может быть изменен, и мы не уверены, `int` он или нет, то лучше передавать его как `const ref`
```suggestion
  Edge(const EdgeId& e_id, const VertexId& ver1, const VertexId& ver2, const Boss& b_info = Boss())
```

2021-10-07 17:35 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
Усложняешь себе жизнь вот этим конструктором. Ну раз уж хочешь... В таком случае, нужно бы проверить на валидность входных данных. Все ли вершины связаны гранями? Я бы на твоем месте, в данном случае упростил бы, и передавал просто список граней, из которых уже заполнил `adjacency_list_`. Зачем тебе вообще передавать сюда вершины?
```suggestion
  Graph(const std::vector<Edge>& edges)
```

2021-10-07 17:37 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +        json_stringstream << "\n";
`std::endl` - кроссплатформенная версия новой строки
```suggestion
        json_stringstream << std::endl;
```

2021-10-07 17:40 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  size_t n = 14;
`const`?

2021-10-07 17:40 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::vector<Vertex> v_ans;
Что за криптографические названия, чтобы посложнее понять было?)

2021-10-07 17:41 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  size_t n = 14;
Лучше вообще вынести в глобальную константу

2021-10-07 17:41 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +Graph task_02_get_graph(void) {
зачем `void`?

2021-10-07 17:42 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::vector<Edge> e_ans{Edge(0, 0, 1),    Edge(1, 0, 2),    Edge(2, 0, 3),
`const`?

2021-10-07 17:42 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph g = task_02_get_graph();
`const`?

2021-10-07 17:42 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph g = task_02_get_graph();
Что опять за криптография?

2021-10-07 17:43 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  json_file.close();
`return 0` не повредил бы

2021-10-07 18:12 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Vertex(int vertex_id, Camp c_info = Camp())
поправил

2021-10-07 18:21 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::vector<Edge> e_ans{Edge(0, 0, 1),    Edge(1, 0, 2),    Edge(2, 0, 3),
сделал const std::vector<Edge>

2021-10-07 18:23 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph g = task_02_get_graph();
g is now task_02_graph
const поставил

2021-10-07 18:23 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  json_file.close();
поставил return 0

2021-10-07 18:33 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  size_t n = 14;
const добавил. Во что весь проект с графом в итоге выльется еще не очень видно, поэтому не очень понял зачем ее глобальной делать

2021-10-07 18:37 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::vector<Vertex> v_ans;
расшифровал криптографию)

2021-10-07 19:03 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
Вот этот момент не очень понял. В таком случае мы не сможем сконструировать граф с изолированнными вершинами, что в итоге нам даст неочевидное ограничение на хранимый граф и это придется где-то специфицировать. На связность пришлось бы проверять в любом случае. 
К тому же у меня в векторе `edges`, как в векторе структур `Edge`, не хранятся сами вершины как структуры `Vertex`, а только как их id. То есть если бы мы хотели построить граф со сложной информацией в вершинах, нам бы это удалось только после того, как мы сконструировали этот граф по ребрам.
Добавил проверку на соответствие вектора ребер вектору вершин

2021-10-09 16:12 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  VertexId id;
Поле `id` может меняться? Почему бы его не сделать `const`?

2021-10-09 16:22 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +             "Graph constructor: given graph is invalid");
Вся логика валидации должна находиться внутри `assert`. Обычно в продакшене `assert` отключаются, и соответственно должна отключаться вся связанная с ними логика.
Как вариант, можешь создать статический метод, инкапсулирующий эту логику и вызывать его изнутри `assert`

Еще лучше, я бы не перемешивал логику `assert` с нормальной логикой, и вначале тела конструктора проверил все данные на валидность, а уже потом вызывал ожидаемую логику по заполнению графа. То есть всегда, когда нужно проверить входные данные на валидность, сначала производишь проверку, а уже потом реализовываешь остальную логику.

2021-10-09 16:23 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +             "Graph constructor: given graph is invalid");
Еще момент: не стоит совмещать в одном `assert` несколько проверок, иначе, когда произойдет ошибка, не получится точно сказать её причину.

2021-10-09 16:26 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
Вообще, по хорошему, `id` - это внутренняя структура графа, которая не должна иметь выход наружу. `id` должен генерироваться внутри графа, а интерфейс графа должен давать пользователю найти ту вершину, которая ему нужна.
Чтобы лучше понять, о чем я говорю, можешь посмотреть на ПР Новикова - #50

2021-10-09 16:29 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
Для упрощения логики можно определить аналогичные методы внутри `Edge` и `Vert`, тогда их можно будет вызывать рекурсивно, и логика получится проще.
```cpp
struct Edge {
  std::string to_json() const;
};
struct Vert {
  std::string to_json() const;
};
```
В этом заключается большое удобство `JSON` - это вложенная сама в себя структура, и ты можешь добавлять любые объекты, покуда они знают как себя печатать.

2021-10-09 16:30 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string json_string = task_02_graph.get_json_string();
`const`?

2021-10-10 18:38 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string json_string = task_02_graph.get_json_string();
поправил

2021-10-10 19:55 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
То есть чтобы пользователь не смог все сломать, передав графу две вершины с одинаковым `id`? Makes sense, наверное нужно сделать тоже самое и для `EdgeId`

2021-10-10 20:12 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
Аа, можно при добавлении вершины возвращать ее `VertexId`. Now it's all makes sense again

2021-10-10 20:16 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  VertexId id;
поправил

2021-10-10 20:18 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +             "Graph constructor: given graph is invalid");
пожалуй сделаю исключения)

2021-10-10 20:20 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  Graph(const std::vector<Vertex>& vertices, const std::vector<Edge>& edges)
Хотя лучше не `VertexId`, а какую-нибудь структуру типо `VertexProperties`, по которой потом можно будет найти эту вершину

2021-10-10 21:40 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
переписал

2021-10-12 22:28 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.json
> +{"vertices":[{"id":0,"edge_ids":[0,1,2]},{"id":1,"edge_ids":[0,3,4,5]},{"id":2,"edge_ids":[1,6,7]},{"id":3,"edge_ids":[2,8]},{"id":4,"edge_ids":[3,9]},{"id":5,"edge_ids":[4,10]},{"id":6,"edge_ids":[5
починил

2021-10-12 22:58 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
третий `assert` сразу дает ограничение на хранимый граф, у нас не будет кратных ребер, у меня есть ощущение, что поддерживать отсутствие кратных ребер лучше извне

2021-10-12 23:18 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  void add_edge(const EdgeId& edge_id) { adjacted_edges_.insert(edge_id); }
поправил

2021-10-13 17:14 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    update_next_vertex_id_();
nit: Эту логику можно было ещё улучшить и энкапсулировать всю логику связанную с `id` внутри функции `update_next_vertex_id_()`
```suggestion
    const VertexId new_vertex_id = get_next_vertex_id();
```
Но это мелочи

2021-10-13 17:16 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  if (!json_file) {
Не уверен что С++ может адекватно привести `std::fstream` к `bool`. Лучше проверить что файл открыт:
```suggestion
  if (!json_file.is_open()) {
```

2021-10-13 20:20 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  bool is_edge_adjacted(const EdgeId& edge_id) const {
имелось в виду adjacent)

2021-10-13 20:23 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  bool is_edge_adjacted(const EdgeId& edge_id) const {
поправил

2021-10-13 20:25 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  bool is_edge_adjacted(const EdgeId& edge_id) const {
a319a77ebdf8334eed612ce6d86fa033b89c79e0

2021-10-13 20:51 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    return false;
поправил a6172c369fb274e6b745d454aa88628fb40874b0

2021-10-15 18:24 UTC, Friend-LGA requested changes
Ааа, исправляя недочеты, добавил новый :)) Теперь остался, всего один, уже финишная прямая!

2021-10-15 18:24 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::set<EdgeId> connected_edges;
Зачем переместил в публичную зону видимости, теперь любой может поломать внутреннюю структуру вершины, не хорошо. Это же не константа, если тебе нужно получить доступ к данным извне, нужно добавить геттер:
```cpp
const std::set<EdgeId>& connected_edges() const;
```

2021-10-15 20:01 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::set<EdgeId> connected_edges;
пофиксил 8ff22a337d950cadbead3ecbc8feb957199e2517

2021-10-18 16:40 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  VertexId get_next_vertex_id_() {
nit: функции обычно не называют с `_` на конце, это, в основном, используется только для переменных.

2021-10-18 16:42 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    VertexId new_vertex_id = next_vertex_id_;
`const`

2021-10-18 16:42 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    VertexId vertex2 = added_vertices[edge.second];
`const`

2021-10-18 16:44 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    added_vertices.push_back(new_vertex);
```suggestion
    added_vertices.push_back(task_02_graph.add_vertex());
```

2021-10-18 16:44 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    EdgeId new_edge_id = next_edge_id_;
`const`

2021-10-18 16:46 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    for (const auto& vertex1_edge : it_vertex1->second.connected_edges()) {
`const` или
```suggestion
    for (const auto& vertex1_edge : vertices_.find(vertex1)->second.connected_edges()) {
```

2021-10-18 16:47 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +      if (it_vertex2->second.has_edge_id(vertex1_edge)) {
`const` или 
```suggestion
      if (vertices_.find(vertex2)->second.has_edge_id(vertex1_edge)) {
```

2021-10-18 16:50 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    auto it_vertex1 = vertices_.find(vertex1);
Вот видишь, уже начались проблемы из-за неправильного наименования.
Что за `it_vertex1`? Что значит `it`? Ты это написал, просто потому, что у тебя имя `vertex` уже занято. А по-хорошему оно не должно быть занято, просто ты все напутал с наименованием:
```suggestion
  bool is_connected(const VertexId& vertex1_id, const VertexId& vertex2_id) const {
    assert(is_vertex_exists(vertex1_id) && "Vertex 1 doesn't exist");
    assert(is_vertex_exists(vertex2_id) && "Vertex 2 doesn't exist");
    auto vertex1 = vertex_ids_.find(vertex1_id);
```
Видишь, насколько проще была бы читаемость кода, всего-то из-за более правильного наименования переменных.

2021-10-18 16:57 UTC, Flagro commented
Все последние комментарии сейчас поправлю и запушу в бранч с четвертой задачей

2021-10-18 17:02 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  VertexId get_next_vertex_id_() {
поправил в пр с четвертой задачей 5ae232960574aa20b9a5a3b275402e8450aed483

2021-10-18 17:07 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    EdgeId new_edge_id = next_edge_id_;
поправил 3e4e2819e145de411c13e047e0e350d904533e21

2021-10-18 17:10 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    added_vertices.push_back(new_vertex);
поправил 11c5eb4b24ef64bf0ace77defdcb00d1e0f2a175

2021-10-18 17:19 UTC, merged

2021-10-18 17:25 UTC, Flagro commented
PR замерджил 
![3x](https://user-images.githubusercontent.com/47938145/137778704-e231bddc-cb05-4295-9219-d68824908c02.gif)