Alexander setyaev/task 02
Friend-LGA/msu_course_cpp_323 pull request #57
Opened 2021-10-07 06:41 UTC by Alexsetyaev

2021-11-18 07:05 UTC, Friend-LGA requested changes

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  id = i;
`Member initializer list`

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  return this->id;
Зачем `this`?

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  int first_vertex = 0;
`first_vertex_id`

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  vertices.emplace_back(i);
```suggestion
  vertices.emplace_back(get_new_vertex_id());
```

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +    if (vertices[j].get_id() == first) {
`get_vertex`

2021-11-18 07:05 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  for (int i = 0; i < 14; ++i) {
14 - magic number
вынеси в константу
constexpr VERTICES_COUNT

2021-11-24 20:17 UTC, Friend-LGA requested changes
Структура проекта изменилась. Обновись на свежий мастер и замени новыми файлами файлы в свой папке, в корне репозитория.

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +
Не исправлено

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  std::vector<int> connected_edges;
Не исправлено

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  int _id = 0;
Читай `Naming Convention`

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  Vertex(int id);
Если в конструкторе только 1 аргумент, нужно указывать его как `explicit`

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +}
Читай `Common Mistakes` - member initialiser list

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  int get_new_edge_id() const;
Детали имплементации не должны быть частью публичного интерфейса

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  _edges.emplace_back(get_new_edge_id(), first, second);
Лучше вынести в отдельный интерфейс
```cpp
Vertex& get_vertex(const VertexId& id);
```
```suggestion
  const auto& new_edge = edges_.emplace_back(get_new_edge_id(), first_vertex_id, second_vertex_id);

  auto& first_vertex = get_vertex(first_vertex_id);
  first_vertex.add_edge_id(new_edge.id);

  auto& second_vertex = get_vertex(second_vertex_id);
  second_vertex.add_edge_id(new_edge.id);
```

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  return _vertices.size();
`id` не имеет прямой связи с индексом. Нужно завести специальный счетчик
```cpp
VertexId vertex_id_counter_ = 0;
```
```suggestion
  return vertex_id_counter_++;
```

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +void Graph::add_edge(int first, int second) {
Обсуждали уже названия аргументов

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  Graph g;
Обсуждали уже однобуквенные называния

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  const int VERTICES_COUNT = 14;
Вынеси в глобальную константу.
И используй `constexpr`

2021-11-24 20:17 UTC, Friend-LGA commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  for (int i = 0; i < _vertices.size(); ++i) {
```suggestion
  for (const auto& vertex : vertices_) {
```

2021-11-29 14:17 UTC, Friend-LGA requested changes
`JSON` невалидный, он даже красным подсвечивается, как просмотрел-то?

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +}
Не правильно. Эти функции должны возвращать новый `id`, а они просто переменную возвращают, к которой у нас итак есть доступ. Эти функции реализуют логику - возвращают значение `id` и увеличивают счетчик, иначе зачем они нужны?

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +  bool operator==(const Vertex& right_edge) const;
И второе, не вижу, чтобы он где-то использовался

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +      if (j < vertex.get_connected_edges_count() - 1) {
Чем плодить миллион функций, лучше просто верни `const` ссылку на вектор
```suggestion
    const auto& edge_ids = vertex.connected_edge_ids();
    for (const auto edge_id : edge_ids)  {
      json << edge_id;
      if (edge_id != edge_ids.back()) {
```

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +void json_to_file(std::string str) {
Всё, что не является фундаментальным типом, лучше передавать по `const` ссылке

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +}
Не используются

2021-11-29 14:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +        json << "]" << std::endl;
Если открываешь скобку вне цикла, то и закрывать её нужно вне цыкла.
Иначе, в случае, если элементов 0, то у тебя будет только открытая скобка, а закрытой не будет.
Эта логика к циклу не относится.

2021-12-02 05:48 UTC, Alexsetyaev commented on 02_knight_and_princess/setyaev_alexander/graph.cpp
> +  Graph g;
test

2021-12-02 06:17 UTC, Friend-LGA requested changes

2021-12-02 06:17 UTC, Friend-LGA commented on setyaev_alexander/graph.cpp
> +std::string Graph::to_string() const {
```cpp
Edge::to_string;
Vertex::to_string;
```

2021-12-02 07:12 UTC, Friend-LGA approved these changes

2021-12-02 07:15 UTC, merged