task01 solution
Friend-LGA/msu_course_cpp_323 pull request #6
Opened 2021-09-09 07:00 UTC by Flagro

Anton Potapov's task01 solution

2021-09-14 20:15 UTC, Friend-LGA requested changes
Добавь скриншот в `README.md`

2021-09-14 20:15 UTC, Friend-LGA commented on task_01/anton_potapov/README.md
> +Антон Потапов
Где скриншот?

2021-09-15 08:29 UTC, Flagro commented on task_01/anton_potapov/README.md
> +Антон Потапов
> Где скриншот?

Ой, скриншот потерялся. Добавил его

2021-09-15 12:42 UTC, Friend-LGA requested changes

2021-09-15 12:42 UTC, Friend-LGA commented on task_01/anton_potapov/README.md
> +Антон Потапов
А в README.md добавить забыл?)

2021-09-16 07:00 UTC, Flagro commented on task_01/anton_potapov/README.md
> +Антон Потапов
Почему-то коммиты не подтягиваются. Создаю новый пулл реквест

2021-09-16 07:07 UTC, closed without merging