dana_stepina/task_02
Friend-LGA/msu_course_cpp_323 pull request #60
Opened 2021-10-07 09:44 UTC by Procyon13

2021-10-12 08:19 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +int i = 0, j = 0;
Обсуждали:
1. Никогда не используй глобальные переменные, их невозможно контролировать. Только глобальные константы.
2. Нужно писать выразительный, легко читаемый и понимаемый код. Однобуквенные названия переменных - это какая-то криптография. Такой код ближе к машинному, чем к человеческому языку.

2021-10-12 08:19 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +struct E {
Читай `Naming Convention`

2021-10-12 08:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +    v_g = new V[count_v];
Обсуждали, не использовать низкоуровневые манипуляции с памятью, и не использовать `C-style` code. Мы хотим научиться пользоваться теми инструментами, которые нам дает `C++`
Соответственно, если хочешь использовать поинтеры, то используй `smart pointers`
Конкретно в данном случае, вообще нет необходимости использовать поинтеры, попробуй упростить логику.

2021-10-12 08:25 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +  void print_mass_vertices();
Почему ты везде назвала их `mass`? У них нету массы. Все что у них есть на данный момент - это `id`.

2021-10-12 08:27 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +  friend void input_file_json(GRAPH& graph);
В большинстве случаем использовать `friend` нет необходимости, особенно учитывая, что его использование ломает инкапсуляцию. Нужно всегда пытаться избежать использования `friend`, и прибегать к этой логике только в исключительных случаях, когда это действительно необходимо.

В твоем же случае, нужно просто написать удобный интерфейс для взаимодействия с графом, и никаких `friend` не понадобится

2021-10-12 08:29 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +  };
Договаривались не использовать `C` синтаксис.
Если тебе нужен массив - то используй `std::array` или `std::vector`

2021-10-12 08:34 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +}
В одной функции заключено слишком много логики. Чтобы упростить логику и избежать потенциальных ошибок, нежно пытаться писать такие функции, которые реализуют как можно меньше логики, которые решают только одну маленькую задачу. Чем меньше кода - тем лучше.
В данном случае её будет легко разделить на следующие действия:
```cpp
void print_graph();
void print_vertex();
void print_edge();
void save_file();
```

2021-10-12 08:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +  int t[][2] = {
Если создаешь локальные переменные, которые не планируешь модифицировать, то нужно помечать их как `const`, они ведь и есть по факту константы.

2021-10-12 08:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.json
> +}
Видишь гит ругается на отсутствие пустой строки в конце файла?

2021-10-12 08:36 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph_oop.cpp
> +  // cout<<"graph"<<endl;
Лишние комментарии незадействованного кода никому не нужны.

2021-10-13 18:05 UTC, Friend-LGA requested changes

2021-10-13 18:05 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  std::vector<Vertex> get_vertices() { return graph_vertices_; }
Чем копировать, потенциально большие объекты, лучше возвращать `const` ссылку
```suggestion
  const std::vector<Edge>& get_edges() { return graph_edges_; }
  const std::vector<Vertex>& get_vertices() { return graph_vertices_; }
```

2021-10-13 18:05 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  int count_edges = 0;
Эта переменная вообще нигде не используется, зачем она нужна?

2021-10-13 18:05 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  int count_vertices = 0;
Зачем тебе вручную считать, когда это уже есть готовое?
```suggestion
  int count_vertices() const { return graph_vertices_.size(); }
```

2021-10-13 18:05 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  }
Логика генерации графа не должна находиться внутри графа, это не его обязанность генерировать самого себя. Граф знает только о вершинах и гранях, которые хранит, а о том, как нужно генерировать граф должен заботиться кто-то другой. В твоем случае достаточно будет просто вынести эту функцию в глобальный скоуп.

2021-10-18 15:35 UTC, Friend-LGA requested changes

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  int vertex_end = 0;
Ты указала `id` - `const`, а остальные данные могут изменяться при жизни объекта? В нашем случае грань всегда связана с одинаковыми вершинами, поэтому их тоже стоит пометить как `const`

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  void add_vertices();
Эти функции включают в себя слишком большую ответственность, интерфейс можно упростить, что упростит и логику взаимодействия:
```suggestion
  void add_edge(const VertexId& from_vertex_id, const VertexId& to_vertex_id);
  void add_vertex();
```

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<Edge>& get_edges() { return edges_; }
Если функция не мутирует объект, она должна быть помечена как `const`
```suggestion
  const std::vector<Edge>& get_edges() const { return edges_; }
```

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +void print_vertex_json(std::ofstream& out, Graph& graph) {
1. Аргументы нужно передавать как `const` ссылки, иначе ожидается, что они будут меняться внутри функции:
```suggestion
void print_vertex_json(std::ofstream& out, const Graph& graph) {
```
2. "Распечатать вершины" и "Записать данные в файл" - это 2 задачи, а значит функцию можно упростить и избавиться от лишнего аргумента:
```suggestion
std::string print_vertex_json(const Graph& graph) {
```
3. Ответственность этой функции - распечатать вершины. Зачем ей знать о всем графе?
И к тому же `print_vertex` это единственное число и переводится как `распечатать вершину`, мы же печатаем коллекцию вершин, значит должны использовать множественное число:
```suggestion
std::string print_vertices_json(const std::vector<Vertex>& vertices) {
```
Но в таком случае опять, логика усложнена, зачем нам печатать вектор вершин, когда распечатать одну вершину - намного более гибкая и масштабируемая логика:
```suggestion
std::string print_vertex_json(const Vertex& vertex) {
```
Надеюсь тебе понятна данная логическая цепочка?

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +void print_edge_json(std::ofstream& out, Graph& graph) {
Аналогичные замечания

2021-10-18 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +void print_graph_json(Graph& graph) {
Аналогичные замечания

2021-11-08 16:14 UTC, Friend-LGA requested changes

2021-11-08 16:14 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +    graph.add_edge(vertex_connection.front(), vertex_connection.back());
К чему такие сложности?)
```suggestion
    graph.add_edge(vertex_connection[0], vertex_connection[1]);
```

2021-11-08 16:14 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<std::array<int, 2>> vertex_connections = {
Будет логичнее использовать `std::pair`
```suggestion
  const std::vector<std::pair<int>> vertex_connections = {
```

2021-11-08 16:14 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  Graph graph;
Не оставляй неинициализированные переменные:
```suggestion
  auto graph = Graph();
```

2021-11-08 16:14 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/graph.json
> +{
Почему у тебя изменился файл? Данные-то в программе те же самые.

2021-11-15 13:22 UTC, Friend-LGA requested changes

2021-11-15 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  bool has_edge_id(const EdgeId& edge_id) {
Методы, которые не изменяют родительский объект, должны быть помечены как `const`
```suggestion
  bool has_edge_id(const EdgeId& edge_id) const {
```

2021-11-15 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +                    const VertexId& to_vertex_id) {
Так как это публичный интерфейс и может быть вызван отдельно. То тут тоже не помешает добавить проверку на входные параметры, на существование вершин

2021-11-15 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +    for (const auto& edge : edges_)
Очень неэффективная логика, а что, если у нас миллион граней? Достаточно взять грани, присоединенные к вершинам, и найти их пересечение.

2021-11-15 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  EdgeId vertex_id_counter_ = 0;
`VertexId`?

2021-11-15 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<std::pair<int, int>> vertex_connections = {
1. Раз ты знаешь размерность вектора, будет логичней и эффективней использовать `std::array`
2. Это скорее `VertexId`, а не `int`

2021-11-15 14:25 UTC, Procyon13 commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<std::pair<int, int>> vertex_connections = {
В прошлых ПР вы писали, что лучше использовать именно pair. И vertex_count - это не размерность, потому что размерность у меня 18 на 2... Или вы что-то другое имели в виду?

2021-11-15 14:29 UTC, Procyon13 commented on 02_knight_and_princess/dana_stepina/main.cpp
> +           "A vertex with this id already exists.");
Тогда эту проверки совсем не надо делать? Ведь add_vertex() работает так, что невозможно добавить вершину с уже существующим id

2021-11-16 22:47 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<std::pair<int, int>> vertex_connections = {
Да, другое:
```suggestion
  const std::array<std::pair<VertexId, VertexId>, EDGES_COUNT> connections = {
```

2021-11-16 22:47 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +           "A vertex with this id already exists.");
Ну да, здесь проверка не нужна

2021-11-16 22:49 UTC, Procyon13 commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::vector<std::pair<int, int>> vertex_connections = {
поняла, спасибо!

2021-11-16 22:59 UTC, Friend-LGA requested changes
Осталась мелочевка, давай исправляй - и принимаю.

2021-11-16 22:59 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  return str_edge;
Вроде писал уже тебе в прошлых ревью, что здесь нет смысла создавать переменную
```suggestion
  return "\t\t{\"id\":" + std::to_string(edge.id) +
          ",\"vertex_ids\":[" +
          std::to_string(edge.vertex_start) + "," +
          std::to_string(edge.vertex_end) + "]}";
```

2021-11-16 22:59 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const int vertex_count = 14;
Лучше все-таки вынести в глобальную константу `constexpr`

2021-11-16 22:59 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  bool has_edge_id(const EdgeId& edge_id) {
Не вижу, что исправила

2021-11-17 17:36 UTC, Friend-LGA requested changes

2021-11-17 17:36 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +constexpr EdgeId EDGES_COUNT = 18;
Зачем ты заменила `int` на `VertexId`???
`VertexId` репрезентует в нашей программе только один тип - `id` вершины. Ты не можешь использовать его для обозначения количества объектов, между ними нет никакой связи.

2021-11-17 17:36 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  const std::array<std::pair<VertexId, VertexId>, 18> vertex_connections = {{
`EDGES_COUNT`?

2021-11-17 17:36 UTC, Friend-LGA commented on 02_knight_and_princess/dana_stepina/main.cpp
> +  bool has_edge_id(const EdgeId& edge_id) {
Все ещё не исправлено...

2021-11-17 19:02 UTC, Friend-LGA approved these changes
![](https://media.giphy.com/media/KEG5UtvXUD7WPIhhuy/giphy.gif)

2021-11-17 19:23 UTC, merged