robert_gaisin/task_04
Friend-LGA/msu_course_cpp_323 pull request #62
Opened 2021-10-09 13:31 UTC by geleg-rigzin

2021-11-03 10:57 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +const int Red = 4;
Вообще нужно понимать, что `enum` был изначально создан именно для такой логики, которую ты здесь реализуешь. Я не то чтобы настаиваю на использовании `enum`, я говорю, что в таких ситуациях, как эта, можно использовать только `enum`, все остальное варианты - костыли.

Ты должен научиться видеть, когда и какой тип данных нужно использовать. Если у тебя есть набор опций, которые реализуют одинаковую логику, то это и есть `enum`

Например:
- `enum class Day { Mon, Tue, Wed, Thu, Fri, Sat, Sun };`
- `enum class Month { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep< Oct, Nov, Dec };`
- `enum class Side { Left, Top, Right, Bottom };`
- `enum class Direction { North, West, South, East };`

```cpp
enum class EdgeColor { Gray, Green, Blue, Yellow, Red };
```

2021-11-03 12:10 UTC, Friend-LGA requested changes

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +int neighbour_choice(int rule, size_t k, size_t sub) {
Зачем нужен этот метод? Для синих граней? Они должны проверяться для каждой пары соседних вершин, нет необходимости ещё и по вероятности выбирать одну из 2ух, тогда финальная вероятность будет отличаться от заданной.

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  vector<int> depth_sizes_;
Думаю что просто хранить размерность глубин тебе не хватит. Как ты будешь эффективно доставать все вершины на одной глубине? Наверное тебе пригодится скорее карта глубины, что-то вроде
```cpp
std::vector<std::vector<VertexId>> depth_map_;
```

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
>  }
УУУ, слишком большая функция, слишком сложно такое читать и уж тем более вникать. Разбей на более мелкие. Логично будет что-то вроде такого:
```cpp
Graph generate_graph() {
  // ... some logic ...
  generate_gray_edges();
  generate_green_edges();
  generate_blue_edges();
  generate_yellow_edges();
  generate_red_edges();
}
```
Согласись, насколько проще будет финальная логика, нежели все в одной куче.

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
>  }
Ещё, `rand()` - это что-то сишное. Для наших задач очень хорошо вписывается [bernoulli_distribution](https://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution)

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  cin >> new_vertices_num;
А что, если я введу `depth: - 100`, программа сможет что-нибудь сгенерировать? Нужно добавить обработку вводимых данных.

2021-11-03 12:10 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  const Graph graph = graph_generator(depth, 1, new_vertices_num);
Функция = действие. Сгенерировать граф - `generate_graph`

2021-11-08 18:53 UTC, geleg-rigzin commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  Vertex(const VertexId& new_id, size_t depth_n) : id(new_id), depth(depth_n) {}
Пожалуй, здесь не соглашусь, при генерации графа я совершенно точно знаю глубину, на которой должна находиться вершина при ее генерации, коли так, то что мне мешает сразу ее добавить?

2021-11-08 20:18 UTC, geleg-rigzin commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  void add_vertex(size_t depth);
То же, что и комментарием выше

2021-11-08 20:18 UTC, geleg-rigzin commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  vector<int> depth_sizes_;
Пока достаточно того, что есть

2021-11-10 22:05 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  Vertex(const VertexId& new_id, size_t depth_n) : id(new_id), depth(depth_n) {}
"Ты" - это кто? В контексте твой программы - это функция `generate_gray_edges`. И по какой такой логике, эта функция должна высчитывать данные, которые относятся ко внутренней структуре графа, а граф за них не в ответе. Тут ты выбираешь, какая сущность будет в ответе за расчет глубины, и ты решил что эта логика лучше подходит функции `generate_gray_edges`. По этой логике получается, что мы извне можем добавлять вершины в граф на любую глубину не связывая их, как в таком случае будет выглядеть граф? Если я добавлю вершину `depth = 0` и `depth = 100`, а потом свяжу их? Будет ли такая структура валидная?

То, чего я пытаюсь от вас добиться - начать мыслить об архитектуре программы, а не о банальном написании алгоритма, для которого особых навыков и не нужно. То что ты предлагаешь - это не прорабатывать архитектуру, а решить моментальную задачу, написав код, который будет 1) не расширяемым, 2) позволяющим потенциально сломать всю структуру твоего класса. Да, такая программа будет работать, но ни для чего, кроме как выполнения текущего задания она не пригодится. Для чего ты пишешь код, просто как хобби? Если нет, то 99% кода, который пишет программист - будет использоваться другими людьми, а не только самим тобой, и, если ты не научишься закладывать качественную, защищенную от потенциальных ошибок и расширяемую архитектуру, то ценность твоя, как программиста будет очень низкой. А именно такое мышление "работает - значит этого достаточно" - ведет к низкокачественной архитектуре или же, к отсутствию архитектуры, как таковой.

Логика твоего приложения строится поверх такой структуры данных, как граф, а он, в свою очередь имеет определенную логику поведения. Глубина графа определяется количеством последовательно связанных вершин. Ты же игнорируешь эту логику, и позволяешь любому пользователю твоего графа сломать его внутреннюю структуру. В каких-то исключительных случаях это может быть оправдано, но не на этапе обучения, где ваша задача именно что, научиться писать качественный код и продумывать архитектуру.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +EdgeColor Red = EdgeColor::Red;
nit: Я бы назвал это оверкилл. Ты пытаешься укоротить все возможные названия?) Простое название цвета - слишком универсальный тип, он может относиться к совершенно разной логике. Конкретно здесь, `EdgeColor` дает понимание контекста, о каком цвете мы говорим. А размер кода особенно не страдает, эти типы используются-то в паре мест. Ты что, для каждого вводимого `enum` класса, будешь создавать отдельные типы данных для каждой опции? А если у тебя таких `enum` будет штук 5, а опций в них будет по 20? Это 100+ строк кода только на обозначение типов, которые у тебя итак уже есть.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +std::mt19937 mersenne(rd());
Мы обсуждали что нельзя использовать глобальные переменные, это зло.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  if (color == Gray) {
Для такой логики есть специально придуманная структура - `switch - case`

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +    return "\"red\"";
Не правда, потенциальная ошибка. `red` должен возвращаться только в случае `color == EdgeColor::Red`, а в остальных случаях программа должна падать

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  void add_depth(int depth);
Что за `add_depth` - добавить глубину? Как можно в граф добавить глубину? Можно добавить вершину. можно добавить грань, добавить глубину нельзя.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  if (depth >= (int)depth_sizes_.size())
Нет нужды приводить типы, итак должно работать.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  for (int i = depth_sizes_.size(); i <= depth; ++i)
У тебя есть интерфейс, который делаем именно то, что возвращает глубину. А раз у тебя есть интерфейс - используй его, таким образом избежишь дублирования кода и потенциальной ошибки.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +int neighbour_choice(int rule, int k, int sub) {
Метод не используется.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +                         Graph& returned_graph,
Почему `returned_graph`, почему не просто `graph`, что за лишняя информация?

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +                         vector<int>& offsets) {
`in-out` аргумент? Зачем он тебе? Ты что-то усложняешь здесь. Функция просто должна сгенерировать серые грани и все, про неё можно забыть, никаких данных возвращать она не должна.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  int p = 100;
Что мы говорили насчет однобуквенных названий?

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  Vertex(const VertexId& new_id, int depth_n) : id(new_id), depth(depth_n) {}
Что за `depth_n`? Объясни, что значит `_n`?

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  for (int i = 0; i < graph_depth - 1; ++i) {
1. `i` - наверное это `depth`? Почему тогда и не назовешь её `depth`?
2. Почему `i < graph_depth - 1`? Выглядит как ошибка, при глубине, например 5, глубина 4 будет последней, откуда генерируются новые серые грани, в этом случае запись будет `i < graph_depth`. Точно тут нет ошибки?

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +    }
По-идее, это всегда будет `true`, потому что у пустого графа глубина должна быть 0

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  const int p_blue = 25;
Все вот эти вероятности - это `magic number`, вынеси их в глобальные константы. Возможно ещё будет логично добавить функцию, которая будет возвращать вероятность в зависимости от цвета

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +      if (mersenne() % 100 + 1 <= p_blue) {
1. Все ещё похоже на `C`ишную логику.
2. Чем тебе не понравилось `std::bernoulli_distribution`, ещё раз повторяю, что оно реализует имено ту логику, которая дана у нас в задании.
3. Это повторяющаяся логика, будет разумным вынести её в отдельную функцию

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +}
Не похоже, что в данной логике есть необходимость, все, что тебе нужно знать - связаны ли вершины или нет, а для этого у нас уже должен быть метод `is_connected` или как-то так

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +    for (int k = offsets[i]; k < offsets[i + 1]; ++k) {
Нет смысла усложнять эту логику, для зеленых граней достаточно просто пройтись по всем вершинам, в не зависимости от их глубины

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  vector<int> offsets;
Не похоже на "удобство", похоже на что-то сложное и низкоуровневое. Попробуй обойтись вообще без этого вектора. Твою логику можно существенно упростить, и необходимости в данном оффсете совершенно нет. Каждая из функций генерации цветов имеют изолированную логику и нет нужды передавать лишние данные между ними. Нужно просто ещё немного подумать над интерфейсом графа. Причем при прошлом ревью я давал тебе намеки на то, как можно упростить твою логику.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  }
Не не не, программа не должна падать, если юзер накосячил, мы должны ожидать неверные данные, сообщить пользователю об ошибке и запросить данные снова.
Представь, если бы браузер каждый раз падал бы, когда ты ввел адрес несуществующего сайта?) Программа должна уметь обрабатывать ошибки, а не ломаться целенаправленно.

И использовать `try - catch` для этого не стоит, достаточно проверить условие и всего-то.

2021-11-10 22:48 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
>    assert(has_vertex(end) && "Vertex doesn't exist");
Мне что, писать одни и те же комментарии в каждом ревью? Почему нажал `Resolved`, хотя ничего в коде не исправил?

2021-11-10 22:52 UTC, Friend-LGA requested changes

2021-11-10 22:52 UTC, Friend-LGA commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  assert(!(is_connect && color_gray) && "Vertices already connected");
1. Все валидации входных параметров лучше писать в самом начале тела функции. Соответственно сначала `assert`, потом вся остальная логика.
2. Ты что-то усложнил тут. При любом цвете граней вершины не должны быть связаны. Проверка на цвет лишняя.

2021-11-22 21:11 UTC, geleg-rigzin commented on 02_knight_and_princess/robert_gaisin/main.cpp
> +  int p = 100;
"p" - общепринятое обозначение для вероятности

2021-11-24 13:28 UTC, Friend-LGA requested changes

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  mod_depth(0, 0);
Не логично вызывать эту функцию здесь.

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  std::mt19937 mersenne(rd());
Дублирующийся код
Вынеси в функцию
```cpp
bool is_lucky(probability);
```

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  returned_graph.add_root_vertex();
Не часть генерации серых вершин, лучше вынести на уровень выше

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +const int proba_yellow_begin = 0;
1) Naming Convention
2) `constexpr`

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +        if ((int)(mersenne() % 100 + 1) <= proba_gray) {
`std::bernuolli_distribution`
- https://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  for (int i = 0; i < graph_depth - 1; ++i) {
`i` - плохое название, лучше будет `depth`

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +      for (int c = 0; c < new_vertices_num; ++c) {
```cpp
const auto& vertices = graph.get_vertices_at_depth(depth);
for (const auto& vertex: vertices) {
  for (int i = 0; i < new_vertices_num; ++i) {
    if (is_lucky(proba_gray)) {
      const auto new_vertex_id = graph.add_vertex();
      returned_graph.add_edge(vertex.id, new_vertex_id, EdgeColor::Gray);
    }
  }
}
```

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +        ++k;
Не нужно увеличивать итератор, зачем?

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +vector<VertexId> generate_set_vertices(const vector<VertexId>& layer,
`get_unconnected_vertex_ids`

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +            vertices_to_connect[mersenne() % vertices_to_connect.size()];
```cpp
VertexId get_random_vertex_id(const std::vector<VertexId> vertex_ids);
```

2021-11-24 13:28 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  try {
Нет особого смысла отлавливать исключение

2021-12-02 15:36 UTC, Friend-LGA commented on robert_gaisin/main.cpp
>    int sub_proba_gray = proba_gray / graph_depth;
По большому счету тебе не нужны лишние переменные вне цикла, чтобы рассчитать вероятность, ты можешь в любой момент рассчитать её, зная глубину, на которой находишься, и максимальную глубину

2021-12-02 15:38 UTC, Friend-LGA commented on robert_gaisin/main.cpp
>    for (auto i = returned_graph.depth_map().begin();
`vertex_ids_at_depth`?

2021-12-04 21:50 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +const int proba_yellow_begin = 0;
Зачем изменил? Это старый комментарий был. Ты его уже исправлял.

2021-12-04 21:50 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +constexpr int proba_yellow_begin = 0;
Не исправлено

2021-12-04 21:59 UTC, Friend-LGA requested changes

2021-12-04 21:59 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +          auto new_vertex_id = returned_graph.add_vertex();
конст?

2021-12-04 21:59 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +          returned_graph.add_edge(vertex_id, new_vertex_id, EdgeColor::Gray);
Теоретически ты итерируешься и изменяешь один и тот же объект. Программа не падает? Я бы ожидал проблемы с памятью здесь.

2021-12-04 21:59 UTC, Friend-LGA commented on robert_gaisin/main.cpp
>    for (auto& vector_ids : returned_graph.depth_map()) {
`const`?

2021-12-04 21:59 UTC, Friend-LGA commented on robert_gaisin/main.cpp
>    int add_proba_yellow = 100 / returned_graph.depth();
тут тоже нет необходимости в переменной, все это можно рассчитать, зная глубину

2021-12-04 21:59 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +    assert(depth_map_.size() == 0 && "Attempt to create zero depth failed");
Данный `assert` не имеет смысла, ты только что на прошлой строчке проверил условие `empty()`, соответственно, он всегда будет `true`

2021-12-05 21:55 UTC, geleg-rigzin commented on robert_gaisin/main.cpp
> +          returned_graph.add_edge(vertex_id, new_vertex_id, EdgeColor::Gray);
Пока ни разу не упала из-за этого, я, конечно, исходный код не видел, но предполагаю, что не единственный, кто хотел бы так делать и, наверное, этот момент был предусмотрен

2021-12-07 13:26 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +          returned_graph.add_edge(vertex_id, new_vertex_id, EdgeColor::Gray);
`depth_map` - это вектор, добавляя новые вершины и грани, ты изменяешь его размер, соответственно он будет в какой-то момент переаллоцирован. Ну, если не падает, то отлично.

2021-12-07 13:33 UTC, Friend-LGA requested changes
Что-то не так с вероятностями. На предпоследней глубине от каждой вершины должны отходить желтые грани.

> Глубина графа 0: 0%
> . . .
> Глубина графа N-1: 100%

![Screenshot 2021-12-07 at 16 30 21](https://user-images.githubusercontent.com/5897136/145038149-40ad6414-01a5-4c8f-ac03-c567d11660ee.png)

2021-12-08 10:54 UTC, Friend-LGA requested changes

2021-12-08 10:54 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> -            graph.get_vertex((*vertex_ids_at_depth).front()).depth;
```cpp
((float)depth / (float)max_depth) * 100
```
`graph.depth()` должен возвращать глубину графа, а не количество уровней глубины

2021-12-08 11:25 UTC, Friend-LGA requested changes

2021-12-08 11:25 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  if (graph.depth() > 1) {
```cpp
if (graph.depth() < 2) {
  return;
}
```

2021-12-08 11:26 UTC, Friend-LGA requested changes

2021-12-08 11:26 UTC, Friend-LGA commented on robert_gaisin/main.cpp
> +  for (auto vertex_ids_at_depth = graph.depth_map().begin();
```
if (graph.depth())
```

2021-12-08 11:52 UTC, Friend-LGA approved these changes

2021-12-08 11:53 UTC, Friend-LGA requested changes
почему 2 бинарника?

2021-12-08 11:55 UTC, Friend-LGA approved these changes

2021-12-08 11:55 UTC, merged