anton_potapov/task_04
Friend-LGA/msu_course_cpp_323 pull request #66
Opened 2021-10-14 06:21 UTC by Flagro

Anton Potapov task_03

2021-10-16 11:50 UTC, Flagro commented
Пример генерируемого графа 
![image](https://user-images.githubusercontent.com/47938145/137586133-9a1e5154-a8fe-4f0d-ab28-2c723384d96b.png)

2021-11-05 17:59 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +enum class Color { GRAY, GREEN, BLUE, YELLOW, RED };
EPS пофиксил тут 857fbb94862fb23fe618ac3541459f2008f494c7

2021-11-05 17:59 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +enum class Color { GRAY, GREEN, BLUE, YELLOW, RED };
enum пофиксил тут 88ab3e515066233795e20edadb697cfa18f4f357

2021-11-05 18:18 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
Описание синих ребер из формулировки задания: "Синяя: 25% что соседние вершины, находящиеся на одной глубине, будут соединены".  Судя по приведенному примеру графа и описанию, я определил "соседние" как соседние по номеру, что наверное не очень осмысленно и неправильно

2021-11-05 18:22 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
поменял название метода, теперь оно более осмысленное 675fde8ec4b39694365fa5035b7873726962ef50

2021-11-05 18:25 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  size_t depth;
поправил 29b54925c5e853d2ea857d1393ba05b15c9b3f2e

2021-11-05 18:30 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
>  }
Жалко было). Замерджу задачу - код потеряется. Поправил c701d3e56eb36c5e9bc93fb7f660cc1f7d36e69f

2021-11-05 18:40 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +       Color edge_color)
Вроде enum'ы должны мало весить, но с другой стороны const нужен

2021-11-05 18:41 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +       Color edge_color)
поправил c4e41ebbb888556e078c41ce161ac15795c4e0a9

2021-11-05 18:58 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  void init_depth(size_t new_depth) { depth = new_depth; }
пофиксил 1912b097c0a926ed17cd941be15b7b09f8c9a622

2021-11-05 19:01 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  const std::string color;
ой, это вообще какая-то unused variable была, пофиксил 45e220f09eb0f30137ecd0043600a0aa0e3cc6e6

2021-11-05 19:11 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +        {Color::RED, "red"}};
сделал 7cfa78d862d163188f638680666f762de89c531a

2021-11-05 19:18 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string get_json_string() {
Я реализовал что-то типо ленивых вычислений: до тех пор, пока нам не понадобятся значения глубин каждой вершины, я их пересчитывать не буду. Например, если мы добавляем (и потенциально потом удаляем) много вершин, то если мы каждый раз будем пересчитывать глубины `bfs`'ом, это будет очень неэффективно по времени. Здесь же знать глубины вершин нам нужно только для экспорта в `json` и для геттера для реализации самой задачи. Чтобы обновить значения глубин я сделал функцию `update_vertices_depth()`, которая вызывается перед экспортом в функции `get_json_string()` и заодно обновляет соответствующие поля `depth` у классов.

2021-11-05 19:22 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string get_json_string() {
При чем этого нельзя избежать, убрав все эти `depth` поля у классов и просто пересчитывая `bfs`'ом нужные значения, возвращать их в геттерах, так как у нас рекурсивная генерация `json` строки, а значит эти поля нужны и рано или поздно будут нуждаться в обновлении

2021-11-05 19:24 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string get_json_string() {
Не знаю как выйти из данной ситуации кроме как поменять название метода, на что-то типо `get_updated_json_string()`, но вроде это лишняя информация для пользователя класса

2021-11-05 23:03 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +}
Сделал объект 559e3edd33b4914b745cb24e6de764b9aea473ac

2021-11-05 23:35 UTC, Flagro commented
В итоге разделил получившийся огромный файл на несколько маленьких в последнем коммите da00987e36e4725b89bb90de0f5dee99f256cd1a . Вынес все, что относится к графу (классы `Edge`, `Vertex`, `Graph` вместе со всеми константами) в файл `graph.hpp`, генератор графа в файл `graph_generator.hpp` и решение самой задачи оставил в файле `graph_create.cpp`.

2021-11-06 14:44 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +       Color edge_color)
Да, все легкие данные можно передавать по значению. Но в первую очередь это относится к фундаментальным данным как `int`, `float` и тд... А вот все остальное `Class`, `Struct`, `Enum Class`, даже если они маленькие, лучше передавать по `const` ссылке

2021-11-06 16:00 UTC, Friend-LGA requested changes

2021-11-06 16:00 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +            std::advance(rand_it, rand_id);
1. Одинаковая логика с красными гранфми, будет логичным вынести в функцию, например `get_random_verterx_id(not_connected_vertices)`
2. `std::rand() %` - это `C`. Используй `C++` логику, подобную той, что ты использовал в `is_lucky`

2021-11-06 16:01 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  }
Добавил комментарий в новое ревью

2021-11-06 16:02 UTC, Friend-LGA commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string get_json_string() {
Добавил комментарий в новое ревью как избавиться от метода `update_vertices_depth()`

2021-11-18 06:11 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +enum class EdgeColor { GRAY, GREEN, BLUE, YELLOW, RED };
Прочитал еще раз и кажется пофиксил 1e08bef38871ee839296684c0007413d5bbbcb4e

2021-11-18 06:23 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  return color_string_map.find(color)->second;
переписал b704ed274792e0359933cd77eb444f7897ec1370

2021-11-18 06:56 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  }
Неправильно понял условие). Пофиксил 4aa5c9492c70e7f164ea6896e701f5930342296a

2021-11-18 07:14 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +};
Разобрались на паре, BFS оставляем и добавляем сложную логику с ленивыми вычислениями)

2021-11-18 07:17 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  return color_string_map.find(color)->second;
переписал b704ed274792e0359933cd77eb444f7897ec1370

2021-11-25 10:17 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  std::string get_json_string() {
Готово a09e89ae0dfe711a354ddab47a0b963024df9f3e

2021-11-25 10:18 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +      auto vertex_pair_iterator = vertices_.find(vertex1_id);
сделал a09e89ae0dfe711a354ddab47a0b963024df9f3e

2021-11-25 10:20 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +    return new_edge_id;
ленивые вычисления

2021-11-25 10:36 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  return graph_generator.graph;
тут все пофикшено cc8895f6cc1afbccd74289ebb175e526ec93cdab

2021-11-25 10:36 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +  return graph_generator.graph;
и тут a09e89ae0dfe711a354ddab47a0b963024df9f3e

2021-11-25 10:38 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +Graph task_03_get_graph(const int depth, const int new_vertices_num) {
согласен, убрал cc8895f6cc1afbccd74289ebb175e526ec93cdab

2021-11-25 10:44 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +                  EdgeColor edge_color = EdgeColor::GRAY) {
const добавил, валидацию входного параметра за меня сделает компилятор) db5164ca4f11fb12118eec420fc85bee82d2abf0

2021-11-25 10:46 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_create.cpp
> +    }
кажется, что с исключениями было элегантней). Типо функцию task_03_get_graph() мы могли бы вызывать не только при вводе cc8895f6cc1afbccd74289ebb175e526ec93cdab

2021-11-25 10:48 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  size_t max_depth() const { return max_depth_; }
Вообще говоря, `map` в `vertices_at_depth` мог расширяться, когда мы с ним через `find` работали, и максимальная глубина через `size()` была бы не валидной

2021-11-25 10:55 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +    return new_vertex_id;
ох уж этот си 44b617e16b62559d5be8a6e168405a5325317284

2021-11-25 11:04 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +                   Edge(new_edge_id, vertex1, vertex2, edge_color));
согласен, поправил a80c7be2f96d32e1122f07de718d476f9851d51e

2021-11-25 11:17 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  size_t max_depth() const { return max_depth_; }
поправил ef8d7b9d21bd543b638b76ce7e4c6171a13405f1

2021-11-25 11:17 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  size_t max_depth_;
поправил ef8d7b9d21bd543b638b76ce7e4c6171a13405f1

2021-11-25 11:19 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +bool is_lucky(const double probability) {
поправил feca35271e2cacef8d1a5dfb58166981da09ab60

2021-11-25 11:21 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +      auto same_depth_vertices = graph.get_vertices_at_depth(i);
Изначально у нас бы `get_vertices_at_depth()` корректно отработала и вернула пустой `set`

2021-11-25 13:59 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  }
пофиксил 25a1ec30e96ef154845b1b7c77a361ea5fb74669

2021-11-25 14:06 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +constexpr double DOUBLE_COMPARISON_EPS = 1e-9;
2da96693230a07fe5f469bd7427291c1bf598da7

2021-11-25 14:08 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +constexpr double DOUBLE_COMPARISON_EPS = 1e-9;
Float не хотелось из-за каких-то флешбеков после си и его printf

2021-11-25 14:10 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +  Graph graph;
вот тут пофиксил a09e89ae0dfe711a354ddab47a0b963024df9f3e

2021-11-25 14:24 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph.hpp
> +  std::map<size_t, std::set<VertexId>> vertices_at_depth_;
пофиксил 77f450b6b619cd5f3e036b46fdf4a27738904175

2021-11-25 14:25 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +      auto same_depth_vertices = graph.get_vertices_at_depth(i);
пофиксил 77f450b6b619cd5f3e036b46fdf4a27738904175

2021-11-25 14:29 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +      if (is_lucky(0.1)) {
пофиксил 8099333f71d85d1d6c374c0fc2e416f7fc423156

2021-11-25 14:47 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +        for (const auto& vertex2_id : same_depth_vertices) {
Аааа, теперь понял. Понятие "соседних вершин" в синих ребрах какое-то немного размытое

2021-11-25 15:05 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +        for (const auto& vertex2_id : same_depth_vertices) {
сделал 4d9040a77c20f9b012d44906c3d32ce0bbff265d

2021-11-25 15:28 UTC, Flagro commented on 02_knight_and_princess/anton_potapov/graph_generator.hpp
> +            std::advance(rand_it, rand_id);
сделал 3c8fca89cde7c6dfb61b2ab26895e7c1af4242d0

2021-11-25 18:09 UTC, Friend-LGA requested changes
Обновись на свежий мастер

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
Зачем?

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  return *rand_it;
Так не попроще будет выглядеть?
```suggestion
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<> dist(0, vertex_id_set.size() - 1);
  auto iter = vertex_id_set.begin() + dist(gen);
  return *iter;
```

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +}
Не забывайте про знак пустой строки

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph_create.cpp
> +  Graph graph = std::move(graph_generator.generate_graph());
`std::move` в этом случае должен автоматически происходить, по идее

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph_create.cpp
> +  GraphGenerator graph_generator(depth, new_vertices_num);
`const`?

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph_create.cpp
> +    if (depth < 0 || new_vertices_num < 0) {
Лучше по очереди их проверять, попробуй, это же не удобно с точки зрения пользователя, нужно сразу информировать об ошибке

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +  Graph& generate_graph() {
Не надо ссылку возвращать, просто создай локальную переменную и верни её по значению.
Не нужно хранить `graph_`

2021-11-25 18:09 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +  std::map<int, std::set<VertexId>> initial_depth_distribution_;
По идее тебе не нужны лишние переменные

2021-11-25 20:19 UTC, Flagro commented on anton_potapov/graph.hpp
> +}
куда-то он потерялся... 210aaf65786174c51b5a500d9b0b5db3055dbff0

2021-11-25 20:26 UTC, Flagro commented
Очень много времени потратил на обновление форка, почему-то стандартная рекурсивная стратегия слияния не помечала два нужных файла как ours, и просто не выдавала никаких предложений разрешения конфликта в diff3 конфликтстайле. Потребовалось часа два, чтобы додуматься использовать стратегию `-s resolve`

2021-11-25 20:30 UTC, Flagro commented on anton_potapov/graph.hpp
> +    this->vertices_ = std::move(other_graph.vertices_);
Как-то так спокойней, ощущение безопасности от конфликтов имен) ca88599d8398f5c0987c06ebd794cd760dbe946a

2021-11-25 20:33 UTC, Flagro commented on anton_potapov/graph.hpp
> +                  const EdgeColor edge_color = EdgeColor::Gray) {
да ea0eb6d4d2a74c0bfb4805351e6e75e86fbb3d4b

2021-11-25 20:35 UTC, Flagro commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
Чтобы не дублировать код в константной и неконстантной версии

2021-11-25 20:44 UTC, Flagro commented on anton_potapov/graph.hpp
> +  return *rand_it;
92e638eaf9cc58cfab888e31bbfde8a6e2069147 сделал, только у меня там не random access итераторы

2021-11-25 20:52 UTC, Flagro commented on anton_potapov/graph_create.cpp
> +  Graph graph = std::move(graph_generator.generate_graph());
так не компилируется, без `std::move` вызывается конструктор копирования, которого нет)

2021-11-25 20:58 UTC, Flagro commented on anton_potapov/graph_create.cpp
> +    if (depth < 0 || new_vertices_num < 0) {
сделал 86f28b02d0eb13a49a8cc88549cacb4a5ba627f7

2021-11-25 21:56 UTC, Flagro commented on anton_potapov/graph_create.cpp
> +  Graph graph = std::move(graph_generator.generate_graph());
убрал возвращение ссылки и теперь все норм) 1088a19974c430d09de88feb7200b544bd64bd36

2021-11-25 21:57 UTC, Flagro commented on anton_potapov/graph_create.cpp
> +  GraphGenerator graph_generator(depth, new_vertices_num);
не очень понял вообще суть генераторов, поправил с учетом темплейтов в новой формулировке задания 1088a19974c430d09de88feb7200b544bd64bd36

2021-11-25 21:57 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  Graph& generate_graph() {
1088a19974c430d09de88feb7200b544bd64bd36

2021-11-25 21:57 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  std::map<int, std::set<VertexId>> initial_depth_distribution_;
сделал как в темплейтах в новой формулировке задания 1088a19974c430d09de88feb7200b544bd64bd36

2021-11-25 22:00 UTC, Flagro commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
![image](https://user-images.githubusercontent.com/47938145/143503174-00802a64-05a0-430a-abc2-643c5fcf4925.png)

2021-11-26 16:35 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +constexpr float DOUBLE_COMPARISON_EPS = std::numeric_limits<float>::epsilon();
Не похоже на `double`

2021-11-26 16:35 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
Я писал, как можно обойти эту проблему, почитай:
- https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#const-methods-overriding

2021-11-26 16:37 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +    this->vertices_ = std::move(other_graph.vertices_);
Никаких конфликтов быть не должно без `using namespace`

2021-11-26 17:10 UTC, Friend-LGA requested changes

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
И примени этот подход ко всем остальным дублированным методам

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +                  const EdgeColor& edge_color = EdgeColor::Gray) {
Добавь `assert` для валидации цвета.
- Серые только для новых
- Зеленые только к самой себе
- Синие только на одной глубине
- Желтые на соседней глубине
- Красные с разницей в одну глубину

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +          VertexId new_vertex = graph.add_vertex();
`new_vertex` -> `new_vertex_id`
`const`

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
`i` -> `current_depth`

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
Оно вообще работает? По идее `graph.max_depth()` всегда должен быть 0, пока ты не вызовешь `update_depth`

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +    const auto initial_depth_distribution = graph.depth_distribution();
Нет смыла в этой переменной, у всех есть доступ к графу, кто надо - тот запросит

2021-11-26 17:10 UTC, Friend-LGA commented on anton_potapov/graph_generator.hpp
> +    const auto& cur_depth_vertices = depth_distribution.find(cur_depth)->second;
`graph.get_vertices_at_depth()` зачем тебе?

2021-11-26 18:12 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +constexpr float DOUBLE_COMPARISON_EPS = std::numeric_limits<float>::epsilon();
действительно b71d3adce023da6d0f95ffcd6b65ab795337c8aa

2021-11-26 18:14 UTC, Flagro commented on anton_potapov/graph.hpp
> +  size_t depth;
05576dd74df6f5e9d8810e8abee12fd494b2069f

2021-11-26 18:15 UTC, Flagro commented on anton_potapov/graph.hpp
> +    auto it_vertex1 = vertices_.find(vertex1);
так там вроде итератор удобно использовать

2021-11-26 18:22 UTC, Flagro commented on anton_potapov/graph.hpp
> +      vertices_at_depth_[depth].insert(vertex_id);
ух, да 4a1bf824f0e95722253a59221422d05472219e2e

2021-11-26 18:44 UTC, Flagro commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
that's exactly what i've been looking for eaac6b66e42d7327573bbaea1dbf255c111b34e7
к остальным сейчас тоже применю

2021-11-26 18:49 UTC, Flagro commented on anton_potapov/graph.hpp
> +  std::string get_json_string_private() const {
5c724ed4670e15f39e634eaa4b4edd99d0c24174 готово

2021-11-26 19:00 UTC, Flagro commented on anton_potapov/graph.hpp
> +        auto& vertex_edge = get_edge(vertex_edge_id);
согласен согласен 98126c4c64ea2efd8274ad1b4aad254253b44469

2021-11-26 19:05 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto& cur_depth_vertices = depth_distribution.find(cur_depth)->second;
видимо я изобрел `get_vertices_at_depth` после этого кода и забыл)

2021-11-26 19:13 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto& cur_depth_vertices = depth_distribution.find(cur_depth)->second;
пофиксил 9bcfb4649fd52d9d4accc276eaf1064af0652227

2021-11-26 19:21 UTC, Flagro commented on anton_potapov/graph.hpp
> +    return vertices_.find(id)->second;
```diff
- Undefined Behavior

2021-11-26 19:22 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
у меня `max_depth()` обновляет глубины

2021-11-26 19:27 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
Вроде все в порядке)

2021-11-26 19:29 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
642d3f036d34320a77c07093943934c0c6dbae8c

2021-11-26 19:34 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +  for (int i = 0; i <= graph.max_depth(); ++i) {
e7b126c74a753ffd8a3b4bdd7452522e1653bc44 и тут еще сделал дополнительное условие, так как это во-первых это впустую потраченная итерация цикла, а во-вторых у нас функция is_lucky может выполниться у слишком lucky вызова

2021-11-26 19:51 UTC, Flagro commented on anton_potapov/graph.hpp
> +  void update_vertices_depth() {
Кстати насчет второго пункта действительно, надо было сразу думать над аналогом bfs'a для динамических графов

2021-11-26 19:53 UTC, Flagro commented on anton_potapov/graph.hpp
> +  void update_vertices_depth() {
Вроде можно запоминать, на какой минимальной глубине у нас были последние изменения, и потом, имея в памяти промежуточные вычисления прошлого bfs'a, можно перерасчитывать только большие глубины, потому что они только могут уменьшиться с добавлением ребер

2021-11-26 19:53 UTC, Flagro commented on anton_potapov/graph.hpp
> +  void update_vertices_depth() {
вроде просто реализовать, сейчас попробую

2021-11-27 10:33 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto& cur_depth_vertices = depth_distribution.find(cur_depth)->second;
стоп, так в этом же и смысл, нам нужно заморозить значения глубин, потому что при добавлении красных вершин они активно меняются

2021-11-27 11:35 UTC, Flagro commented
Нашел очень неприятную багу, которая мне долгое время все ломала. Эти методы, которые я активно использую, возвращают ссылку на внутреннюю структуру, которая меняется вообще в рандомное (с точки зрения пользователя) время, в итоге все итераторы и range-based циклы по возвращаемой структуре работать не будут. Единственные варианты решения этой проблемы - это возвращать в этих методах не ссылку, а копию (что долго), либо как-то забанить пользователю range-based циклы (я не знаю как это сделать))
![image](https://user-images.githubusercontent.com/47938145/143679370-36e8322c-9f53-4519-af63-1285102dddcb.png)

2021-11-27 11:37 UTC, Flagro commented
в итоге пока что буду возвращать копию

2021-11-27 12:03 UTC, Flagro commented on anton_potapov/graph.hpp
> +                  const EdgeColor& edge_color = EdgeColor::Gray) {
готово 6f8dc8de524b2cd0c50ead6e0be0ee4ed0c0e58d

2021-11-27 12:04 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto initial_depth_distribution = graph.depth_distribution();
да, у меня там баг был, описал ниже
6f8dc8de524b2cd0c50ead6e0be0ee4ed0c0e58d

2021-11-27 12:05 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto& cur_depth_vertices = depth_distribution.find(cur_depth)->second;
вообще говоря не очень понятно, что с красными вершинами делать, не очень очевидно, нужно ли динамически обновлять глубины по мере их добавления или нет
сделал динамическое обновление 6f8dc8de524b2cd0c50ead6e0be0ee4ed0c0e58d

2021-11-27 12:17 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +          VertexId new_vertex = graph.add_vertex();
6bd9a694008c91bf5ef89637f3e15d8088a24fb6

2021-11-27 12:40 UTC, Flagro commented on anton_potapov/graph.hpp
> +    auto it_vertex1 = vertices_.find(vertex1);
d49922de2bc8c0f7caeac481e47618c1756a7dfa

2021-11-27 12:44 UTC, Flagro commented on anton_potapov/graph.hpp
> +    return vertices_.find(id)->second;
заменил на `map::at`, оно выбрасывает исключение в таком случае

2021-11-27 12:44 UTC, Flagro commented on anton_potapov/graph.hpp
> +    return vertices_.find(id)->second;
d49922de2bc8c0f7caeac481e47618c1756a7dfa

2021-11-27 13:00 UTC, Flagro commented on anton_potapov/graph.hpp
> +  void update_vertices_depth() {
реализовал первую идею d9ded9e18b3ed90f55ae959890e070bb08f834d1

2021-11-27 23:33 UTC, Flagro commented on anton_potapov/graph.hpp
> +  void update_vertices_depth() {
готово feeeca1e2805cf1ef5db55e3d7808c44a7cd8920

2021-11-29 16:45 UTC, Friend-LGA requested changes

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +  int minimum_updated_depth = UNREACHABLE_DEPTH;
`minimum` - кажется это излишняя информация, просто `updated_depth` логически то же самое, да?

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +      }
кажется что всю эту логику можно объединить, как-то так
```cpp
  if (minimum_updated_depth >= 0) {
    for (const auto& vertex_id : vertices_at_depth_.at(minimum_updated_depth)) {
      used.insert(vertex_id);
    }
  }
  int next_depth = minimum_updated_depth + 1;
  for (const auto& vertex_id : vertices_at_depth_.at(next_depth)) {
    depths.emplace(vertex_id, next_depth);
    bfs_queue.push(vertex_id);
    used.insert(vertex_id);
  }
}
```

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +           vertices_.find(current_vertex_id)->second.connected_edges()) {
`get_vertex()`

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +        const Edge connected_edge = edges_.find(connected_edge_id)->second;
Зачем копию делаешь?

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +        vertices_at_depth_.erase(invalid_depth);
Есть такая версия `erase`
```cpp
iterator erase( iterator first, iterator last );
```

2021-11-29 16:45 UTC, Friend-LGA commented on anton_potapov/graph.hpp
> +    if (!something_changed) {
Длинная функция, можешь её разбить на более мелкие?

2021-11-29 17:30 UTC, Friend-LGA commented
> в итоге пока что буду возвращать копию

Плохая идея
1) Если это конст функция, то нет смысла делать копию
2) Это не твоя ответственность, а как раз-таки отвественность пользователя. Он должен понимать, что итерирует и изменяет один и тот же объект, а так делать нельзя. Это не проблема интерфейса - это проблема программиста, который написал такой код. Но хороший интерфейс, конечно, может помочь избежать части таких проблем. Защита от дурака нужна, но не всегда она возможна.

Блин, я написал длинный подробный комменентарий об этой проблеме, а потом сделал ревью из другой вкладки и комментарий потерял))) печаль... Ну надеюсь сейчас тоже более-менее понятно объяснил.

2021-12-01 09:28 UTC, Flagro commented on anton_potapov/graph.hpp
> +  bool something_changed = true;
ух, плюс одно знание на пути написания читаемого кода 8197cb9a9a35aef1441cd60b61ffe01fa0fa28c4

2021-12-01 09:32 UTC, Flagro commented on anton_potapov/graph.hpp
> +  int minimum_updated_depth = UNREACHABLE_DEPTH;
Про `minimum`, не совсем понятно, в `updated_depth` по идее может лежать любое значение глубины, большее чем `minimum_updated_depth`, но в целом вроде бы без разницы) f3e8d93e3b5c04731b00ec4648a649ab0595a55c

2021-12-01 09:38 UTC, Flagro commented on anton_potapov/graph.hpp
> +  explicit Vertex(const VertexId& vertex_id) : id_(vertex_id) {}
Разве нам не удобно будет уметь отличать промежуточное состояние, когда вершина была добавлена, но не была связана ребром/ее значение глубины с момента добавления не было обновлено? У меня на этом держится логика валидации добавленного ребра по цвету). Просто не очень хочется реализовывать инициализацию глубины вершины сразу при ее добавлении, это как-то противоречит логике ленивых вычислений, так как мы будем обновлять это значение гарантированно дважды: при инициализации и при очередном обновлении

2021-12-01 09:40 UTC, Flagro commented on anton_potapov/graph.hpp
> +    update_vertices_depth();
Второй вариант конечно кажется более легким в реализации). Вроде легко, попробую поправить

2021-12-01 09:45 UTC, Flagro commented on anton_potapov/graph.hpp
> +  virtual ~Graph() = default;
вдруг будет)) 3943eb74234c9c87548683f9af342330bb99c314

2021-12-01 09:48 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +      if (is_lucky(RED_EDGE_PROB) && !next_depth_vertices.empty()) {
действительно, не заметил, когда добавлял `break` 94f1fcae376f4fca5ec19c29685ce2927b48d8e8

2021-12-01 10:13 UTC, Flagro commented on anton_potapov/graph.hpp
> +        vertices_at_depth_.erase(invalid_depth);
готово ef37597babe1988286e62f2fd6931db1c2efafbd

2021-12-01 10:14 UTC, Flagro commented on anton_potapov/graph.hpp
> +           vertices_.find(current_vertex_id)->second.connected_edges()) {
1b1c8641e99dc84aee88920229ca24579aae155e

2021-12-01 10:20 UTC, Flagro commented on anton_potapov/graph.hpp
> +    if (!something_changed) {
попытался, aff8760c2acfe23e272ba0f73c51ed1ff4e4c801 , все остальное по идее сильно привязано к алгоритму BFS

2021-12-01 10:28 UTC, Flagro commented on anton_potapov/graph.hpp
> +  std::set<VertexId> get_vertices_at_depth(int depth) {
ну да, тут все-таки неконстантный метод, надеюсь тут ничего фиксить не надо)

2021-12-01 10:39 UTC, Flagro commented on anton_potapov/graph.hpp
> +      }
возможно у меня голова не соображает, но вроде не сжимается(. Нам важно при первом заполнении определить корневую вершину, учитывая, что у нас мап `vertices_at_depth_` еще пустой

2021-12-01 10:51 UTC, Flagro commented on anton_potapov/graph.hpp
> +    update_vertices_depth();
11372744604e7d47db27a84780523471087e0a01 жесть костыльно, но готово)

2021-12-01 10:58 UTC, Flagro commented on anton_potapov/graph.hpp
> +        const Edge connected_edge = edges_.find(connected_edge_id)->second;
ae17d88549df2069bc36e572d8cf3b515fabc896

2021-12-01 11:10 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +      if (depth > 1 && is_lucky((float)cur_depth / (depth - 1))) {
там просто при depth == 1 деление на ноль

2021-12-01 11:12 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +      if (depth > 1 && is_lucky((float)cur_depth / (depth - 1))) {
385d5a5cbd5facdca54ee585181c53b2a19f12bd

2021-12-01 13:00 UTC, Flagro commented on anton_potapov/graph.hpp
> +  }
b0961fb27145410d2d8d770c15134e262a69f8b0

2021-12-01 13:00 UTC, Flagro commented on anton_potapov/graph_generator.hpp
> +    const auto same_depth_vertices = graph.get_vertices_at_depth(current_depth);
b0961fb27145410d2d8d770c15134e262a69f8b0

2021-12-01 13:02 UTC, Flagro commented on anton_potapov/graph.hpp
> +  }
Мы же в общем случае не добавляем вершины по глубинам, тогда функция совсем не превращается в get_max_depth()

2021-12-01 14:09 UTC, Flagro commented on anton_potapov/graph.hpp
> +  }
c9fc50e73dac93c09f79cc7cf37346d101863c6e

2021-12-01 14:10 UTC, Flagro commented on anton_potapov/graph.hpp
> +  explicit Vertex(const VertexId& vertex_id) : id_(vertex_id) {}
c9fc50e73dac93c09f79cc7cf37346d101863c6e

2021-12-01 14:58 UTC, Friend-LGA approved these changes

2021-12-01 15:01 UTC, merged