tevfik_aksoy/task_04
Friend-LGA/msu_course_cpp_323 pull request #69
Opened 2021-10-15 10:00 UTC by AxoyTO

- Renamed task_03 -> task_04
- Updated code according to feedback on task_02/03

2021-10-20 13:02 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> -           "Vertex already exists!");
+

2021-10-20 13:03 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> -    assert(!edge_id_exists_in_vertex(_id, edge_ids_) &&
+

2021-10-20 13:04 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +std::uniform_real_distribution<float> probability(0.0, 100.0);
Добавил ф-ю

2021-10-20 13:05 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +       EdgeColor _color = "")
Удалил эту логику,  перешел на enum

2021-10-20 15:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Edge(VertexId _source, VertexId _destination, VertexId _id, Color _color)
Почему убрал `const` ссылки?
Все типы данных, которые не фундаментальные нужно передавать по `const` ссылке.

2021-10-20 15:18 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string color_to_string(const Edge::Color& color) const;
Helper метод не должен быть частью класса `Edge`, он должен быть вне его, так как логика напрямую не относится к `Edge`

2021-10-20 15:19 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Graph(VertexDepth max_depth, int new_vertices_num)
`const` ссылка
Эти параметры не должны быть частью графа, они должны передаваться генератору графа, который уже будет использовать публичный интерфейс графа, чтобы его сгенерировать.
```cpp
add_vertex();
add_edge();
```

2021-10-20 15:27 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  void add_edge(const EdgeId& _id) {
Почему переименовал? Ты добавляешь здесь `id` а не `edge`, поэтому `add_edge_id` было правильным.

2021-10-20 15:29 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +std::string Edge::color_to_string(const Edge::Color& _color) const {
Почему `_color`, а не просто `color`?

2021-10-20 15:32 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                     const VertexDepth& depth) {
Глубина неизвестна, пока ты не соединил вершину с другой вершиной. Передавать глубину при создании вершины - не правильная логика.

2021-10-20 15:35 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color) {
nit: Так как по умолчанию у нас создаются серые грани, а все остальные - это особенные случаи, тогда будет логичным указать дефолтное значение этого аргумента:
```suggestion
                   const Edge::Color& color = Edge::Color::Gray) {
```

2021-10-20 15:37 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  enum class Color { GRAY, GREEN, BLUE, YELLOW, RED };
Это не константы, не нужно называть их все большими буквами. Это скорее как тип данных, класс или структура:
```suggestion
  enum class Color { Gray, Green, Blue, Yellow, Red };
```
Обновил `Naming Convention` для `Enum`

2021-10-20 15:45 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
>             "Destination vertex id doesn't exist!");
1. Почему убрал `are_vertices_connected`?
2. `edge_id` ты на валидность проверяешь, а `vertex_id` забыл

2021-10-20 15:48 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +             "Vertices are already connected!");
В чем уникальность зеленой грани? Давай решим, что у нас так же, может быть только одна грань из вершины в саму себя, тогда логика проверки будет общей для всех

2021-10-20 15:48 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  void set_max_depth(VertexDepth max_depth) { max_depth_ = max_depth; }
Граф может знать только свою глубину, никакой `max_depth` он не знает. Эта логика должна относиться. к генератору графа.

2021-10-20 15:53 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
1. Граф не знает о том, сколько вершин может сгенерировать нулевая вершина. И он вообще не занет о том, что вершины могут генерировать друг друга, это выдуманная логика нашей задачи, и она не имеет прямого отношения к структуре `graph`. Эта логика относится к генератору графа.
2. Обходить все вершины - очень не эффективная логика, а если их у нас 100500+? Лучше хранить карту глубины, которая сможет моментально возвращать вершины с определенной глубины, например
    ```cpp
    std::vector<std::vector<VertexId>> depth_map;
    ```

2021-10-20 15:54 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  vector<Edge> get_edges() const { return edges_; }
Чем возвращать копию потенциально очень тяжелых данных, лучше вернуть `const` ссылку, а если пользователю понадобится копия - он сделает её сам
```suggestion
  const vector<Vertex>& get_vertices() const { return vertices_; }
  const vector<Edge>& get_edges() const { return edges_; }
```

2021-10-20 15:55 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      return 1;
Откуда граф знает об этом? Он не знает, об этом известно только в нашем задании, которое существует совершенно в другом измерении.

2021-10-20 15:59 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  int new_vertices_num;
Уже обсуждали, никогда не создавай неинициализированные переменные. Откуда ты знаешь что `max_depth < 0`? Потенциальная ошибка, в данный момент `int` указывает на какой-то рандомный участок памяти, который может содержать в себе значение больше 0.

2021-10-20 16:16 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Убрал

2021-10-20 16:20 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +std::string Edge::color_to_string(const Edge::Color& _color) const {
А да, просто забыл при перемещении данных от приват на public обратно, исправил

2021-10-20 16:30 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  Graph(VertexDepth max_depth, int new_vertices_num)
Исправил

2021-10-20 18:43 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                     const VertexDepth& depth) {
Не понимаю почему, но это скорее всего значит соединить их в insert_edge?

2021-10-20 18:56 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  enum class Color { GRAY, GREEN, BLUE, YELLOW, RED };
Понял, исправил

2021-10-20 18:58 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  std::string color_to_string(const Edge::Color& color) const;
Не знаю возможно ли это, пока enum class будет в структуре

2021-10-20 20:36 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Да, глубина тебе тут не поможет, это лишь вариант того, как можно обойтись вообще без `source_id`, не совсем пока понимаю, зачем тебе это вообще нужно.
Но да, в этом случае, тебе нужна будет карта еще и всех `source_id`, например
```cpp
std::unordered_map<VertexId, std::vector<VertexId>> source_vertices_map;
```

2021-10-21 06:40 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                     const VertexDepth& depth) {
Наконец теперь я все понял 😆 
![](https://futurethinkers.org/wp-content/uploads/2016/03/What-if-Artificial-Intelligence-Was-Enlightened-1038x583.jpg)

2021-10-21 09:00 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Сделал)))

2021-11-03 13:22 UTC, Friend-LGA requested changes

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          graph.insert_edge(vertex, next_random_vertex_id, Edge::Color::Yellow);
Что ты здесь такое делаешь заумное?
```suggestion
        if (filtered_next_vertex_ids.size() == 0) {
          continue;
        }
        VertexId random_vertex_id = get_random_vertex_id(filtered_next_vertex_ids);
        graph.insert_edge(vertex_id, random_vertex_id, Edge::Color::Yellow);
```
Этого недостаточно?

2021-11-03 13:22 UTC, Friend-LGA commented on .gitignore
> -.vscode/
Зачем?

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +#include <filesystem>
Зачем?

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  explicit Vertex(const VertexId& id) : id(id) {}
Работает так? Странно что компилируется. Переименуй, чтобы названия переменных не совпадали.

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      depth_map_[0].push_back(0);
Что такое `push_back(0)`? `magic_number`

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color = Edge::Color::Gray) {
А вот проверки на то что вершины существуют убирать не стоило

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color = Edge::Color::Gray) {
Еще нужно добавить валидацию на новый аргумент - `color`

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                              const VertexId& destination) {
Нужно добавить валидацию на входные параметры, что вершины существуют

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Зачем это вообще нужно?

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Если у тебя не будет функции `initialize_and_update_depth_map`, то и эта не понадобится, зачем все усложнять

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +
Не нужна... Ещё раз объяснил в другом комментарии

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        json_string += "\n  ],\n";
Видимо проглядел в прошлом ПР.
Зачем ты проверяешь это условие внутри `for`, достаточно просто вынести это после `for`

2021-11-03 13:22 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  int condition = 90;
Все вероятности - `magic numbers`, вынеси в константы.

2021-11-03 13:30 UTC, AxoyTO commented on .gitignore
> -.vscode/
Это не я сделал, fetch & pull -> такое получилось и я ничего не менял

2021-11-04 09:05 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +#include <filesystem>
Удалил

2021-11-04 09:06 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  explicit Vertex(const VertexId& id) : id(id) {}
😅 Да, работало, и IDE тоже не ругало поэтому не заметил даже, вот исправил

2021-11-04 09:08 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      depth_map_[0].push_back(0);
`-> push_back(id)`

2021-11-04 09:56 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Да я просто забыл переназвать, на самом деле функция `initialize_and_update_depth_map` только `initialize_depth_map`

2021-11-04 11:10 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Не нужно, исправил логику

2021-11-04 11:10 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  }
Не нужно, исправил логику

2021-11-04 11:15 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        json_string += "\n  ],\n";
Аааа, так точно!

2021-11-04 11:16 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        json_string += "\n  ],\n";
Но все равно надо проверить, чтобы поставить `,`

2021-11-04 11:22 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  graph.initialize_and_update_depth_map(max_depth);
Понял, удалил вообще

2021-11-04 11:27 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          graph.insert_edge(vertex, next_random_vertex_id, Edge::Color::Yellow);
Кажется да, достаточно 😅

2021-11-04 13:46 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +}
Исправил

2021-11-06 13:56 UTC, Friend-LGA commented on .gitignore
> +.vscode/
Зачем? Видимо тебе просто нужно было обновиться на свежий мастер

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      assert(false && "Color is not valid!\n");
Можно просто не добавлять `default`, тогда компилятор итак выдаст ошибку и `assert` не будет нужен

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      depth_map_[0].push_back(id);
уж лучше напиши
```suggestion
      auto& first_depth_layer = depth_map_.emplace_back({});
      first_depth_layer.push_back(id);
```
Так будет более наглядно, что мы добавляем новый пустой вектор

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          depth_map_.resize(depth + 1);
Что за мания к ресайзам, просто добавь новый элемент

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  bool is_lucky_flag = true;
Зачем ты добавил этот флаг? До этого было больше похоже на правду

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  const int condition = 90;
В прошлый раз писал про `magic number` - нужно вынести в константу

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        VertexId random_vertex_id = get_random_vertex_id_between_excluding(
Зачем, достаточно обычной `get_random_vertex_id()`

2021-11-06 13:56 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          graph.insert_edge(vertex, next_random_vertex_id, Edge::Color::Yellow);
Не нажимай `Resolved`, если вместо исправления оставил комментарий, который продолжает дискуссию.

А я тебе говорю достаточно. Ты передаешь фильтрованный вектор, и тебе нужно вернуть один элемент из него. Эта вся логика, которая тебе нужна. Не вижу никакой проблемы.

2021-11-06 14:00 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color = Edge::Color::Gray) {
Нажал `Resolved` и ничего не исправил

2021-11-06 14:03 UTC, Friend-LGA requested changes

2021-11-06 14:03 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color = Edge::Color::Gray) {
Нажал Resolved и ничего не исправил

2021-11-06 14:31 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  const int condition = 90;
```suggestion
  constexpr int GREEN_EDGE_PROBABILIY = 10;
```

2021-11-06 14:38 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      assert(false && "Color is not valid!\n");
+

2021-11-06 15:06 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  const int condition = 90;
+

2021-11-06 15:07 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        VertexId random_vertex_id = get_random_vertex_id_between_excluding(
+

2021-11-06 15:07 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  bool is_lucky_flag = true;
+

2021-11-06 15:12 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          graph.insert_edge(vertex, next_random_vertex_id, Edge::Color::Yellow);
+

2021-11-06 15:16 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      depth_map_[0].push_back(id);
`depth_map_.emplace_back({})` выдает ошибку -> `depth_map_.emplace_back();`

2021-11-06 15:33 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          depth_map_.resize(depth + 1);
+

2021-11-06 17:32 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +    if (source_id != destination_id) {
+

2021-11-07 09:20 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +                   const Edge::Color& color = Edge::Color::Gray) {
Добавил, но не уверен правильно ли

2021-11-07 09:39 UTC, AxoyTO commented on .gitignore
> +.vscode/
Обновил форк

2021-11-08 16:49 UTC, Friend-LGA requested changes

2021-11-08 16:49 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      assert(false && "Color is not valid!");
Зачем здесь `assert`?

2021-11-08 16:49 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        if (destination.id == vertices_.size() - 1)
Совершенно не обязательно. Размер массива не связан с `id` напрямую. Найди более подходящий вариант проверки

2021-11-08 17:06 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      assert(false && "Color is not valid!");
Я думал, что программа должна падать если неправильный цвет ввести например orange

2021-11-08 17:06 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +        if (destination.id == vertices_.size() - 1)
Понял, исправил

2021-11-08 18:13 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +      assert(false && "Color is not valid!");
Она итак упадет, так как у нас нет `default`

2021-11-08 18:42 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +            abs(source.id - destination.id) == 1)
Исправил

2021-11-08 19:49 UTC, Friend-LGA requested changes

2021-11-08 19:49 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          }
Тут ты проверяешь что вершина реально находится на глубине, которая в ней сохранена. Но это не относится к данной функции

2021-11-08 20:01 UTC, Friend-LGA requested changes

2021-11-08 20:01 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +            if (vertex == source.id && vertex + 1 == destination.id)
ты тут к id прибавляешь 1, хотя это больше похоже что ты хочешь взять 2 соседних элемента из массива

2021-11-09 06:23 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +            if (vertex == source.id && vertex + 1 == destination.id)
Solved

2021-11-09 15:12 UTC, Friend-LGA requested changes

2021-11-09 15:12 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +            if (source.id == first && destination.id == second)
А если наоборот? Можно вызвать эту функцию как `add_edge(0, 1)`, так и `add_edge(1, 0)`

2021-11-10 15:03 UTC, Friend-LGA requested changes
Проверил локально, с желтыми гранями что-то не то, на уровне `N-1` у них должна быть 100% вероятность генерации, а значит от каждой вершины на предпоследнем уровне должна отходить желтая грань

2021-11-10 23:10 UTC, Friend-LGA approved these changes
![](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

2021-11-10 23:16 UTC, merged