alexey_mesheryakov/task_04
Friend-LGA/msu_course_cpp_323 pull request #71
Opened 2021-10-20 17:50 UTC by alexmeshr

2021-12-15 10:30 UTC, Friend-LGA requested changes

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +    levels_ = {{vertex_id}};
1) Зачем ты пересоздаешь объект? Просто добавь внутрь новый вектор.
2) Почему проверяешь на количество вершин? Проверь на `levels_.size()`, это будет логичней

Ты должен все новые вершины класть на 0ой уровень, иначе где они находятся, в вакууме?

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +                     const Graph::Edge::Color& color) {
Ты долго сдавал, задание немного изменилось, `color` нужно вычислять динамически внутри графа. В задании есть пример кода.

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +  if (first != second)
Зачем проверка внутри условия? Условие тут лишнее, оставь просто проверку

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +  std::cout << "id: " << first << " " << second << std::endl;
Дебаг логи? Такое в коде не нужно

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +  assert(vertex_has_depth(parent_vertex_id) && "Graph must be connected");
Вершина в графе всегда должна находиться на какой-то глубине. Если бы мы писали всегда связанный граф, то интерфейс был бы другим. Поэтому при добавлении вершин, они сразу должны попадать в карту глубин на 0ой уровень

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph.hpp
> +  Depth depth_ = 0;
Тебе не нужна эта переменная, у тебя есть `levels_`

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +    for (int j = 0; j < level.size(); j++)
```cpp
for (const auto vertex_id : level) {
```

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +    auto level = graph.get_vertices_at_depth(depth);
1) `const`
2) Почему делаешь копию? Добавь комментарий в код

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +        VertexId nearest_id = randomiser ? level[j - 1] : level[j + 1];
Бери просто следующий элемент на уровне, нет нужды в рандомизации

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +        if (!graph.edge_exist(level[j], nearest_id))
Грани тут не должно быть по дизайну, если что у нас ассерт упадет. Нет нужды в проверке

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +            new_vertices.push_back(vertex_id);
вынеси в отдельную функцию
```cpp
get_unconnected_vertex_ids(vertex_id, vertex_ids);
```

2021-12-15 10:30 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +          graph.add_edge(level[j], new_vertices[rand() % new_vertices.size()],
1) `rand() % new_vertices.size()` - `C` рандомизация, используй `std::uniform_int_distribution`
2) Вынеси в функцию 
```cpp
get_random_vertex_id(vertex_ids);
```

2021-12-22 14:32 UTC, Friend-LGA requested changes

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.hpp
> +using std::vector;
Нельзя использовать `using` внутри `hpp`

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +         this->get_vertex(first).get_edge_ids())
```cpp
get_vertex(first).get_edge_ids()
```

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +bool Graph::edge_exist(const VertexId& first, const VertexId& second) {
const метод

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +#include <stdlib.h>
Вряд ли нужен

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
>    }
Вынеси в функцию
```cpp
const auto color = calculate_color(first_id, second_id);
```

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +  if (first_depth * second_depth > 0) {
1)
```cpp
if (first_depth == 0 || second_depth == 0) {
```
2) Что насчет зеленой грани к 0ой вершине

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +    set_vertex_depth(first_id, second_id);
`update_vertex_depth`

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.hpp
> +#include <string>
Где?

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +  srand(time(0));
`C` - плохо

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +  generate_yellow_edges(graph, params_.depth);
Зачем им `params_.depth`
`graph.depth()`

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +    }
```cpp
if (!level_added) {
  break;
}
```

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +            VertexId new_vertex_id = graph.add_vertex();
const

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +         "given probability is incorrect");
Объединять ассерты плохо - это усложняет дебаг

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +        auto level_for_red_edge = graph.get_vertex_ids_at_depth(depth + 2);
Зачем копия, тут должна быть ссылка

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +      if (j < level.size() - 1 &&
```cpp
    for (int j = 0; j < level.size() - 1; j++) {
```

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +    const auto level = graph.get_vertex_ids_at_depth(depth);
зачем тут копия

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +      auto level = graph.get_vertex_ids_at_depth(depth - 1);
Добавь комментарий в коде, почему ты тут делаешь копию

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +  vector<VertexId> new_vertices(0);
Зачем тут 0?

2021-12-22 14:32 UTC, Friend-LGA commented on alexey_mesheryakov/graph_generator.cpp
> +    Graph& graph,
Почему не конст

2021-12-23 07:21 UTC, Flagro requested changes

2021-12-23 07:21 UTC, Flagro commented on alexey_mesheryakov/graph.cpp
> +  throw std::runtime_error("Vertex doesn't exist");
```suggestion
const auto& vertex_it = vertices_.find(vertex_id);
if (vertex_it == vertices_.end()) {
    throw std::runtime_error("Vertex doesn't exist");
}
return *vertex_it;
```

2021-12-23 07:21 UTC, Flagro commented on alexey_mesheryakov/graph.json
> +{"depth":5,"vertices":[{"id":0,"edge_ids":[0,1,2,3],"depth":0},{"id":1,"edge_ids":[0,4,5,6,83,114],"depth":1},{"id":2,"edge_ids":[1,7,8,9,74,83],"depth":1},{"id":3,"edge_ids":[2,10,11,12,13,84,115],"
пустую строчку в конце в json файла тоже надо бы

2021-12-23 07:21 UTC, Flagro commented on alexey_mesheryakov/graph_generator.hpp
> +}  // namespace uni_course_cpp
blank line is needed :sun_with_face:

2021-12-23 07:21 UTC, Flagro commented on alexey_mesheryakov/main.cpp
> +  const int new_vertices_num = handle_new_vertices_num_input();
можно тоже auto

2021-12-23 10:47 UTC, Friend-LGA requested changes

2021-12-23 10:47 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
> +    levels_.emplace_back(vector<VertexId>(1, vertex_id));
```cpp
levels_.emplace_back(vector<VertexId>({vertex_id}));
levels_.push_back({vertex_id});
```

2021-12-23 10:47 UTC, Friend-LGA commented on alexey_mesheryakov/graph.cpp
>    VertexId vertex_id = get_new_vertex_id();
const

2021-12-23 10:47 UTC, Friend-LGA commented on alexey_mesheryakov/graph.hpp
> +  }  // without copy gives segfault
лишние комментарии

2021-12-24 12:03 UTC, Friend-LGA requested changes

2021-12-24 12:03 UTC, Friend-LGA commented on alexey_mesheryakov/main.cpp
> +  file.open("/home/alex/prac/graph_task/graph.json",
Ну ты выдал, у меня например другой путь до этой папки)) Тебе нужно не абсолютные, а относительный путь использовать

2021-12-24 12:49 UTC, Friend-LGA commented
Ещё у тебя 2 бинарника в проекте, оставь один
```
123664 Dec 24 15:48 a.out
 62832 Dec  2 16:13 gr
```

2021-12-24 14:13 UTC, Friend-LGA approved these changes
🎉

2021-12-24 14:18 UTC, Flagro approved these changes

2021-12-24 14:19 UTC, Flagro commented
🎉

2021-12-24 14:19 UTC, merged