alexey_matveev/task 02
Friend-LGA/msu_course_cpp_323 pull request #73
Opened 2021-10-23 10:27 UTC by MatveevAlexy

2021-11-06 12:54 UTC, Friend-LGA commented
Таск готов к ревью? Если готов - нужно запрашивать ревью, справа сверху есть кнопка, рядом с моей аватаркой в секции `Reviewers`. Если ПР готов к ревью - нажми её.

2021-11-15 12:43 UTC, Friend-LGA requested changes

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  bool HasVertex(const VertexId& _vertex_id) {
1. `Naming Convention`
2. Нет необходимости в `_`, достаточно просто `vertex_id` или `id`
3. Данная функция не изменяет родительский объект, а значит должна быть помечена `const`

```suggestion
  bool hasVertex(const VertexId& id) const {
```

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +    for (const auto& edge : edges_) {
Очень неэффективная логика - обходить все грани, а если их у нас миллион? Достаточно взять грани из обоих вершин и проверить их пересечение.

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  void AddVertex() { vertexes_.emplace_back(vertex_new_id_++); }
Лучше вынести логику увеличения счетчика `vertex_new_id_++` в отдельную функцию, например:
```cpp
VertexId get_new_vertex_id() { return vertex_new_id_++; }
```

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +    for (const auto& edge : edges_) {
Ага, я вижу что ты не добавил возможности взять список граней по вершине. Не помешало бы добавить такую возможность. Например `std::unordered_map<VertexId, std::vector<EdgeId>> adjacency_list_;`

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  constexpr int VERTEX_NUMBER = 14, EDGE_NUMBER = 18;
Все `magic number` - это обычно глобальные константы. И в данном случае их будет логичней записать в глобальном скопе, а не в локальном.

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  const std::vector<std::array<VertexId, 2>> vertex = {
1. Я тебе вроде предлагал использовать `std::pair`, не получилось?
2. Если ты знаешь размер вектора, то логичней и более эффективно использовать `std::array`
3. `Vertex` - это вершина. Твой же вектор, это что угодно, но не вершина. Нужно переименовать.

```suggestion
  const std::array<std::pair<VertexId, VertexId>, size> connections = {
```

2021-11-15 12:43 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  for (int i = 0; i < EDGE_NUMBER; i++) {
Всегда предпочитай такую запись:
```suggestion
  for (const auto& connection : connections) {
```

2021-11-15 13:09 UTC, MatveevAlexy commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  const std::vector<std::array<VertexId, 2>> vertex = {
Насколько я помню, я пытался использовать и array, и pair, но получилось только с вектором

2021-11-16 23:35 UTC, Friend-LGA requested changes

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  bool AreConnected(const VertexId& _vertex_id1, const VertexId& _vertex_id2) {
Ну что, ты думаешь я тебе на каждую ошибку буду указывать? В прошлом ревью писал, что нет смысла просто так ставить `_` в названии агрументов

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  const std::vector<std::pair<VertexId, VertexId>> connections = {
> Насколько я помню, я пытался использовать и array, и pair, но получилось только с вектором

У других получается, попробуй ещё раз. И не забудь добавить `#include`. Есть у меня подозрение, что в прошлый раз из-за этого не работало

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  bool HasVertex(const VertexId& vertex_id) const {
Повторяю, читай `Naming Convention`

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  bool AreConnected(const VertexId& _vertex_id1, const VertexId& _vertex_id2) {
Как по-твоему, это `const` функция?

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +    vertexes_.emplace_back(GetNewVertexId());
Плохая идея использовать сырое значение `id` до того момента, как ты вообще добавил объект. Нужно все делать последовательно. И вся логика по работе с `id` у тебя сосредоточена в функции `GetNewVertexId()`. Лучше будет так:
```suggestion
    const auto& new_vertex = vertexes_.emplace_back(GetNewVertexId());
    connection_list_.insert({new_vertex.id, std::vector<EdgeId>()});
```

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  std::vector<Vertex> vertexes_;
Такого слова в английском языке нет, множественное число - это `vertices`

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +                        std::max(_vertex_id1, _vertex_id2));
Зачем тебе брать `min` и `max`? Последовательность не принципиальна, не усложняй

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +        if (edges_[edge_id].vertex_id1 == _vertex_id1 &&
Уже обсуждали раньше. Ты не можешь полагаться на то что `index` == `id`. А что, если мы добавим удаление граней? Тогда нужно будет программу переписывать. Так можно делать, когда ты решаешь очень конкретный алгоритм с конкретной имплементацией. Но у нас немного другая задача, поэтотому логика должна быть аналогичной `HasVertex`

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +            edges_[edge_id].vertex_id2 == _vertex_id1) {
Работает? Похоже что тут должно быть так:
```suggestion
        if (edges_[edge_id].vertex_id1 == _vertex_id2 ||
            edges_[edge_id].vertex_id2 == _vertex_id2) {
```

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  int vertex_new_id_ = 0, edge_new_id_;
Почему вершине задал дефолтное значение, а грани нет? В этом вот проблема написания нескольких переменных в одну строку, сложно читать, и легко что-то пропустить.

2021-11-16 23:35 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +    edges_.emplace_back(edge_new_id_++, std::min(_vertex_id1, _vertex_id2),
Что мы говорили в прошлый раз про `vertex`? `GetNewEdgeId()`

2021-11-18 14:11 UTC, Friend-LGA requested changes

2021-11-18 14:11 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +        assert(hasEdge(edge_id && "Edge index is out of range"));
Вот эти `assert` уже перебор. Я говорил нужно добавить валидацию входных параметров в функции. А так, если каждую строчку валидировать, то у нас вся программа из валидаторов будет состоять)) Достаточно только валидации входных аргументов, в начале функции.

2021-11-18 14:11 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +    throw std::runtime_error("");
Сообщение все-таки не помешало бы "Edge doesn't exist", например

2021-11-18 14:11 UTC, Friend-LGA commented on 02_knight_and_princess/matveev_alexey/task2.cpp
> +  const Edge& getEdge(EdgeId edge_id) const {
1. Почему `private`, вполне валидный `public` метод
2. Договорились же передавать по `const` ссылке

2021-11-18 15:57 UTC, Friend-LGA requested changes
Так как у нас структура репозитория обновилась, перенеси свои файлы в новую папку

2021-11-19 16:26 UTC, Friend-LGA approved these changes
![](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

2021-11-19 17:11 UTC, merged