alexey_matveev/task_05
Friend-LGA/msu_course_cpp_323 pull request #76
Opened 2021-10-23 16:19 UTC by MatveevAlexy

2021-11-19 17:27 UTC, Friend-LGA requested changes
После 4ого таска будем смотреть

2021-12-16 07:05 UTC, Friend-LGA requested changes

2021-12-20 11:42 UTC, Friend-LGA requested changes
Ты проверял, программа не падает, если папки `temp` нет?

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/config.hpp
> +const char* getLogFilePath();
В том что ты делаешь нет смысла)) У тебя итак публичная константа, и метод просто возвращает её.
```cpp
constexpr const char* TEMP_DIRECTORY_PATH = "temp/";
constexpr const char* LOG_FILE_NAME = "log.txt";
static const std::string LOG_FILE_PATH = TEMP_DIRECTORY_PATH + LOG_FILE_PATH;
```
В этом случае тебе `cpp` файл вообще не будет нужен

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/graph_printer.hpp
> +  std::string printEdge(const Edge& edge) const;
Валидные публичные методы, почему ты решил их убрать? Кто-то может захотеть распечатать вершину или грань, это нормальный интерфейс.

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/main.cpp
> +//#include <cstdlib>
Комментарии

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/main.cpp
>  }
Эта функция теперь ненужна

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/graph.hpp
> +#pragma once
Ты понял, зачем вообще нужен этот препроцессор? Он удостоверяется в том, что дальнейший код не проходится компилятором несколько раз. Как думаешь, должен ли быть какой-то код, перед этим флагом? В таком случае он теряет свой смысл.

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/graph_generator.cpp
> +}
Эти функции можно перенести в приватный неймспейс и убрать из интерфейса

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/graph_printer.hpp
> +#include <vector>
Не используется

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/logger.hpp
> +#include "graph_printer.hpp"
Все используются в этом файле?

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/logger.cpp
> +#include "graph_printer.hpp"
Все используются?

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/logger.hpp
> +  std::string getCurrentDateTime();
В приватный неймспейс

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/logger.hpp
> +  std::string getCurrentDateTime();
В приватный неймспейс

2021-12-20 11:42 UTC, Friend-LGA commented on matveev_alexey/main.cpp
> +                  "temp/graph_" + std::to_string(i) + ".json");
`temp/` должен быть в логгере как `TEMP_DIRECTORY_PATH`

2021-12-20 16:33 UTC, MatveevAlexy commented on matveev_alexey/main.cpp
> +                  "temp/graph_" + std::to_string(i) + ".json");
В логгере? Не в конфиге?

2021-12-22 12:30 UTC, Friend-LGA requested changes

2021-12-22 12:30 UTC, Friend-LGA commented on matveev_alexey/logger.hpp
> +#include <fstream>
длобавь `<string>`

2021-12-22 12:30 UTC, Friend-LGA commented on matveev_alexey/main.cpp
> +//ругается локальная машина
Обсудили, комментарии из кода надо убрать

2021-12-22 12:30 UTC, Friend-LGA commented on matveev_alexey/main.cpp
>  }
Эта функция больше ненужна

2021-12-22 12:30 UTC, Friend-LGA commented on matveev_alexey/main.cpp
> +  // std::experimental::filesystem::create_directory(config::TEMP_DIRECTORY_PATH);
убрать

2021-12-22 13:38 UTC, Friend-LGA requested changes

2021-12-22 13:38 UTC, Friend-LGA commented on matveev_alexey/config.hpp
> +namespace config {
Под общим неймспейсом

2021-12-22 13:38 UTC, Friend-LGA commented on matveev_alexey/config.hpp
> +const std::string LOG_FILE_NAME = static_cast<std::string>("log.txt");
`static_cast` не нужен

2021-12-22 15:30 UTC, Friend-LGA requested changes

2021-12-22 15:30 UTC, Friend-LGA commented on matveev_alexey/logger.cpp
> +                   uni_course_cpp::config::LOG_FILE_NAME) {
убери лишний код

2021-12-22 16:10 UTC, Friend-LGA approved these changes
🎉

2021-12-22 16:10 UTC, merged