anton_gadzikovskiy/task_01
Friend-LGA/msu_course_cpp_323 pull request #79
Opened 2021-10-24 20:34 UTC by AGadzuk

2021-11-03 10:02 UTC, Friend-LGA requested changes

2021-11-03 10:02 UTC, Friend-LGA commented on 01_hello_world/anton_gadzikovskiy/hello_world.cpp
> +}
Видишь гит ругается на `No newline at end of file`

2021-11-03 10:02 UTC, Friend-LGA commented on 01_hello_world/anton_gadzikovskiy/README.md
> +![alt text](https://github.com/AGadzuk/msu_course_cpp_323/blob/anton_gadzikovskiy/task_01/01_hello_world/anton_gadzikovskiy/screenshot.jpg?raw=true)
Укажи просто локальную ссылку на файл в папке
`(screenshot.jpg)`

2021-11-05 19:19 UTC, AGadzuk commented on 01_hello_world/anton_gadzikovskiy/hello_world.cpp
> +}
Я не понимаю о чем Вы, у меня все проверки прошли и ошибку не показывает.

2021-11-06 12:33 UTC, Friend-LGA approved these changes

2021-11-11 17:58 UTC, merged