roman kuprii/task 05
Friend-LGA/msu_course_cpp_323 pull request #81
Opened 2021-10-27 12:03 UTC by kapkappa

2021-11-06 16:15 UTC, Friend-LGA requested changes
И задание немного расширилось, почитай

2021-11-06 16:15 UTC, Friend-LGA commented on .gitignore
> +temp
Укажи конкретно свою папку

2021-11-06 16:15 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/main.cpp
> +  void write(std::ofstream& logfile, const std::string log) const {
1. `log` - это действие. Называть так строку не правильно, а вот что правильно - назвать так метод.
2. Каждый раз передавать файл - это оверкилл. Укажи его один раз и пусть он помнит куда 
логировать.
3. Почему `const` значение, а не ссылка?
```suggestion
  void log(const std::string& string) const {
```

2021-11-06 16:15 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/main.cpp
> +  static shared_ptr<Logger> log;
Эта переменная где-то используется?

2021-11-11 22:07 UTC, kapkappa commented on 02_knight_and_princess/roman_kuprii/main.cpp
> +  void write(std::ofstream& logfile, const std::string log) const {
По поводу 2 пункта - std::ofstream& logfile это объект, чтобы не передавать в логгер его нужно в нём сохранить тогда, это укладывается в логику логгера?

2021-11-15 22:20 UTC, Friend-LGA requested changes
1. Разбил на файлы очень поверхностно. Каждая логическая единица должна иметь свой файл. Прочитай ещё раз задание, я там даже пример набора файлов дал.
2. В логгере лишняя логика, которая непосредственно к логгеру не относится. Все что умеет логгер - записывать передаваемую строку. Все.

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +constexpr double RED_TRASHOULD = 0.33;
Не похоже, что эти константы относятся к графу, больше похоже что они относятся к генератору графа. Надо бы тебе получше разбить программу на файлы. `graph.hpp` и `graph.cpp` - не достаточно.

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +bool is_edge_id_included(const EdgeId& id, const vector<EdgeId>& edge_ids);
```suggestion
bool is_edge_id_included(const EdgeId& id, const vector<EdgeId>& edge_ids) const;
```

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +constexpr int INVALID_ID = -1;
Нужно спрятать из глобальной зоны видимости, но и в публичном интерфейсе ему делать особо нечего.
Должно быть достаточно спрятать его в приватный неймспейс:
```cpp
namespace {
  constexpr int INVALID_ID = -1;
}
```

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +const std::string JSON_GRAPH_FILENAME = "temp/graph_";
Не используется в этом файле

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +#include <vector>
header файлы должны включать в себя минимально необходимый набор инклудов (как, в принципе и любой файл, но для хэдеров это вдвойне принципиально) Чем больше инклудов - тем медленнее скорость компиляции финальной программы.

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +enum class Color { Gray, Green, Blue, Yellow, Red };
Находится в глобальном неймспейсе, причем с очень универсальным именем. Лучше внеси его внутрь `Graph::Edge::Color`

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +double get_random_number();
Функции в глобальном скопе, должны быть где-то, где им полагается. Подумай.

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +struct Edge {
Слишком универсальная структура в глобальном скопе. Не лишним было бы твой код спрятать внутри какого-нибудь неймспейса, например
```cpp
namespace kuprii {
 ...
}
```

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +void paint_edges(Graph& work_graph);
Похоже, что это все, к этому файлу не относится

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/main.cpp
> +constexpr int GRAPH_NUMBER = 10;
Писал раньше, что обновил условие задачи, чтобы этот параметр задавался пользователем

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/logger.hpp
> +  Logger() {}
Лучше использовать `= default`

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/logger.hpp
> +               const Logger& logger);
Не, это не логика логера

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/logger.hpp
> +  void log(std::ofstream& logfile, const std::string& text) const {
Логфайл будет логично передать только один раз, в методе, например `set_logfile()`
```suggestion
  void log(const std::string& text) const {
```

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/logger.hpp
> +constexpr int COLORS_NUMBER = 5;
Не логика логгера

2021-11-15 22:20 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/log.txt
> +time Graph 0, Generation Started
:))) `time` - имелось ввиду время, а не слово "time"
Обновил описание задачи, теперь должно быть понятнее, посмотри.

2021-11-19 09:59 UTC, kapkappa commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +bool is_edge_id_included(const EdgeId& id, const vector<EdgeId>& edge_ids);
Это не метод класса, а глобальная функция

2021-11-19 11:18 UTC, kapkappa commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +enum class Color { Gray, Green, Blue, Yellow, Red };
то есть сделать namespace Graph, внутри которого namespace Edge? Потому что struct Edge не член класса Graph..

2021-11-19 11:19 UTC, kapkappa commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +double get_random_number();
В namespace-е специально для этих функций?

2021-11-19 11:20 UTC, kapkappa commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +struct Edge {
Logger тоже довольно универсальный класс, как и Graph, как и Vertex. Их всех нужно запрятать в namespace такой? Тогда в нём будет по сути целиком код из graph.hpp/cpp logger.hpp . (Кроме того, у нас уже есть uni_cpp_practice namespace который содержит код целиком (пока непонятно зачем правда..) )

2021-11-19 14:21 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +bool is_edge_id_included(const EdgeId& id, const vector<EdgeId>& edge_ids);
Понял, проглядел.

2021-11-19 14:22 UTC, Friend-LGA commented on 02_knight_and_princess/roman_kuprii/graph.hpp
> +enum class Color { Gray, Green, Blue, Yellow, Red };
Не, если `Edge` не находится внутри `Graph`, никаких конфликтующих по названию неймспейсов плодить не надо, сделай `Edge::Color`

2021-11-19 15:13 UTC, Friend-LGA requested changes
УБери вот эти, миллион `.orig` файлов из ПР

2021-11-19 15:13 UTC, Friend-LGA commented on roman_kuprii/graph_printer.cpp
> +namespace graph_printing {
Ты не праввильно понял идею, что должен включать в себя `graph_printing`
Тут должно быть то, что в данный момент у тебя реализовано как
```cpp
std::string Graph to_json() const;
std::string Vertex to_json() const;
std::string Edge to_json() const;
```
Соответвтеноо, если вынести эту логику из `Graph`
```cpp
// graph_printing.hpp
namespace uni_cpp_practice {

namespace graph_printing {

std::string graph_to_json(const Graph& graph);
std::string vertex_to_json(const Vertex& graph);
std::string edge_to_json(const Graph& graph);

} // graph_printing

} // uni_cpp_practice
```

А то что ты сейчас сюда вынес - все эти функции, не сказать, что напрямую связаны друг с другом, скорее это набор несильно связанной логики, которая никогда не может нигде понадобиться, кроме как в функции `main()`, а в таком случае, нет особого смысла выносить эти функции из `main.cpp` файла, ибо они существуют только ради того, чтобы быть вызванными из `main()`. Они не являются интерфейсом, который можно переиспользовать в будущем из других мест программы. Все эти функции очень специфичны, именно для реализации `main()`, поэтому им скорее место рядом с `main()`

В целом, можно их объединить, например как `logging_helper.hpp`, без `cpp` файла, потому что тут, по большому счету вообще нет интерфейса, а лишь набор функций. Поэтому нет особого смысла разбивать на `header` и `source` файлы.

`helper` обычно называют набор логики, которая не связана друг с другом, и нужна либо для переиспользования одного и того же кода в разных местах, либо чтобы убрать не важный код с глаз долой)) Но это такое себе...

2021-11-19 15:13 UTC, Friend-LGA commented on roman_kuprii/logger.hpp
> +  static Logger& get_logger(std::ofstream& f) {
геттер не должен менять объект. Он же может использоваться в 100 разных мест, и каждый раз как ты будешь брать логгер, ты будешь изменять файл, куда он пишет? ЭЖто плохая логика. Добавь отдельную функцию для этого, например 
```cpp
void Logger::set_output(const std::optional<std::string>& file_path) {
  if (!file_path.has_value()) {
    if (ofstream_.has_value()) {
      ofstream_->close();
      ofstream_ = std::nullopt;
    }
    return;
  }

  ofstream_ = std::ofstream(file_path.value());

  if (!ofstream_->is_open()) {
    throw std::runtime_error("Failed to create file stream");
  }
}

void Logger::log(const std::string& string) {
  std::cout << string << std::endl;
  if (ofstream_.has_value()) {
    ofstream_.value() << string << std::endl;
  }
}
```
Как-то так

Идея такая, в дефолтном состоянии у логгера вообще нету стрима, но при этом он должен работать, поэтому имеет смысл сделать стрим опциональным. А раз стрим у нас опциональный, значит и метод `set_output` должен иметь возможность удалить стрим, поэтому `filename` тоже должен быть опциональным и в случае `null` мы просто удаляем стрим

2021-11-19 15:13 UTC, Friend-LGA commented on roman_kuprii/logger.hpp
> +  void log(std::string text) const {
`const` ссылка. Сколько уже можно?

2021-11-19 15:13 UTC, Friend-LGA commented on roman_kuprii/logger.hpp
> +  Logger& operator=(const Logger&) = delete;
`move` тоже должен быть удален
```cpp
  Logger(Logger&&) = delete;
  Logger& operator=(Logger&&) = delete;
```

2021-11-22 23:05 UTC, kapkappa commented on roman_kuprii/graph_generator.hpp
> +void paint_edges(Graph& work_graph);
Почему они не часть интерфейса? Добавить рёбра определенного цвета, раскрасить рёбра (добавить рёбра всех цветов - название суть не отражает но это другой вопрос) - всё это может быть вполне доступно пользователю, нет?

2021-11-23 11:55 UTC, Friend-LGA commented on roman_kuprii/graph_generator.hpp
> +void paint_edges(Graph& work_graph);
Это все детали внутренней реализации. Думаешь пользователь хочет/будет этим заниматься? Он хочет настолько высокоуровневый интерфейс, насколько это возможно. Пользователь хочет вызвать `generate()`, а все остальное чтобы произошло само собой, без его вмешательства. Ему нет смысла раскрашивать ребра, потому что это должно происходить динамически. Иначе зачем вообще нам инкапсулировать `generation` логику? Это сделано для того, чтобы спрятать ненужные детали имплементации от пользователя, чтобы снизить уровень информационного шума.

2021-11-23 13:11 UTC, Friend-LGA requested changes

2021-11-23 13:11 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +    graph_generating::paint_edges(my_graph);
Какой смысл в генераторе, если ты не пользуешься удобным интерфейсом, а можно сказать, пишешь процедурную логику по вызову последовательности функций. Где же здесь удобство?
```suggestion
    const auto graph = uni_cpp_practice::graph_generation::generate(depth, new_vertices_num);
```

2021-11-23 13:11 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +using namespace uni_cpp_practice;
Обсуждали же ещё в начале семестра, что включать неймспейсы полностью - плохая идея.

2021-11-24 09:49 UTC, Friend-LGA requested changes

2021-11-24 09:49 UTC, Friend-LGA commented on roman_kuprii/graph_generating.hpp
> +Graph generate(const int& depth, const int& new_vertices_num);
Ну сколько можно. Фундаментальные типы нужно передавать по значению, а не `const` ссылке

2021-11-24 09:49 UTC, Friend-LGA commented on roman_kuprii/main.cpp
> +    uni_cpp_practice::logging_helping::write_graph(my_graph, graph_num);
nit: Ну тут, конечно, очень длинные неймспейсы получились. Лучше бы ты где-нибудь `using` написал, а то из крайности в крайность. Или `using` не работает для названия функций?

2021-11-24 09:49 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +    const Edge::Color& color) const {
Вот эта функция будет очень медленно работать...
Ну ладно, пусть будет так. Будешь потом ещё программу оптимизировать, отдельной задачей.
Пока можешь оставить как есть.

2021-11-24 10:49 UTC, kapkappa commented on roman_kuprii/main.cpp
> +    uni_cpp_practice::logging_helping::write_graph(my_graph, graph_num);
Да, у меня не сработало

2021-11-24 12:42 UTC, Friend-LGA requested changes

2021-11-24 12:42 UTC, Friend-LGA commented on roman_kuprii/graph.cpp
> +                             const bool& initialization) {
???

2021-11-24 12:42 UTC, Friend-LGA commented on roman_kuprii/graph_generating.cpp
> +  std::mt19937 gen(rd());
Вынеси дублирующийся код
```cpp
VertexId get_random_vertex_id(const std::vector<VertexId> vertex_ids);
```

2021-11-24 14:05 UTC, merged