tevfik_aksoy/task_05
Friend-LGA/msu_course_cpp_323 pull request #90
Opened 2021-11-15 17:54 UTC by AxoyTO

### Init commit:

- Divided the program into headers.
- Added logger prototype

2021-11-15 22:46 UTC, Friend-LGA requested changes
Нужно разбить не только на `.hpp`, но и на `.cpp` файлы

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +int Logger::k = 1;
`no newline`
Сам хоть свои ПР просматриваешь? Как можно пропустить эту большую красную иконку?

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +}
Глобальные функции - плохо, кто угодно может их вызывать, а зачем? У всех функций должна быть своя зона видимости

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +struct Logger {
Договаривались, если сложная логика - то это `class` а не `struct`

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +struct Logger {
В задании сказано, что нужно реализовать этот класс как `Singleton`. У тебя не очень похоже.
Должно быть что-то типа 
```cpp
static Logger& get_instance();
```

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +struct Logger {
Очень много сложной логики. Все, что должен делать логгер - это логировать строку, и все.
```cpp
void log(const std::string& string);
```

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +void PrintandWrite(std::ostream& os, std::ostream& fs, const string& str) {
Внезапно решил полностью изменить стиль наименования функций? `Naming Convention`

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +using std::vector;
В header файлах опасно писать такие вещи. Представь, теперь каждый, кто импортирует твой файл, будут вынуждены использовать твои сокращения.

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +using VertexDepth = int;
Твои кастомные типы тоже, не должны находиться в глобальном скопе, они непосредственно связаны с классом граф, и будет лучше спрятать их внутрь класса.

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +struct Vertex {
Слишком универсальная структура в глобальном скопе. Не лишним было бы твой код спрятать внутри какого-нибудь неймспейса, например
```cpp
namespace aksoy {
 ...
}
```

2021-11-15 22:46 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph_generator.hpp
> +#include "graph.hpp"
А тут забыл `include guard`

2021-11-16 20:06 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph_generator.hpp
> +#include "graph.hpp"
Вроде исправил

2021-11-16 20:45 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +using std::vector;
Хорошо

2021-11-16 20:52 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +int Logger::k = 1;
Да, извините

2021-11-16 20:57 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +}
Хорошо

2021-11-17 09:56 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +using VertexDepth = int;
Внутрь класса или какого нибудь namespace? потому что не только в классе они но еще в структурах

2021-11-17 10:12 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +struct Vertex {
Сделал, теперь они в namespace graph_structures

2021-11-17 18:03 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +struct Logger {
Попробовал исправить 🙂

2021-11-17 19:12 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +using VertexDepth = int;
Можно в неймспейс

2021-11-17 19:16 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +struct Vertex {
Не очень хорошее название неймспейса. Обычно название должно быть более специфическим. Graph Structures - это такое же абстрактное общее название, которое может с чем-то конфликтовать. Ладно, я укажу что-нибудь более конкретное в описании задачи.

2021-11-17 19:25 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +struct Vertex {
Назови его `uni_cpp_practice`

2021-11-17 20:33 UTC, Friend-LGA requested changes

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +  assert(logfile.is_open() && "Error while opening the log file!");
`assert` лучше использовать для проверки входных параметров, другими словами для проверки самого себя. А если ты ожидаешь, что в программе может произойти ошибка, то это исключительное поведение - лучше выкинуть `exception`, например `std::runtime_error`
```cpp
throw std::runtime_error("Error while opening the log file!");
```

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +#include <cassert>
В этом файле нету `assert`

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +  print_and_write(string, std::cout, logfile);
В этой функции нету особого смысла, это и есть логика функции `log`, можно вызывать код напрямую отсюда.

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +  std::ofstream logfile(logfilename, std::ofstream::app);
Каждый раз открывать стрим кажется немного затратно. Будет логичней создавать стрим сразу при указании файла и хранить его внутри логгера.

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +void Logger::set_file(const std::string filename) {
ссылка?

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +#include <vector>
Все эти библиотеки тут используются?

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +  void set_file(std::string filename = "./temp/log.txt");
Нет, логгер не знает где он находится.
Тут одно из 2ух:
- либо логгер вообще не решает куда должен писать, и тогда filename должен быть передан снаружи
- либо логгер сам решает где должен создаваться файл для логирования. Но в этом случае вообще нет смысла передавать его извне.

Я считаю, что первый вариант лучше второго, таким образом мы уменьшаем зону ответственности класса, чем упрощаем его логику. Поэтому дефолтного значения тут быть не должно.

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +  std::string logfilename;
`thelogfilenamewherewewillwritedata` - как насчет такого?
`log_filename`, или лучше просто `filename`. Зачем нам `Log.log_filename`? Это как `Vertex.vertex_id`

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  char date_and_time[100] = {0};
`C-Style Array`
Используй `std::put_time`

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
>  int main() {
Очень длинная `main()` функция. Разбей её на более мелкие.

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  logger.set_file();
Что это такое?) Тебя вызов такой функции не смущает?

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  int graph_number = 1;
Почему 1 а не 0? Зачем тебе вообще эта переменная?

2021-11-17 20:33 UTC, Friend-LGA commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          {"gray", graph.total_edges_of_color(Edge::Color::Gray)},
У тебя ведь специально для этого была функция `color_to_string`. Плохая практика использовать строки в коде.

2021-11-18 11:11 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +namespace validation {
+

2021-11-18 11:49 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +bool does_vertex_exist(const VertexId& id, const std::vector<Vertex>& vertices);
Понял

2021-11-18 11:51 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +void Vertex::add_edge_id(const EdgeId& _id) {
хорошо, да будет достаточно но `Declaration shadows a field of 'uni_cpp_practice::Vertex'`

2021-11-18 11:52 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +struct Vertex {
Хорошо

2021-11-18 11:53 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +void Logger::set_file(const std::string filename) {
+

2021-11-18 11:54 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +}
😳

2021-11-18 11:56 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +#include <vector>
Нет, исправил

2021-11-18 11:57 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +  std::string logfilename;
😂😳😳 хорошо, исправляю

2021-11-18 11:58 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +using namespace graph_structures;
Я понмю, конечно, хорошо

2021-11-18 12:13 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +std::string Edge::to_JSON() const {
Сделал

2021-11-18 12:17 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +}
Внутри namespace? Я его переместил в класс GraphPrinter, поэтому его тут больше нет

2021-11-18 12:18 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.hpp
> +#define _GRAPH_
Хорошо, узнал, спасибо

2021-11-18 13:16 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +  assert(logfile.is_open() && "Error while opening the log file!");
Понял

2021-11-18 13:27 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph_generator.hpp
> +                           const int new_vertices_num);
Сделал

2021-11-18 13:27 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +          {"gray", graph.total_edges_of_color(Edge::Color::Gray)},
Понял, да обновил

2021-11-18 13:27 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  int graph_number = 1;
Да я просто думал, что с 1 начинаем индекс, исправил

2021-11-18 13:28 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
> +  logger.set_file();
😂😂😳 Смущает) исправил

2021-11-18 13:29 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.hpp
> +  void set_file(std::string filename = "./temp/log.txt");
Я думаю, что понял

2021-11-18 13:31 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/logger.cpp
> +  print_and_write(string, std::cout, logfile);
+

2021-11-18 14:17 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +bool edge_id_exists_in_vertex(const EdgeId& edge_id,
Сделал, но тогда остается только валидация на глубину в неймспейсе, его тоже можно перенести в граф класс и потом избавиться от неймспейса, не знаю насколько это логично

2021-11-18 14:40 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/main.cpp
>  int main() {
Хорошо

2021-11-19 14:19 UTC, Friend-LGA requested changes

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +  const Graph generate();
Это единственная публичная функция, зачем все остальные находятся в `public`?

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +  std::vector<uni_cpp_practice::VertexId> filter_connected_vertices(
Эта функция вообще не должна быть частью интерфейса, её достаточно перенести в приватный неймспейс

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +      const std::vector<uni_cpp_practice::VertexId>& vertices);
Эта функция вообще не должна быть частью интерфейса, их достаточно перенести в приватный неймспейс

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +  const float RED_EDGE_PROBABILITY_ = 0.33;
Они должный быть глобальными константами 
```suggestion
  constexpr float GREEN_EDGE_PROBABILITY_ = 0.1;
  constexpr float BLUE_EDGE_PROBABILITY_ = 0.25;
  constexpr float RED_EDGE_PROBABILITY_ = 0.33;
```
Зачем они в `hpp` файле? Они же не являются частью интерфейса

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_printer.hpp
> +  GraphPrinter(const Graph& graph) : graph(graph){};
Коллизия наименований. Так делать нельзя, названия должны отличаться

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/graph_printer.hpp
> +  const Graph& graph;
`Naming Convention`

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/logger.hpp
> +    if (file_stream_->is_open())
`filename.has_value()` надо бы проверить сначала

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +namespace logger {
Вообще нет смысла создавать этот неймспейс - это все логика `main()`, просто вспомогательные функции, чтобы реализовать логику в `main()`. Это не отдельная логика, она вся связана с `main()`

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
>  int main() {
Большая функция `main()`, разбей на более маленькие. Например как-то так:
```cpp
// ... some other logic ...

int main() {
  const int depth = handle_depth_input();
  const int new_vertices_num = handle_new_vertices_num_input();
  const int graphs_count = handle_graphs_count_input();
  const auto generator = GraphGenerator(depth, new_vertices_num);

  for (int i = 0; i < graphs_count; i++) {
    log_start(logger, i);
    const auto graph = generator.generate();
    log_finish(logger, i, graph);

    const auto graph_printer = GraphPrinter(graph);
    write_to_file(graph_printer.print(), "graph_" + std::to_string(i) + ".json");
  }

  return 0;
}
```

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +  int graph_number = 0;
Зачем тебе эта переменная, у тебя же есть индекс итерирования - `i`

2021-11-19 14:19 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +      const auto graph = GraphGenerator(max_depth, new_vertices_num).generate();
Зачем ты в цикле каждый раз создаешь генератор, достаточно создать его один раз вне цикла.

2021-11-19 14:26 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +  int graph_number = 0;
... Да... точно! Просто я забыл из-за переноса эту логику сюда с моего прототипа логгера

2021-11-19 14:41 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.cpp
> +
Аааа, я не понял, что весь код в неймсейс, я думал, что только структуры и кастомные типы, понял, исправлю

2021-11-19 15:10 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +  const Graph generate();
+

2021-11-19 15:10 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +  std::vector<uni_cpp_practice::VertexId> filter_connected_vertices(
+

2021-11-19 15:46 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +  const float RED_EDGE_PROBABILITY_ = 0.33;
+, я думал их надо закрыть,  но вроде их и так не видно с других файлов

2021-11-19 15:51 UTC, AxoyTO commented on tevfik_aksoy/logger.hpp
> +    if (file_stream_->is_open())
Не очень понял, filename же у меня просто параметр функции set_file, её нет в классе
Если имели ввиду `file_stream.has_value()` то понятно, но has_value и is_open тут эквивалентны, или нет?

2021-11-19 16:18 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +      const auto graph = GraphGenerator(max_depth, new_vertices_num).generate();
+

2021-11-19 16:19 UTC, AxoyTO commented on tevfik_aksoy/graph_printer.hpp
> +  GraphPrinter(const Graph& graph) : graph(graph){};
-> `graph(_graph)`

2021-11-19 16:28 UTC, Friend-LGA commented on tevfik_aksoy/logger.hpp
> +    if (file_stream_->is_open())
Да, перепутал, `file_stream_`

2021-11-19 16:28 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +}
+

2021-11-19 16:30 UTC, Friend-LGA requested changes

2021-11-19 16:30 UTC, Friend-LGA commented on tevfik_aksoy/logger.hpp
> +    if (file_stream_->is_open())
И перенеси в `cpp`, длинноватая функция для `hpp`

2021-11-19 16:30 UTC, Friend-LGA commented on tevfik_aksoy/logger.cpp
> +    file_stream_->close();
if `file_stream_.has_value()`

2021-11-19 16:30 UTC, Friend-LGA commented on tevfik_aksoy/logger.cpp
> +  if (file_stream_->is_open()) {
if `file_stream_.has_value()`

2021-11-19 16:49 UTC, AxoyTO commented on tevfik_aksoy/logger.hpp
> +    if (file_stream_->is_open())
Хорошо

2021-11-19 17:15 UTC, AxoyTO commented on 02_knight_and_princess/tevfik_aksoy/graph.cpp
> +}
Понял

2021-11-19 17:33 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
>  int main() {
+

2021-11-19 18:03 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +bool Graph::does_color_match_vertices(
Реализовал, но тут return val нужно, компилятор ругает, поэтому добавил Unknown to enum class Color

2021-11-19 18:04 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +  if (depth_map[depth].empty())
Да, точно

2021-11-20 18:27 UTC, Friend-LGA requested changes

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +                                               vertices_[destination_id]);
У тебя нет прямой связи между индексом и `id`, ты должен непосредственно искать вершину в коллекции по `id`, можно эту логику вынести в функцию
```suggestion
  const auto& source_vertex = get_vertex(source_id);
  const auto& destination_vertex = get_vertex(destination_id);
  const auto color = calculate_color_for_edge_(source_vertex,
                                               destination_vertex);
```
Ты мог бы использовать `vertices_[vertex_id]`, если бы у тебя вершины были `unordered_map`
```cpp
std::unordered_map<VertexId, Vertex> vertices_;
```
Тогда да, ты мог бы получать вершину сразу по её `id`

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +}
Каждый раз проходиться по всем граням - это очень медленная логика. Лучше было бы хранить отдельную коллекцию, которая сразу могла бы вернуть все грани, например как-то так:
```cpp
std::unordered_map<Edge::Color, std::vector<EdgeId>> colored_edges_map_;
```
И тогда логичней будеть возвращать весь вектор
```cpp
const std::vector<EdgeId>& get_colored_edges(const Edge::Color& color) const;
```

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +    generate();
Зачем ты вызываешь `generate()`???

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +}  // namespace uni_cpp_practice
no newline, сколько можно?

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +  float get_random_probability() const;
Эта функция не выглядет как часть интерфейса, скорее её место в приватном неймспейсе

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.hpp
> +constexpr float RED_EDGE_PROBABILITY_ = 0.33;
1. Глобальные переменные не называются с `_` на конце. Разве `Naming Convention` такой сложный? Сколько можно делать одни и те же ошибки?
2. Они не нужны как часть публичного интерфейса. Перенеси их в приватный неймспейс в `cpp` файл.

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/graph_printer.cpp
> +std::string GraphPrinter::print() const {
Раз уж ты выделил отдельный объект для распечатки графа - тогда уж нужно всю логику распечатки вынести сюда. Она все равно не очень вписывается в зону отвественности графа.
```cpp
namespace {

std::string print_vertex(const Vertex& vertex) {
  // ...
}

std::string print_edge(const Edge& edge) {
  // ...
}

} // namespace

namespace uni_cpp_practice {

std::string GraphPrinter::print() const {
  // ...
}

} // namespace uni_cpp_practice
```
И, соответственно, убрать все методы `to_JSON()`

2021-11-20 18:27 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +
Чтобы не писать миллион раз 
```cpp
uni_cpp_practice:: ...
```
Проще будет написать 
```cpp
using Graph = uni_cpp_practice::Graph;
using Vertex = uni_cpp_practice::Vertex;
using Edge = uni_cpp_practice::Edge;
using GraphPrinter = uni_cpp_practice::GraphPrinter;
using GraphGenerator = uni_cpp_practice::GraphGenerator;
using Logger = uni_cpp_practice::Logger;
```

2021-11-20 19:36 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +    generate();
Убрал, это с прошлой реализации было

2021-11-20 19:38 UTC, AxoyTO commented on tevfik_aksoy/graph_generator.hpp
> +constexpr float RED_EDGE_PROBABILITY_ = 0.33;
Забыл удалить после переноса, удалил сейчас

2021-11-20 19:42 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +  assert(!are_vertices_connected(source_id, destination_id) &&
То что вершины существуют? Они же внутри проверки are_vertices_connected

2021-11-20 19:55 UTC, AxoyTO commented on tevfik_aksoy/graph_printer.cpp
> +std::string GraphPrinter::print() const {
++

2021-11-20 21:00 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +                                               vertices_[destination_id]);
Сделал get_vertex

2021-11-20 21:48 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +}
++, сделал, просто есть сомнение с try catch блоком(опасно ли так?)

2021-11-21 15:23 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +  assert(!are_vertices_connected(source_id, destination_id) &&
Ну и что, валидация всегда должна быть иаксимально изолированной. Лучше не полагаться на то, что кто-то другой за нас сделает работу, а вдруг имплементация изменится внутри `are_vertices_connected `. Для нас важно знать, что эта функция работает правильно и тут нет багов. В любом случае все `assert()` будет отключены в production версии

2021-11-21 15:57 UTC, Friend-LGA requested changes

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/graph.hpp
> +                         const std::vector<Vertex>& vertices) const;
Не имеет смысла передавать в эту функцию `vertices`, у неё и так есть доступ к вершинам.
```suggestion
  bool does_vertex_exist(const VertexId& id) const;
```

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/graph.hpp
> +  Vertex get_vertex(const VertexId& id) const;
`get` - означает вернуть элемент, а не его копию
```suggestion
  Vertex& get_vertex(const VertexId& id);
```
Имеет смысл перенести её в `public`

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/graph.hpp
> +  int total_edges_of_color(const Edge::Color& color) const;
особого смысла в функции нет, скорее это лишний шум в интерфейсе. Любой сможет получить эту информацию как `graph.get_colored_edges(color).size()`. Ради этого нет смысла создавать отдельную функцию

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/graph.cpp
> +  return colored_edges_map_.at(color);
Да, ты должен быть уверен что тут не будет `exception`. Так как мы всегда можем запросить цвет, и в случае, если граней нет, мы хотим просто вернуть пустой вектор - вот один из вариантов,Ю как этого добиться:
```suggestion
  if (colored_edges_map_.find(color) == colored_edges_map_.end()) {
    static std::vector<EdgeId> empty_result;
    return empty_result;
  }
  return colored_edges_map_.at(color);
```

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/graph_generator.cpp
> +namespace {
Уже писал тебе о том что приватный неймспейс должен быть снаружи. К тому же у тебя тут 2 приватных неймспейса, объедини их в один.

2021-11-21 15:57 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +  const auto colors = set_colors(graph);
`set` - значит установить, указать, например
```cpp
auto& colors = get_colors();
set_colors(colors);
```
Поэтому такого не может быть что функция `set_colors` возвращает значение, тогда это должно быть `get_colors`. Более того, это не `colors` - это количество граней, разложенных по цветам.
И у тебя уже есть логика, чтобы их взять - `graph.get_colored_edges()`. Поэтому можешь просто удалить этот лишний метод и использовать `graph.get_colored_edges()`. Ещё логичней будет его перенести внутрь  метода `log_colors()`, они тебе все равно в этой функции не нужны.

2021-11-21 16:12 UTC, AxoyTO commented on tevfik_aksoy/graph.hpp
> +  int total_edges_of_color(const Edge::Color& color) const;
Согласен, поменяю

2021-11-21 16:21 UTC, AxoyTO commented on tevfik_aksoy/graph.hpp
> +                         const std::vector<Vertex>& vertices) const;
А да, точно, при переносе с неймспейса валидации забыл это убрать

2021-11-21 16:29 UTC, AxoyTO commented on tevfik_aksoy/graph.hpp
> +  Vertex get_vertex(const VertexId& id) const;
Хорошо

2021-11-21 16:40 UTC, AxoyTO commented on tevfik_aksoy/graph.cpp
> +  return colored_edges_map_.at(color);
Понял, спасибо!

2021-11-21 16:52 UTC, AxoyTO commented on tevfik_aksoy/main.cpp
> +  const auto colors = set_colors(graph);
Избавился от этого, теперь только вызываю `log_colors()` и там все обрабатывается

2021-11-21 17:46 UTC, Friend-LGA requested changes

2021-11-21 17:46 UTC, Friend-LGA commented on tevfik_aksoy/main.cpp
> +std::vector<std::pair<Edge::Color, int>> get_colors(const Graph& graph) {
Где используется?

2021-11-21 17:48 UTC, Friend-LGA commented
Не работает

```zsh
➜  tevfik_aksoy git:(pr/90) ✗ ./main 
Enter graphs_count: 4
Enter max_depth: 4
Enter new_vertices_num: 4
libc++abi: terminating with uncaught exception of type std::runtime_error: Error while opening the log file!
[1]    35610 abort      ./main
```

2021-11-21 17:56 UTC, Friend-LGA approved these changes

2021-11-21 17:57 UTC, merged