novikov_dmitry/task_05
Friend-LGA/msu_course_cpp_323 pull request #92
Opened 2021-11-18 11:16 UTC by dimchanov

2021-11-18 15:33 UTC, Friend-LGA requested changes

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/logger.cpp
> +  print_and_write(string, log_file);
В этом методе нет особого смысла

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/logger.cpp
> +  log_file.open(filename_, std::fstream::out | std::fstream::app);
Ты каждый раз будешь открывать стрим? И, к тому же не закрывать его.
А не лучше создать приватный объект стрима, открыть его один раз, и постоянно в него писать?

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/logger.cpp
> +  assert(log_file.is_open() && "Error while opening the log file!");
Получается у нас программа всегда будет падать, если мы не вызовем `set_file()`? Довольно печально. Это его дефолтное состояние, и в дефолтном состоянии он всегда роняет программу? Плохая логика.

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/logger.cpp
> +  filename_ = filename;
Тут можно сразу открывать стрим, если сделать стрим приватной переменной и хранить её

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/logger.cpp
> +void Logger::set_file(const std::string filename) {
Так как у нас может быть файл, а может не быть, имеет смысл использовать здесь `std::optional` и останавливать логирование в файл, если передается `std::nullopt`

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/graph.cpp
> +bool check_color_valid(const Vertex& first_vertex,
Все-таки это должно быть в приватном неймспейсе, попробуй добавить сюда `[[maybe_unused]]`
```suggestion
[[maybe_unused]] bool check_color_valid(const Vertex& first_vertex,
```

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/graph.hpp
>   Depth get_depth() const {
>     return (depth_map_.size() > DEFAULT_DEPTH) ? (depth_map_.size() - 1)
>                                                : DEFAULT_DEPTH;
>   }
>   const std::vector<VertexId>& get_vertices_at_depth(const Depth& depth) const {
>     assert(depth <= get_depth() && "Depth level doesn't exist");
>     return depth_map_.at(depth);
>   }
>   const Vertex& get_vertex(const VertexId& id) const {
>     assert(has_vertex(id) && "Vertex doesn't exist");
>     return vertex_map_.at(id);
>   }
>   const Edge& get_edge(const EdgeId& id) const {
>     assert(has_edge(id) && "Edge doesn't exist");
>     return edge_map_.at(id);
>   }

Всех таких длинных функций, или сложных, с несколькими действиями, как например с ассертами, не должно быть в хэдере, перенеси их в `cpp`

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/graph.hpp
>  #include <vector>
Не верю что у тебя столько библиотек в хэдере используется

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/graph_generation.hpp
> +int get_random_number(const int size);
по `const` значению не передаются фундаментальные типы, убери `const`

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/main.cpp
> +    }
Зачем обернуто в пустой `if`?

2021-11-18 15:33 UTC, Friend-LGA commented on 02_knight_and_princess/novikov_dmitry/main.cpp
>  int main() {
У тебя просто громадная функция `main()` разбей на более мелкие, чтобы получилось что-нибудь вроде этого:
```cpp
// ... some other logic ...

int main() {
  const int depth = handle_depth_input();
  const int new_vertices_num = handle_new_vertices_num_input();
  const int graphs_count = handle_graphs_count_input();

  const auto params = GraphGenerationParams(depth, new_vertices_num);
  const auto generator = GraphGenerator(params);

  for (int i = 0; i < graphs_count; i++) {
    logger.log(start_string(i));
    const auto graph = generator.generate();
    logger.log(finish_string(i, graph));

    const auto graph_printer = GraphPrinter(graph);
    write_to_file(graph_printer.print(), "graph_" + std::to_string(i) + ".json");
  }

  return 0;
}
```

2021-11-19 16:09 UTC, Friend-LGA commented on novikov_dmitry/logger.cpp
> +  if (file_stream_->is_open()) {
`file_stream_.has_value()`

2021-11-19 16:11 UTC, Friend-LGA commented on novikov_dmitry/logger.cpp
> +  assert(file_stream_->is_open() && "Error while opening the log file!");
Так как здесь ошибка вне нашего контроля, то это не проверка на баги, это исключительное состояние, лучше выкинуть `exception`
```suggestion
  if (!file_stream_->is_open()) {
    throw std::runtime_error("Failed to create file stream");
  }
```

2021-11-19 16:11 UTC, Friend-LGA commented on novikov_dmitry/logger.hpp
> +      file_stream_->close();
Не однострочная функция, лучше убрать её тело в `cpp`

2021-11-19 16:12 UTC, Friend-LGA commented on novikov_dmitry/main.cpp
> +namespace logger {
Вся эта логика напрямую связана с `main()`, нет особого смысла отделять её в отдельный `namespace`

2021-11-19 16:16 UTC, Friend-LGA commented on novikov_dmitry/main.cpp
> +  logger.set_file("./temp/log.txt");
Усложняет чтение `main()` и не добавляет полезной информации - это детали имплементации, лучше тоже вынести в отдельную функцию, например
```suggestion
  auto& logger = prepare_logger();
```

2021-11-19 16:20 UTC, Friend-LGA commented on novikov_dmitry/main.cpp
> +      file_out.close();
1. Логика генерации не зависит от того открылся файл или нет.
2. Лучше тоже вынести лишнюю логику в функцию, а то много информационного шума. Трудно понять что происходит.
```suggestion
      logger.log(start_string(i));
      const auto graph = uni_cpp_practice::graph_generation::generate_graph(
          depth, new_vertices_num);
      logger.log(end_string(i, graph));
      
      write_to_file(graph.to_string(), "graph_" + std::to_string(i) + ".json");
```

2021-11-20 18:45 UTC, Friend-LGA requested changes
1. `JSON` файлы тоже должны теперь создаваться внутри `/temp` директории. А у тебя все ещё в основной папке.
2. Ну и раз уж придется исправлять `JSON`, то заодно, вынеси логику по распечатке графа в `graph_printing.hpp` и `graph_printing.cpp`
```cpp
// graph_printing.hpp
namespace uni_cource_cpp {

namespace graph_printing {

std::string print_graph(const Graph& graph);
std::string print_vertex(const Vertex& vertex);
std::String print_edge(const Edge& edge);

}

}
```
А старые методы `to_string()` удали. Это не совсем ответственность графа - распечатывать самого себя, и будет лучше выделить эту логику в отдельную сущность, и сейчас самое время, пока ты разбиваешь код на файлы.

В остальном все хорошо, почти готово!

2021-11-20 18:45 UTC, Friend-LGA commented on novikov_dmitry/logger.cpp
> +      file_stream_ = std::nullopt;
nit: Вот это уже не обязательно, все объекты удалятся вместе с родительским объектом. Главное - это закрыть стрим было.

2021-11-22 17:10 UTC, Friend-LGA requested changes
Пара мелочей и все, давай добивай

2021-11-22 17:10 UTC, Friend-LGA commented on novikov_dmitry/graph.hpp
> +  const std::pair<VertexId, VertexId> get_binded_vertices() const {
Возвращать константное значение нет смысла. Либо просто копию, либо `const` ссылку

2021-11-22 17:10 UTC, Friend-LGA commented on novikov_dmitry/graph_printer.cpp
> +const std::string print_vertex(const uni_cpp_practice::Vertex& vertex) {
Так как мы возвращаем копию данных, нам не важно что дальше с ней происходит, нет смысла в `const`

2021-11-22 17:10 UTC, Friend-LGA commented on novikov_dmitry/graph_printer.cpp
> +    if (it != vertex.get_edge_ids().begin()) {
3 раза вызываешь `get_edge_ids()` - дублирование кода и потенциально просадка производительности. Чем 3 раза получать одно и тоже значение, просто сохрани его в локальную переменную
```cpp
const auto& edge_ids = vertex.get_edge_ids();
```

2021-11-22 17:19 UTC, Friend-LGA commented on novikov_dmitry/main.cpp
> +  const std::string dafault_filename = "./temp/Graph";
nit: Тут получается уже не просто `filename`, а почти `file_path`. Но на самом деле, тут ни то и ни другое.
Это `temp_folder_path` + `file_name_prefix`
Ну это сейчас не принципиально. Просто старайся не смешивать логику, это потенциально ведет к проблемам. Если тебе нужно директория, объяви её отдельно, нужен специальный префикс или суффикс - называй вещи своими именами.

2021-11-22 19:24 UTC, dimchanov commented on novikov_dmitry/main.cpp
> +  const std::string dafault_filename = "./temp/Graph";
А я вот был почти уверен, что за это стукнут, но забыл исправить пока pull/merge и подобные штуки делал, чтобы конфликт убрать(((

2021-11-23 11:49 UTC, Friend-LGA approved these changes

2021-11-23 11:49 UTC, Friend-LGA commented on novikov_dmitry/main.cpp
> +  const std::string filename_suffix = ".json";
nit: Больше похоже на глобальные константы.

2021-11-23 15:20 UTC, merged