xieyu_wang/task_04
Friend-LGA/msu_course_cpp_323 pull request #93
Opened 2021-11-18 18:37 UTC by AncientEncoder

2021-11-18 18:40 UTC, AncientEncoder commented
No need check now not finished yet will be finish on Friday)))

2021-11-19 13:06 UTC, Friend-LGA requested changes
Just to change state. Request review, when ready

2021-11-21 17:01 UTC, Friend-LGA requested changes
Not bad. Much better than in the beginning, but still needs some improvements.

2021-11-21 17:01 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  std::string getResult() { return graph_.toString(); }
Incorrect. The result of the generator is a graph. And it actually should be returned from the `generate()` method itself
```cpp
Graph generate() const;
```

2021-11-23 16:33 UTC, AncientEncoder commented on xieyu_wang/main.cpp
> +  Edge(int id, int fromVertexId, int toVertexId, std::string color)
not really underestand here you means `Edge(int id, int fromVertexId, int toVertexId,const std::string color)
      : id(id),
        fromVertexId(fromVertexId),
        toVertexId(toVertexId),
        color(color) {}` here?

2021-11-24 19:40 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  std::vector<std::vector<int>> connections_;
```cpp
Graph generate() {
  auto graph = Graph();
  graph.add_vertex();
  generate_grey_edges(graph);
  generate_green_edges(graph);
  generate_blue_edges(graph);
  generate_yellow_edges(graph);
  generate_red_edges(graph);
  return graph;
}
```

2021-11-26 17:36 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  Edge(int id, int fromVertexId, int toVertexId, std::string color)
Here is the only one place, where it is applicable. Sure, it is `std::string`, but your example above is still wrong.
it should be `const std::string&`

2021-11-26 19:13 UTC, Friend-LGA requested changes
Pretty good. Just a few more issues to fix.

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/generator.cpp
> +}
instead of these functions
```cpp
bool Generator::vertxGenerateProbabilityController(int depth);
bool Generator::specialEdgeGenerateProbabilityController(Edge::Color color, int depth)
```
you should have something like
```cpp
float get_probability_gray(int max_depth, int depth) {
  assert(max_depth >= 0);
  assert(depth >= 0);
  assert(max_depth >= depth);
  const float result = 1.0 - ((float)depth / (float)max_depth);
  if (std::isnan(result)) {
    return 0.0;
  }
  return result;
}

float get_probability_yellow(int max_depth, int depth) {
  assert(max_depth >= 0);
  assert(depth >= 0);
  assert(max_depth >= depth);
  const float result = (float)depth / (float)max_depth;
  if (std::isnan(result)) {
    return 0.0;
  }
  return result;
}

bool is_lucky(float probability) {
  assert(probability >= 0);
  assert(probability <= 1.0);
  std::random_device rd;
  std::mt19937 gen(rd());
  std::bernoulli_distribution distribution(probability);
  return distribution(gen);
}
```

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/generator.cpp
> +  }
I think I told you, that you don't need this function `getPresentVertexId()`
```suggestion
  for (auto& vertex : graph.vertices()) {
    if (is_lucky(GREEN_EDGE_PROBABILITY)) {
      graph.addEdge(vertex.id, vertex.id, Edge::Color::Green);
    }
  }
```

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/generator.cpp
> +  int nexDepth;
You don't need this variable

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/generator.h
> +  Graph generateGrey(int presentDepth, int fromVertexId);
Why `generateGrey` returns `Graph`, this doesn't make sense
And why is it public?

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/generator.cpp
> +  auto graph = generateGrey();
```cpp
auto graph = Graph();
generateGrey(graph);
...
```

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +Graph::Graph() {}
You don't need this

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  return vertices_.back();
```suggestion
  const auto& newVertex = vertices_.emplace_back(getNextVertexId());
  return newVertex;
```

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +Vertex Graph::addVertex() {
Why are you returning a copy, you should return reference

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  }
code duplication

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +    getVertex(toVertexId).depth = getVertex(fromVertexId).depth + 1;
Don't call `get_vertex()` on every row. Just make a local variable that holds it.

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  strGraph.pop_back();
if `vertices_.size() == 0` then you will delete the opening bracket. You should check if you need to delete these symbols.

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +void Graph::addEdge(int fromVertexId, int toVertexId, Edge::Color color) {
`const` reference

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/main.cpp
>    std::cin >> newVerticesNum;
You should validate user input input

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  Generator generator(maxDepth, newVerticesNum);
`const`

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/vertex.cpp
> +std::vector<int> Vertex::getEdgeIds() const {
Why do you make a copy?

2021-11-26 19:13 UTC, Friend-LGA commented on xieyu_wang/vertex.cpp
> +Vertex::Vertex(int id) : id(id){};
names collision

2021-11-28 04:29 UTC, AncientEncoder commented on xieyu_wang/edge.cpp
> +  }
not really undersatand here you means I need to move iut to main.cpp? or create a new class `edge_color_to_string`?

2021-11-28 08:38 UTC, AncientEncoder commented on xieyu_wang/generator.h
> +  std::default_random_engine generator_;
But if we dont need this how we konw the maxDepth and NumOfVertices?

2021-11-28 08:39 UTC, AncientEncoder commented on xieyu_wang/generator.h
> +  std::default_random_engine generator_;
use'generate' funcation?

2021-11-28 08:41 UTC, AncientEncoder commented on xieyu_wang/generator.h
> +  Graph generateGrey(int presentDepth, int fromVertexId);
it will be error if I give it graph so I make it a obj in it and  return it

2021-11-28 08:42 UTC, AncientEncoder commented on xieyu_wang/graph.cpp
> +Graph::Graph() {}
ok

2021-11-28 09:07 UTC, AncientEncoder commented on xieyu_wang/edge.cpp
> +#include "edge.h"
you means `hpp`?

2021-12-02 14:06 UTC, AncientEncoder commented on xieyu_wang/graph.cpp
> +  strGraph.pop_back();
Nummm I think here is not that logic the pop back is delete the last two symble  `,\n` here is for the last vertex

2021-12-02 15:33 UTC, Friend-LGA requested changes

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/edge.cpp
> +}
no newline again!!!

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/edge.cpp
> +std::string edgeColorToString(Edge::Color color) {
`const` ref

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/edge.cpp
> +      break;
```cpp
return "gray";
```

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/edge.cpp
> +  return strColor;
```cpp
throw std::runtime_error("Failed to convert the color");
```

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/vertex.hpp
> +#include <assert.h>
where is it?
`<cassert>`

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/main.cpp
> +  std::cin >> maxDepth;
You need to check it here

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  return newVertex;
```cpp
return vertices_.emplace_back(getNextVertexId());
```

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  }
What about Edge::Color::Green

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.hpp
> +constexpr float RED_EDGE_PROBABILITY = 0.33;
Why do you need these constants in interface

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +  std::vector<int> verticesPresentLevel;
not used

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +  for (auto& vertex : graph.getVertices()) {
`const`

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +  for (int depth = 0; depth < maxDepth_; depth++) {
`depth < maxDepth_ - 2`

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +      }
```cpp
for (const auto& fromVertex : presentDepth) {
  if (isLucky(RED_EDGE_PROBABILITY)) {
    const auto randomVertexId = get_random_vertex_id(destinationDepth); 
    graph.addEdge(fromVertex, randomVertexId, Edge::Color::Red);
  }
}
```

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +    for (const auto& fromVertex : presentDepth) {
`fromVertexId`

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +    for (auto vertex = presentDepth.begin(); vertex < presentDepth.end();
`vertexIt < presentDepth.end() - 1`

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +      for (const auto& toVertex : destinationLevel) {
The same as with red edges, to random unconnected vertex
```cpp
const auto unconnected_vertex_ids = get_unconnected_vertex_ids(fromVertexId, destinationLevel);
```

2021-12-02 15:33 UTC, Friend-LGA commented on xieyu_wang/graphGenerator.cpp
> +  const float result = (float)depth / (float)maxDepth_;
probably -1

2021-12-02 17:27 UTC, AncientEncoder commented on xieyu_wang/graphGenerator.cpp
> +  for (int depth = 0; depth < maxDepth_; depth++) {
no its not  ` <= ` its  ' <' so need to be -1 Ive tested it

2021-12-02 17:27 UTC, AncientEncoder commented on xieyu_wang/graphGenerator.cpp
> +  const float result = (float)depth / (float)maxDepth_;
yes tested

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/Edge.cpp
> +const std::string edgeColorToString(Edge::Color color) {
Nope, wrong place for `const`. You should never return the value by `const`, only reference. It doesn't matter for us what will happen to this copy of `std::string` outside of the function, as it just a copy and cannot brake anything.

But the argument - `Edge::Color`, should be `const` reference, as it is not necessary to make a copy here, just reference is enough.

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +      if (fromVertexEdgeId == toVertexEdgeId && fromVertexId != toVertexId) {
Again, what about `Edge::Color::Green`? Test it, create a graph with 1 vertex, which vas 1 edge to itself (which should be green), then the function `isConnected` should return `true`. But your function will return `false`.

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
>    for (int depth = 1; depth < maxDepth_; depth++) {
You told me:
> no its not <= its ' <' so need to be -1 Ive tested it

Then, it should be `<=` here?

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +    const std::vector<int> destinationLevel,
`const` value -> should be `const` reference

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.hpp
> +  std::vector<int> getUnconnectedVertexIds(
Also, should be outside of the interface, as `isLucky`

2021-12-04 20:11 UTC, Friend-LGA commented on xieyu_wang/graph.cpp
> +  }
Not resolved

2021-12-04 20:12 UTC, Friend-LGA commented on xieyu_wang/edge.cpp
> +std::string edgeColorToString(Edge::Color color) {
Incorrectly resolved

2021-12-04 20:17 UTC, Friend-LGA requested changes

2021-12-04 20:17 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +        if (randomVertexId != -1) {
It shouldn't be possible to have `-1` value here

2021-12-04 20:17 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +        const auto randomVertexId = getRandomVertexId(unconnectedVertexIds);
You, probably should check `unconnectedVertexIds.size()` here

2021-12-04 20:17 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +  }
it is better to add an `assert` in the beginning of the function to validate that `destinationLevelIds` is not empty. As this function doesn't make sense otherwise

2021-12-05 15:23 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
> +    const std::vector<int> destinationLevel,
no here it should be `-2 ` if its `<=` if `-1` then `< ` is ok

2021-12-07 17:08 UTC, AncientEncoder commented on xieyu_wang/GraphGenerator.cpp
>    for (int depth = 1; depth < maxDepth_; depth++) {
no here it should be -2 if its <= if -1 then < is ok

2021-12-08 11:45 UTC, Friend-LGA requested changes

2021-12-08 11:45 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +      if (fromVertexEdgeId == toVertexEdgeId && fromVertexId != toVertexId) {
```cpp
for (const auto& from_edge_id : get_edge_ids(from_vertex_id)) {
    for (const auto& to_edge_id : get_edge_ids(to_vertex_id)) {
      if (from_edge_id == to_edge_id) {
        if (fromVertexId == toVertexId) {
          const auto& edge = get_edge(from_edge_id);
          if (edge.from_vertex_id() == edge.to_vertex_id()) {
            return edge.id();
          }
        } else {
          return from_edge_id;
        }
      }
    }
  }
```

2021-12-09 13:45 UTC, Friend-LGA requested changes

2021-12-09 13:45 UTC, Friend-LGA commented on xieyu_wang/Edge.cpp
> +std::string edgeColorToString(const Edge::Color color) {
```suggestion
std::string edgeColorToString(const Edge::Color& color) {
```

2021-12-09 13:45 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
> +        const auto edge = getEdge(fromVertexEdgeId);
Why do you make copy here
```suggestion
        const auto& edge = getEdge(fromVertexEdgeId);
```

2021-12-09 13:45 UTC, Friend-LGA commented on xieyu_wang/Graph.cpp
>          return true;
1) Why did you write it so complicated
```suggestion
        if (edge.fromVertexId == edge.toVertexId) {
          return true
        }
```
2. This is incorrect, it will only work for green edges, how's about other edges?

Look. You can check this small example:
```cpp
graph.addVertex();
graph.addVertex();
graph.addVertex();

graph.addEdge(0, 1); // gray
graph.addEdge(1, 2); // gray
graph.addEdge(1, 1); // green

assert(graph.isConnected(0, 1) == true); // gray
assert(graph.isConnected(1, 0) == true); // gray

assert(graph.isConnected(1, 2) == true); // gray
assert(graph.isConnected(2, 1) == true); // gray

assert(graph.isConnected(1, 1) == true); // green

assert(graph.isConnected(0, 0) == false); // no edge
assert(graph.isConnected(2, 2) == false); // no edge
assert(graph.isConnected(0, 2) == false); // no edge
assert(graph.isConnected(2, 0) == false); // no edge
```

This is how your graph should operate. Right now this function is broken.

2021-12-09 15:04 UTC, Friend-LGA requested changes
Crashing
```
Enter Max Depth:8
Enter new vertices num:2
Generator.................done
GrayEdgeGenerate..........done
GreenEdgeGenerate.........done
BlueEdgeGenerate..........done
Assertion failed: (!destinationLevelIds.empty() && "destinationLevelIds is empty!!!"), function getRandomVertexId, file GraphGenerator.cpp, line 135.
[1]    38134 abort      ./main
```

2021-12-09 15:04 UTC, Friend-LGA commented on xieyu_wang/GraphGenerator.cpp
> +        const auto randomVertexId = getRandomVertexId(destinationDepth);
Probably here
```
if (!destinationDepth.empty()) {
```

2021-12-09 15:20 UTC, Friend-LGA approved these changes
🎉 :

2021-12-09 15:25 UTC, AncientEncoder commented
yeeeeeeeh

2021-12-09 15:25 UTC, merged