kirill_tolstobrov/task_04
Friend-LGA/msu_course_cpp_323 pull request #98
Opened 2021-11-22 20:17 UTC by lanzy4

2021-11-23 15:12 UTC, Friend-LGA requested changes
Перечитай задание. Там все довольно подробно расписано с примерами кода.

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +                     Color edge_color = Color::Grey) {
1) `const` ссылка
2) Добавь валидацию на новый входной параметр - `color`. Ещё лучше - вычисляй его динамически, так будет меньше кода и проще логика, чем добавлять валидацию.

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  std::vector<std::pair<int, int>> depths_map;
1) `Naming Convention`
2) А не проще будет
```suggestion
  std::vector<std::vector<VertexId>> depths_map_;
```

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  void set_depths_map(std::vector<std::pair<int, int>>& d_m) {
Договаривались избегать однобуквенных названий

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  enum { GREEN_PROB = 10, BLUE_PROB = 25, RED_PROB = 33, PROB_COEF = 100 };
1) `enum` - это `C` а не `C++`, читай `C vs C++`
2) Лучше вынести это в глобальный скоп. Редко когда классы, структуры или перечисления задаются прямо в локальном скопе.
3) `Naming Convention`
4) Лучше не импользовать значение опций, как их порядок, например, что будет, если у нас вероятность красных и синих граней будет одинаковая? Твой `enum` сломается. Вынеси их в константы и добавь функцию, которая будет возвращать веротяность в зависиомти от цвета `int get_probability(const Edge::Color& color)`

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  graph.set_depths_map(depths_map);
Карта должна заполняться изнутри графа, это его остветственность

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  srand(std::time(NULL));
Это что-то `C`ишное

2021-11-23 15:12 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
>  }
Очень длинная функция, лучше разбить на более мелкие, примерно:
```suggestion
Graph generate_random_graph(int depth, int new_vertices_num) {
  auto graph = Graph();
  generate_grey_edges(graph, depth, new_vertices_num);
  generate_green_edges(graph);
  generate_blue_edges(graph);
  generate_yellow_edges(graph);
  generate_red_edges(graph);
  return graph;
}
```

2021-11-23 16:23 UTC, lanzy4 commented on kirill_tolstobrov/main.cpp
> +  explicit Vertex(const VertexId& init_id = 0) : id(init_id), depth(0) {}
Но я же не передаю здесь глубину, просто инициализирую нулем. Нужно логику глубины из вершины убрать и поместить в граф? Тогда мне придется всю генерацию стркового представления вершины переместить в граф

2021-11-23 16:41 UTC, lanzy4 commented on kirill_tolstobrov/main.cpp
> +  Graph() : depth(0) {
Ну мне же нужно чем то это значение проинициализировать

2021-11-24 11:48 UTC, Friend-LGA requested changes

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +        break;
```suggestion
        return "grey";
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  Graph() : depth(0) { depths_map_.emplace_back(); }
Лучше добавить элемент когда он понадобится

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    VertexId new_id = get_new_vertex_id();
`const`

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    }
```suggestion
    if (connections_map_.find(id1) == connections_map_.end() ||
      connections_map_.find(id2) == connections_map_.end()) {
        return false;
    }
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    auto& vertex2 = vertices_[id2];
`const`

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    return Edge::Color::Grey;
```cpp
trow std::runtime_error("Can't get binded color");
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
>      connections_map_[id2].push_back(edge.id);
А если id одинаковые

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +      }
Избавиться от дублирование

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +          depth = vertices_[id2].depth;
Зачем тебе эта переменная?

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    const int new_vertices_num_ = 0;
зачем `_`

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    int new_vertices_num = params_.new_vertices_num_;
`const`

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  bool random_bool(double true_prob) const {
Зачем `double`

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +            graph.bind_vertices(j, graph.get_vertices().size() - 1);
```cpp
const auto new_vetrex_id = graph.add_new_vertex();
graph.bind_vertices(vertex_id, new_vertex_id);
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +           j <= graph.depths_map_[i][graph.depths_map_[i].size() - 1]; j++) {
```cpp
const auto& vertex_ids_at_depth = graph.depths_map_[i];
for (VertexId vertex_id ...)
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    constexpr float GREEN_PROB = 0.1;
вынеси в глобальные константы

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    std::mt19937 rng(dev());
```cpp
VertexId get_random_vertex_id(const std::vector<Vertex>& vertices);
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    }
```cpp
for (int depth = 0; depth < graph.depth() - 1; depth++) {
  const auto vertices = graph.get_vertices_at_depth(depth);
  const auto next_depth_vertices = graph.get_vertices_at_depth(depth + 1);
  for (const auto& vertex : vertices) {
    const auto& unconnected_vertices = get_unconnected_vertices(vertex, next_depth_vertices);
    if (random_bool(yellow_probability)) {
      const auto random_vertex_id = get_random_vertex_id(unconnected_vertices);
      graph.add_edge(vertex.id, random_vertex_id)
    }
  }
}
```

2021-11-24 11:48 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  GraphGenerator generator(params);
`const`

2021-11-24 14:30 UTC, Friend-LGA requested changes

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  int depth;
```suggestion
  int depth = 0;
```

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  std::string color_to_string() const {
Это не логика `Edge`

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    return "";
Либо убери
Либо `throw std::runtime_error()`

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +      vertices_[to_id].depth = vertices_[from_id].depth + 1;
```cpp
Vertex& get_vertex(const VertexId& id); // поиск по вектору
```

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
>    operator std::string() const {
Вынести наружу
```cpp
class Edge {
  enum class Color;
  operator std::string() const;
}

std::string color_to_string();

operator Edge::std::string() const {
// ...
}

```

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +    const int new_vertices_num = params_.new_vertices_num;
По факту ненужные переменные

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +          VertexId binding_id =
`const`

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +            VertexId binding_id = random_vertex_id(possible_connections);
`const`

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +      for (VertexId cur_id : vertex_ids_at_depth) {
for (const VertexId)

2021-11-24 14:30 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +      for (VertexId cur_id : vertex_ids_at_depth) {
`const`

2021-11-24 15:05 UTC, Friend-LGA requested changes

2021-11-24 15:05 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  Edge::Color get_binding_color(const VertexId& id1, const VertexId& id2) {
функция должна быть `const`

2021-11-24 15:05 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  Edge::Color get_binding_color(const VertexId& id1, const VertexId& id2) {
Добавь `get_vertex() const`

2021-11-24 15:05 UTC, Friend-LGA commented on kirill_tolstobrov/main.cpp
> +  throw std::runtime_error("Nonexistent color");
попробуй убрать

2021-11-24 15:28 UTC, Friend-LGA approved these changes

2021-11-24 15:29 UTC, merged